### ISSUE TITLE
Group schemas

### ISSUE THREAD

**Issue by PiekiBi** [swagger-api/swagger-ui#10171]
### Content & configuration

I would like to group the schemas. The way like you can do with the paths and the tags.

**Comment by Goutamchoudhary907** [comment]
I would like to work on this can you describe the issue a bit more 
and hey @shockey can you assign me this

**Comment by PiekiBi** [comment]
Yes for sure.
I plan the apis for our project. Because our frontend and our backend get developed by different persons it is important to define the dtos ans apis correctly.

For that i write the

**Comment by Roshanchenna** [comment]
Hey, can you assign me this. I would like to work on it.

**Comment by ponelat** [comment]
Hi @PiekiBi thanks for bringing this up. It's not something we'd actively want to support just yet, mostly because it's not an OpenAPI specification thing, like `tags` is. However this could be a good use-case for vendor extensions (like `x-tags`) and a SwaggerUI plugin. Although I'm not sure if/how Writerside can extend its use of SwaggerUI.

Going to close this out as a feature request which is out of scope for the code code.
