### ISSUE TITLE
Jackson-databind reflection problem with swagger-ui

### ISSUE THREAD

**Issue by mebigfatguy** [swagger-api/swagger-ui#10220]
Using swagger-ui version 2.2.26 and jackson-databind version 2.18.1, on jdk21, i get tons of these errors..

ERROR io.swagger.v3.core.jackson.ModelResolver - Neither 'findJsonValueMethod' nor 'findJsonValueAccessor' found in jackson BeanDescription. Please verify your Jackson version.

When i look in jackson-databind, findJsonValueMethod has indeed been recently removed but i do see

    /**
     * Method for locating accessor (readable field, or "getter" method)
     * that has
     * {@link com.fasterxml.jackson.annotation.JsonValue} annotation,
     * if any. If multiple ones are found,
     * an error is reported by throwing {@link IllegalArgumentException}
     *
     * @since 2.9
     */
    public abstract AnnotatedMember findJsonValueAccessor();
    
So i was wondering if anyone could tell me what i am doing wrong here??
(it would also be nice to log beanDesc.getClass().getClassName() in that error message.)

**Comment by funfried** [comment]
I have the same issue, it seems it's related to having webflux and webmvc libraries inside the classpath (which is not good and I have to fix that in my case sometime), but what's strange is that the error message disappears when downgrading back to swagger 2.2.25 still having webflux and webmvc in my classpath.

**Comment by ftreede** [comment]
This is definetely a bug in swagger. Jackson removed the deprecated findJsonValueMethod method with 2.18: https://github.com/FasterXML/jackson-databind/pull/4525

https://github.com/swagger-api/swagger-core/blob/df88c8a8ebaae1cb8ec39d1af295d07620dcaf87/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L1157-L1179

This code first tries the new method, finds it and invokes it. However, if that method returns null, the return is not called and it then tries the old method.

**Comment by ftreede** [comment]
This is actually an issue in swagger, core: check over there: https://github.com/swagger-api/swagger-core/issues/4755

**Comment by codesimplicity** [comment]
As I came here when trying to get that running in GraalVM (Spring Native), I wanted to add some more details for others having the same issue:
- the [current handling](https://github.com/swagger-api/swagger-core/blob/v2.2.28/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L1157-L1180) assumes that the `Exception` is thrown because the method does not exist but in GraalVM I think it may be a different error - is it worth to create a PR to improve that error handling? (haven't checked the exact exception thrown)
- I had to add this to `RuntimeHints` in my Spring Boot app to remove the error:
```kotlin
            .registerType(
                BeanDescription::class.java,
                MemberCategory.INVOKE_DECLARED_METHODS,
            )
```
- I have also added some more `RuntimeHints` until it worked:
```kotlin
            .registerType(MethodHandles.Lookup::class.java)
            .registerType(
                Schema31Mixin.TypeSerializer::class.java,
                MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
            )
            .registerType(
                JsonSchema::class.java,
                MemberCategory.INVOKE_DECLARED_CONSTRUCTORS,
            )
```

The metadata repositories will hopefully include those details soon but until then...
