### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by pexaku** [swagger-api/swagger-ui#1030]
Going through instruction makes me see something like that:

command: docker build -t swagger-ui-builder
```
/usr/local/lib/node_modules/docker/src/docker.js:259
        throw err;
              ^
Error: ENOENT, lstat '/opt/swagger-ui-master/build'
```

**Comment by aviadavi** [comment]
I get the same error too. any update?

**Comment by ponelat** [comment]
I'm no expert, but I think you're using an [npm module called docker](https://www.npmjs.com/package/docker)  instead of the [container library](http://www.docker.com/), you can go check it out... docker has a [cool tutorial](http://www.docker.com/tryit/)

They are very different things, in fact before this issue I had no idea about the npm module ;)
**You don't need to use docker**, to put it simply it's like a mini-operating system that helps when we use different systems.

To build the files...
```bash
#install gulp globally
npm install -g gulp

cd /some/path/to/swagger-ui
npm install
gulp
```
And you should have it, but also remember we commit the built files, so unless you make changes you shouldn't need to build it at all.

@fehguy can you confirm (that part about not needing docker)

**Comment by pexaku** [comment]
@ponelat 
That's the answer, simply we were using bad lib @aviadavi

**Comment by webron** [comment]
Closing it now. Please reopen if still an issue.
