### ISSUE TITLE
Json paring in Swagger UI fired errors.

### ISSUE THREAD

**Issue by nurinamu** [swagger-api/swagger-ui#1130]
I genereated swagger json from swagger-springmvc : 1.0.2. And I was fetching it on swagger-ui : 2.1.0-M2. But it printed javascript errors in console.

Below json is test data.
```javascript
{"apiVersion":"1.0","swaggerVersion":"1.2","apis":[{"path":"/default/admin-controller","description":"Admin Controller","position":0},{"path":"/default/authorization-endpoint","description":"Authorization Endpoint","position":0},{"path":"/default/comic-admin-controller","description":"Comic Admin Controller","position":0},{"path":"/default/error-controller","description":"Error Controller","position":0},{"path":"/default/media-controller","description":"Media Controller","position":0},{"path":"/default/member-controller","description":"Member Controller","position":0},{"path":"/default/meta","description":"META API 입니다.","position":0},{"path":"/default/slots-admin-controller","description":"Slots Admin Controller","position":0},{"path":"/default/token-endpoint","description":"Token Endpoint","position":0},{"path":"/default/video-admin-controller","description":"비디오 컨트롤러 입니다.","position":0},{"path":"/default/whitelabel-approval-endpoint","description":"Whitelabel Approval Endpoint","position":0}],"authorizations":[],"info":{"title":"default Title","description":"Api Description","termsOfServiceUrl":"Api terms of service","contact":"Contact Email","license":"Licence Type","licenseUrl":"License URL"}}
```

After this happening, I tried it on swagger-ui : 2.0.24. It is fine.

Please let me know what should I do for fix this issue on 2.1.0-M2.

**Comment by webron** [comment]
What are the errors you're getting?

**Comment by nurinamu** [comment]
![2015-04-09 11 29 02](https://cloud.githubusercontent.com/assets/1445542/7059406/b2c413c8-deab-11e4-842f-5dd1b434455a.png)

My console printed this.

**Comment by webron** [comment]
In the latest versions of swagger-ui, it takes any older version of a Swagger definition and converts it to 2.0, which it then uses for display.

It looks like there's a problem converting your 1.2 Swagger definition, and it looks like the problem is with (at least) one of the model definitions. However, from the console error you shared, it is impossible to know which model definition is actually causing the problem. 

To continue troubleshooting the problem, I'd suggest the following options:
- Debug it in your own web browser's console and see exactly on which model definition it fails. Share that model definition and we can continue from there.
- Share the full definition, which means the API Declarations as well. It looks like your API is quite varied, so that may require sharing quite a few files.
- Upgrade swagger-springmvc. I don't know which version you use, but some older versions have known issues that produce somewhat problematic Swagger definitions. Note that the project's name has changed now to `springfox`. If you can update the the *latest* version, that would probably be best as that produces Swagger 2.0 definitions which would make this step (the conversion) obsolete.

**Comment by webron** [comment]
@nurinamu - any updates on this?

**Comment by fehguy** [comment]
Please reopen if still an issue.
