### ISSUE TITLE
Freeform query string parameters

### ISSUE THREAD

**Issue by MassTroy** [swagger-api/swagger-ui#1185]
Some API are designed to allow for some known parameters as well as any freeform parameters to be applied. I'd like to add an annotation `@ApiOperation(... , freeformParams = true)`

On swagger-ui, this would add boxes where you could type the query string key and value. This is in addition to any existing parameters defined by `@ApiParam`

Key | Value
----- | --------
foo | bar
baz | bang

This would generate a request such as `GET /myEndpoint?knownParam=value&foo=bar&baz=bang`

**Comment by webron** [comment]
The problem is not with swagger-core nor swagger-ui. There's simply no way to describe this use case with the current version of the Swagger specification.

If you'd like to see support for it in a future version of the spec, please submit a proposal in the form of an issue on the [swagger-spec repository](https://github.com/swagger-api/swagger-spec). To help us better evaluate it, please provide a concrete use case, existing frameworks that provide support for it, well-known public APIs that use this form and anything that can help in making your case.

**Comment by MassTroy** [comment]
Created this issue on the swagger-spec project https://github.com/swagger-api/swagger-spec/issues/349
