### ISSUE TITLE
XSS in url parameter

### ISSUE THREAD

**Issue by mehmetaydogdu** [swagger-api/swagger-ui#1262]
Here is the XSS. http://petstore.swagger.io/?url=%3Cscript%3Ealert(atob(%22SGVyZSBpcyB0aGUgWFNT%22))%3C/script%3E

The problem is in /swagger-api/swagger-ui/master/dist/swagger-ui.js 
at line  
$('#input_baseUrl').val(url);

**Comment by ponelat** [comment]
@mehmetaydogdu thanks for pointing this out, **XSS** prevention is a necessary hassle and isn't always apparent. 

You were close, but the issue was in `showMessage` and `onFailure`, where we were putting the failed URL in `#message-bar`, using `$.html`. We've now changed to `$.text` which escapes HTML entities. This comes at the cost of not being able to show fancy messages (those with markup), but there were no cases that I could find, so nothing lost :D

**Comment by mehmetaydogdu** [comment]
Is it possible to create a tag for the fix? The latest tag is 2.1.8M1 and it contains the issue. I am using webjars.org to download the swagger and I guess it uses the tags to package.

**Comment by webron** [comment]
A tag with this fix has been created a long time ago...

**Comment by mehmetaydogdu** [comment]
Which one is the tag?

**Comment by webron** [comment]
This was fixed in 2.1.0, so any tag from 2.1.0 onward would work (including the current master).

**Comment by mehmetaydogdu** [comment]
The problem is with the webjars. Webjars version [2.1.2](http://cdn.jsdelivr.net/webjars/org.webjars/swagger-ui/2.1.2/index.html?url=%3Cscript%3Ealert(atob(%22SGVyZSBpcyB0aGUgWFNT%22))%3C/script%3E) do not include the fix. I opened an [issue](https://github.com/webjars/swagger-ui/issues/15) to the [webjars](https://github.com/webjars/swagger-ui).

**Comment by mehmetaydogdu** [comment]
I am not able to see the fix on these tags and even on the master. The fix is lost. Please reopen the issue.

**Comment by Steiner-254** [comment]
Interesting <3
