### ISSUE TITLE
Cookies available in the response header.

### ISSUE THREAD

**Issue by violivei** [swagger-api/swagger-ui#1309]
Is there any way Swagger-ui can show the browser cookies in the response header?

**Comment by ponelat** [comment]
Cookies have proven to be quite scary, in terms of how the browser treats them.
We can only access cookies the browser allows us too. Which is ok, but can be misleading when it comes to CORs (our old friend). Most of the time, we _can't_ view cookies from the server, because it's on another domain. I'm still trying to get CookieAuthorization working with CORs. If that happens, we can revisit over here :)

I'll link to the Cookies issue: https://github.com/swagger-api/swagger-js/issues/483
