### ISSUE TITLE
Easier testing (ie: adding specs)

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#1334]
As per @fehguy request.

Make the whole testing of swagger-ui a little easier to approach, and allow the addition of specs to be pain-free.

What we can do is setup a [connect](https://github.com/senchalabs/connect)( or even the more powerful [express](http://expressjs.com/)) server to dish out the specs. With some middleware(connect lingo for 'plugin')  for 4XXs, false mime-types etc.

**Comment by fehguy** [comment]
It's not too late!  Here's an overview of how I'd like to see this effort tackled.

In general, this is a difficult project to test. There are an infinite number of combinations possible when defining a specification.  The rendering and behavior of the UI thus needs to have a very flexible mechanism for creating tests and verifying that the behavior is correct.

It is impossible for us to build an "uber spec" which characterizes all the possible behaviors of the UI.  Thus, we should expect that there will be a large number of specifications which need to be written in order to exhibit bugs or fixes in the user interface.  Making things more complicated, there are _dynamic rendering_ and _execution_ behaviors as well, which means we have to hook in to the guts of the swagger-ui quite deeply in order to properly test.

From a contributor's point of view, I'd like to see that end-users have the following structure available when they submit an enhancement or fix:

* A mechanism to provide a specification for a test.
* A mechanism to load swagger-ui to render, based on the supplied specification
* A framework for verifying the existence of buttons, links, rendered sections of text in a code-driven fashion
* A technique to intercept requests, as executed through swagger-ui, to mock responses from a server.
* A framework to verify rendered output in swagger-ui based on request execution

With the above, we should establish that single test files should be created here:

```
test/integration/*.js
```

In the `integration` folder, a single file should have the following:

* A definition, in a JSON object
* A convenience method to start swagger-ui (headless or not), where swagger-ui will use the definition in it
* Tests should be called after swagger-ui has been initialized and is rendered

**Comment by shockey** [comment]
I believe we have everything covered that was outlined here.

Closing!
