### ISSUE TITLE
To be able to run it on IE i need to specify a meta tag

### ISSUE THREAD

**Issue by mortias** [swagger-api/swagger-ui#1355]
Maybe an improvement related to the swagger-ui,
to be able to run in in IE i had to add this tag: in the index.html
  &lt;meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge"&gt;

maybe a small improvement?

**Comment by patricekrakow** [comment]
Not a small improvement, a BIG one!!!

I was not able to have my Swagger + Mongoose + IE10 working properly, I was getting the error:
<pre>Line: 32 / Error: 'SwaggerUi' is undefined</pre> from IE10
Then, I just add your
<pre>&lt;meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge"&gt;</pre>
and it starts working properly!!!
THANK YOU.

**Comment by patricekrakow** [comment]
Here is some additional information:
1/ Swagger + Mongoose + IE10 was not working without the magic meta tag from mortias, but the following combination are working without it:
- Swagger + Mongoose + Firefox (38.0.5)
- http://petstore.swagger.io/ + IE10 (10.0.9200.17357) !!!

2/ Here are the logs from the IE10 > developers tools > Console
<pre>
[INFO] HTML1202: http://10.120.193.237:8080/swagger-ui-master/dist/ is running in Compatibility View because 'Display intranet sites in Compatibility View' is checked. 
       dist
[ERROR] SCRIPT1010: Expected identifier 
        swagger-ui.js, line 254 character 55

        Line 254|    var defaultValue = isArray && Array.isArray(param.default) ? param.default.join('\n') : param.default;

[ERROR] SCRIPT5009: 'SwaggerUi' is undefined 
        dist, line 33 character 7

        Line  33|      window.swaggerUi = new SwaggerUi({

[ERROR] CSS3111: @font-face encountered unknown error. 
        droid-sans-v6-latin-700.eot
</pre>

I guess that the next step would be to compare the Swagger-version-I-have-Installed with the Swagger-version-used-by-petstore.swagger.io in order to see what has broken the IE10 compatibility, which is magically restore by the meta tag from mortias!

**Comment by ponelat** [comment]
Could be the keyword 'default' that is causing this mischief. At least that is the 55 char.
I'm not sure why/how IE10 treats this differently... but something needs to be done. For the moment the above solution of forcing IE10 to include support for 'EDGE' (which is the latest stable version of IE) - works well.

**Comment by mortias** [comment]
solved another issue :) when the devil is in the details,.. 
however i wouldn't dive too much in details.. basically the tag is a no-brainer :)
http://stackoverflow.com/questions/6771258/whats-the-difference-if-meta-http-equiv-x-ua-compatible-content-ie-edge-e

**Comment by christopheblin** [comment]
This bug is added in milestone 2.1.1 but you alredy packaged 2.1.5-M2.

Does it mean the bug will not be fixed ?

BTW, the bug only showsw when URL is not localhost (so if you use the IP or a DNS alias, the bug appears)

**Comment by webron** [comment]
The version convention may be a bit confusing. Anything with the -M# extension was a milestone release which was finalized on 2.1.0. (imagine it was 2.1-M2.5 instead).

2.1.1 is the next release.

**Comment by christopheblin** [comment]
ok, thanks ! I am eagerly waiting for the fix of this issue since we have a majority of IE users...

do you accept PR ?

**Comment by webron** [comment]
As many as we can :)

If you work on it, make sure to work off the develop_2.0 branch and submit the PR against it (that is, not master).

**Comment by fehguy** [comment]
We're not going to continue supporting IE9 or lower, so I'm closing this out.

**Comment by ponelat** [comment]
@fehguy as I understand, this is for IE10

**Comment by fehguy** [comment]
@ponelat did I have it backwards?  So we should add this tag?  If so, please reopen and I'll do it.

**Comment by ponelat** [comment]
yeah this bug, seems to only affect **ie10**, and then (not sure why) only in certain circumstances. 
I'll see if the tag has any sideaffects, but otherwise put it in, please. (when you have time)

**Comment by webron** [comment]
With 3.0, this is no longer an issue.
