### ISSUE TITLE
Uncaught TypeError: undefined is not a function  in SwaggerUi.js line:59

### ISSUE THREAD

**Issue by niteshkumardash** [swagger-api/swagger-ui#1370]
Hi,Every one.

While loading the v2/petstore.json file through swagger-ui  src/main/html/index.html. I am getting  Uncaught TypeError: undefined is not a function. in line:59 i.e

 59: this.headerView = new SwaggerUi.Views.HeaderView({el: $('#header')});

Uncaught TypeError: undefined is not a function SwaggerUi.js:59 window.SwaggerUi.Backbone.Router.extend.initialize

Please help.

**Comment by ponelat** [comment]
Are you on the latest version of Swagger-UI ? Also, is there anything you may have changed?

**Comment by niteshkumardash** [comment]
Yes,Mr.ponelat I am using latest swagger-ui but i didn't modify anything. i just run the "src/main/html/index.html" but ui is not rendering properly. while i run "dist/index.html" :-it works fine.

 i want to modify the "src/main/html/index.html" page UI look." for the better usage of api or if the api length increases the ui will also expand. 

So i want that the api test body part should come in another <div> or in another webpage.

so i need to modify some source html code in src folder.. if you have any idea or suggestion please give me..my email :-niteshkumardash@gmail.com

**Comment by ponelat** [comment]
I responded in Google Groups...
This issue here is about loading src/main/html/index.html directly. It won't work as you need the built files, so serve up `./dist` instead.

Once you modify the `src`, you'll need to build afterwards... but calling `npm run build`. 
This assumes you have [node.js](https://nodejs.org/) installed and have installed the necessary dependencies for swagger-ui by calling `npm install` in the root of swagger-ui

**Comment by fehguy** [comment]
Closing as this was a build issue.
