### ISSUE TITLE
Unable to send a cookie over the wire when on a different server by CORS

### ISSUE THREAD

**Issue by mortias** [swagger-api/swagger-ui#1372]
When my swagger-ui is running on server A and it wants to send a request to server B with cors enabled my cookie is not taken into count

refr. @ponelat

**Comment by ponelat** [comment]
@mohsen1 have you any experience with CORS + cookies? We've added the `Access-Control-Allow-Credentials: true` for the server.... added `xhrFields: {withCredentials: true}` for the jquery request.. nadda!

**Comment by mohsen1** [comment]
When you inspect the request, does it have the cookies?

**Comment by mortias** [comment]
I didn't think so, first it does the preflight, then the request without the cookie i've added..

**Comment by mohsen1** [comment]
Try adding the cookie manually using `document.cookie`

**Comment by mortias** [comment]
we did, we added it manually so it was even visible in the browser but without success

**Comment by mortias** [comment]
if you want we can take this to the irc channel

**Comment by mortias** [comment]
we basically added the cookie like document.cookie; then in cors allowed Access-Control-Allow-Credentials: true , set the allowed origin to the correct server, because cors complained that you need to specify a server if you authorize, set the xhrFields: {withCredentials: true} and added a authorization with the cookie

**Comment by mortias** [comment]
https://en.wikipedia.org/wiki/Cross-site_request_forgery
An attacker may forge a request to log the victim into a target website using the attacker's credentials; this is known as login CSRF. Login CSRF makes various novel attacks possible; for instance, an attacker can later log into the site with his legitimate credentials and view private information like activity history that has been saved in the account. This attack has been demonstrated against Google[7] and Yahoo.[8]

**Comment by mortias** [comment]
so basically it's a bad idea :)

**Comment by ponelat** [comment]
This is about explicitly setting cookies for cross-domains.
It is definitely possible to bounce back cookies that those domains send you (and you have it configured so) so that you can have sessions etc.

However when it comes to explicitly setting these cookies in your client app, then trying to send them to third party servers... this is where we get stuck and what I'm starting to believe is impossible. 
One reason, is that you can only set cookies for _your domain_. Which would mean, we can't send it to the third party.

It looks like the best option, if you still need to send cookies for debugging. Is to use a proxy that you host. So for instance, you need to reach server A. Host a simple server somewhere reachable, and each request gets forwarded/proxied to server A. Here you now have an opportunity to set cookies.
To do so in your client app, you set a header such as `x-fake-cookie: key=value;` then in your proxy you switch _that_ header and set a cookie. The proxy is not limited to CORS in any way, so will simply send the cookie.

It will depend on how easily you can setup a proxy that modifies the request.

**Comment by mortias** [comment]
basically for dev we'll setup a proxy that will add the headers :)

**Comment by fehguy** [comment]
cookies are not part of the spec, so I'm going to close this out.

**Comment by cbornet** [comment]
FYI, with swagger-ui 2.1.4, you can now use ```enableCookies: true``` in window.swaggerUI to set the withCredentials flag
