### ISSUE TITLE
Replace error-ridden RPC PetsSore sample with a sample following REST principles

### ISSUE THREAD

**Issue by madorb** [swagger-api/swagger-ui#1426]
The current Petstore sample does not adhere to any reasonable interpretation of REST standards. 

It has RPC-esque endpoints like: POST /pet/{petId}/uploadImage. Note the verb in the URI. This should be POST /pet/{petId}/image. 

It also mangles its use of HTTP response codes. For instance POST /pet returns HTTP 405 which is "FORBIDDEN" which RFC2616 defines as: "The method specified in the Request-Line is not allowed for the resource identified by the Request-URI. The response MUST include an Allow header containing a list of valid methods for the requested resource." which seems inappropriate.

If Swagger wants to position itself as THE Rest documentation tool (even if it refuses to support Hypermedia) it's important to actually promote good, restful design practices, instead of the objectively poor practices in the existing sample.

**Comment by brownstein** [comment]
I disagree - although Swagger should seek to promote good restful design, it is important for the documentation tools (and UI) to support cases outside of the ideal. Otherwise, people with less-than-perfect extant APIs would be unable to correctly express them and simply switch to alternatives that fit their use cases. I assert that having less-than-perfectly-restful endpoints in the example reassures people managing imperfect APIs that their use cases fit and encourages greater adoption.

**Comment by madorb** [comment]
@brownstein - I couldn't disagree more. Having a sample that promotes best practices doesn't in any way indicate that the tool can't support less-than-ideal practices. It just ends up PROMOTING those practices. IMO The sample should be model ideal behaviour, and other documentation can go into how to handle less-than-ideal situations. I can tell you, I avoided swagger for a long time, because the documentation gives off an air of "we don't really care about Restful Principles or intentional Design". Let's encourage people to be better,  to understand WHY things should be done in a certain way, and not just settle for lowest common denominator.

**Comment by webron** [comment]
@madorb - thanks for the input, however, the pet store sample is there to exhibit some of the aspects of Swagger and is not intended to represent a 'proper' API design. Overall the sample itself is relatively inclusive feature-wise and covers the basics.

While I agree it's important to promote good, restful design practices, it is not really Swagger's job to do so. We don't really restrict support for 'right' design and it's not really our place. It's true that in some cases we explicitly don't support some design choices, but it's not necessarily because we think it is the wrong design choice.

If you'd still like to see the pet store sample changed, feel free to open a new ticket on [swagger-samples](https://github.com/swagger-api/swagger-samples) where we hold the pet store project, and provide us with a substitute `swagger.json`/`swagger.yaml` file we can use to base the sample on. Keep in mind it needs to support at least the basic aspects of the current sample, including (but not limited to) security, file uploads and constraints.
