### ISSUE TITLE
Javascript error: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by Cpruce** [swagger-api/swagger-ui#1437]
Hey Ron,

I think the problem is a bug in the swagger-ui. As before, the apis I want show up in the api-docs xml page but a couple are not in the swagger ui page. Additionally, there is the javascript error that comes from model.js AND I've seen it from swagger-ui.js. Here are my screenshots but it seems like a problem in the js since the xml is already produced.

![js](https://cloud.githubusercontent.com/assets/2712171/8444365/a42e7220-1f44-11e5-9931-d95f32bd81fc.png)

![xml](https://cloud.githubusercontent.com/assets/2712171/8444368/a8222ad4-1f44-11e5-8ab9-e73a7d7ccb73.png)

**Comment by webron** [comment]
Which library do you use to produce your Swagger documentation?

**Comment by Cpruce** [comment]
swagger-ui for the presentation, swagger-annotations and swagger-springmvc for annotations. I believe it is swagger ui because the xml is produced fine but the js is what hits the error. Thanks for your response

**Comment by webron** [comment]
That's just it, the Swagger specification is not in XML, so that's a swagger-springmvc problem. Granted, it is most likely also producing a JSON when the request is sent with `application/json` as the content type. It would be difficult to debug it further without the actual JSON though.

Also, by the looks of it, you're using an *ancient* version of swagger-springmvc as it produces Swagger 1.0 definitions. Technically, swagger-ui still supports it to an extent, but you're bound to hit issues in more complex APIs (and you have!).

Any chance you can upgrade to [springfox](https://github.com/springfox/springfox)? That's the renamed swagger-springmvc project that's highly maintained and produces the latest Swagger definition version. It may require some work migrating, but will save you a lot of time eventually with these kinds of issues (plus you get the benefit of using the latest version and the whole tool-set with no issues).

**Comment by Cpruce** [comment]
Sure thing, I haven't gotten springfox and the swagger ui to work yet but I'll keep at it. Should I only be dealing with json and not xml?

**Comment by webron** [comment]
JSON or YAML, yes.

**Comment by webron** [comment]
Closing for now.
