### ISSUE TITLE
JSON cannot be loaded despite having CORS headers

### ISSUE THREAD

**Issue by scwood** [swagger-api/swagger-ui#1467]
Followed the directions and added CORS support to the Apache server, still receiving the "Can't read from server" error. 

Unless I'm misunderstanding, swagger-ui and our JSON are hosted on the same webserver, so this shouldn't matter in the first place. 

![screen shot 2015-07-13 at 11 56 35 am](https://cloud.githubusercontent.com/assets/9126138/8656674/400a90fa-2956-11e5-8474-de4fdded02a8.png)

![screen shot 2015-07-13 at 11 58 21 am](https://cloud.githubusercontent.com/assets/9126138/8656702/7a9c85de-2956-11e5-9209-b972bc0652af.png)

**Comment by webron** [comment]
Which version of the UI is that?

On Mon, Jul 13, 2015 at 8:57 PM, Spencer Wood <notifications@github.com>
wrote:

> Followed the directions and added CORS support to the Apache server, still
> receiving this error:
>
> [image: screen shot 2015-07-13 at 11 56 35 am]
> <https://cloud.githubusercontent.com/assets/9126138/8656674/400a90fa-2956-11e5-8474-de4fdded02a8.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-ui/issues/1467>.
>



-- 
-----------------------------------------
http://swagger.io
https://twitter.com/SwaggerApi
-----------------------------------------

**Comment by scwood** [comment]
I cloned the swagger-ui repo on Friday.

**Comment by webron** [comment]
This looks familiar, but can't put my finger on it. I know your screenshot share the relevant information, but just to try and troubleshoot, can you run `curl -I http://path/to/swagger.json` (not from the vm, from your machine) and paste the output here?

**Comment by scwood** [comment]
```bash
$ curl -I http://vm0.net:9000/underarmour/swagger.json
HTTP/1.1 200 OK
Date: Mon, 13 Jul 2015 19:32:55 GMT
Server: Apache/2.2.15 (CentOS)
Last-Modified: Mon, 13 Jul 2015 18:36:16 GMT
ETag: "563eb-21f-51ac5ff338800"
Accept-Ranges: bytes
Content-Length: 543
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, DELETE, PUT, PATCH, OPTIONS
Access-Control-Allow-Headers: Content-Type, api_key, Authorization
Connection: close
Content-Type: application/json
```

**Comment by webron** [comment]
@scwood - I'm afraid there's a chance the error is misleading. If the Swagger definition you have is the one shown in the screenshot above, then the reason you're getting this error is because the definition itself is invalid. Off hand I can tell you the operation described there is missing a response which is required.

**Comment by scwood** [comment]
A little new to this sorry, how could I fix the missing response?

**Comment by webron** [comment]
Take a look at the pet store - http://petstore.swagger.io/v2/swagger.json - look at any of the operations and see the `responses` section. Under it, you need to have a least one response, and a response has to include at least `description`. It's best to document at least the successful response of an operation. In your case, since it's a `get` operation, it's most likely returning a specific model, but for now, you can even say it returns nothing just to test the loading of the json.

**Comment by vsix27** [comment]
i think the error **"Can't read from server. It may not have the appropriate access-control-origin settings."** from swagger ui is misleading.
i took swagger json from petstore mentioned above and replaced in the file double quote by single
local file with double quotes opens fine in local swagger ui and online swagger editor.
local file with single quotes instead of doulbe has error **Can't read from server...** but opens fine in online swagger editor http://editor.swagger.io/

**Comment by fehguy** [comment]
OK so there are restrictions as to what information you have under a CORS scenario.  The message may be misleading but it's pretty difficult to get to the root of it inside a browser.  We could use a proxy but that'd not be nice...

@vsix27 regarding replacing your comment about single quotes--JSON _requires_ double quotes.  If something accepts single quotes as JSON, it's going outside the boundaries of what JSON is supposed to do.  We can't control that, but we certainly don't need to embrace it by supporting it.
