### ISSUE TITLE
Problem with URLs in markdown

### ISSUE THREAD

**Issue by jnehring** [swagger-api/swagger-ui#1491]
In my swagger.yaml I have code examples in markdown. They are surrounded with three backticks. Originally the code example are in the turtle format, a simplified version of a code example looks like this:

```
<http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>
```

In my swagger UI it is rendered like this:
![unbenannt](https://cloud.githubusercontent.com/assets/10537540/8873298/76544b94-3205-11e5-84b8-3c15e9416579.png)
I want the code example to be rendered as plain text, so the slashes stay slashes. Can you give me a hint on what went wrong / how to do this?

It seems that the code example is interpreted as XML. When I add the code language to the backticks (e.g. ```plain) as supposed in [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/) then it still does not work.

**Comment by webron** [comment]
What happens when you use two backticks? Not saying it shouldn't work with three, just wondering.

**Comment by jnehring** [comment]
When I use two backticks then it is rendered as two backticks and unformated text in between. So the backticks are interpreted as plaintext.

**Comment by jnehring** [comment]
I finally used this construct which worked:
```
<pre>
&lt;http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#&gt;
</pre>
```
It creates a code block in swagger and displays the URL correctly.

**Comment by webron** [comment]
Thanks for the update, but I'd like to keep the issue open. We still need to resolve the original problem.

**Comment by sheehan** [comment]
I ran into the same issue. The problem is that the pre-markdown-processed code is inserted into the dom first [here](https://github.com/swagger-api/swagger-ui/blob/488611a4ff9a6fbfbc777ba310a582c9298315f1/src/main/template/param.handlebars#L30) and then later processed [here](https://github.com/swagger-api/swagger-ui/blob/996433d8bc3c4c2591834b434cceeec4a9c8fd54/src/main/javascript/SwaggerUi.js#L205).

Inserting something like `<http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>` into the dom causes it to be parsed weird as show below.

```js
var $el = $('<div>');
$el.html('<http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#>');
console.log($el.html()); 
// <http: persistence.uni-leipzig.org="" nlp2rdf="" ontologies="" nif-core#=""></http:>
$el.html(marked($el.html()));
console.log($el.html()); 
// <p><http: persistence.uni-leipzig.org="" nlp2rdf="" ontologies="" nif-core#=""></http:></p>

**Comment by webron** [comment]
This should not be an issue anymore.
