### ISSUE TITLE
Support responses with image content types

### ISSUE THREAD

**Issue by bgagnon** [swagger-api/swagger-ui#152]
If the web service returns a standard image content type (image/png, image/jpeg, etc.), display it inline instead of the raw  bytes.

**Comment by mohsen1** [comment]
This issue has ben fixed. 

Couple of notes regarding this:

* If you're serving images from a different origin, setup your server to set `content-type` header in CORS calls. Otherwise XHR calls in the UI will not know if the response is an image
* Same for downloading. You should set proper headers.

Here is an example of cross origin (different ports) image
![screen shot 2015-03-26 at 11 33 32 am](https://cloud.githubusercontent.com/assets/543633/6854051/037f29f2-d3ac-11e4-9249-8019007d1fef.png)
