### ISSUE TITLE
Very large sourceMappingUrl in 2.1.1 swagger-ui.js causing slow load times

### ISSUE THREAD

**Issue by daward** [swagger-api/swagger-ui#1534]
There's a huge sourceMappingUrl which appears to contain browserified binary javascript (base64 encoded) in the latest swagger-ui.js file.  This causes the file to be 2MB (in your source tree) where before it was a few K.  Even the minified file is far bigger than the 2.1.0 version.  

It looks to me like it happened at this commit: https://github.com/swagger-api/swagger-ui/commit/5a73c3d5b76437c4e65e4a4ad4f1b8dad54684e7#diff-7b22c617cbad75cdd8123d16345c8e80.  Is this performing an essential feature that is worth the massively increased file size?

**Comment by skjegg** [comment]
Seriously, swagger-ui.js is 2398.101 kB ? From: https://github.com/swagger-api/swagger-ui/blob/master/dist/swagger-ui.js 

That is insane..

**Comment by fehguy** [comment]
Use the minified version, that's why it's there.

**Comment by daward** [comment]
Even the minified version is awfully large, and tripled in size with that commit.

**Comment by fehguy** [comment]
if source mapping is in the minified file, that's a bug.  otherwise, we have wrapped the dependencies into the library so that this is all that's required for execution.  It solves a bunch of problems to do this, but indeed it does make it slightly larger.

But if you're seeing the source map in there, it needs to get fixed.  Please confirm

**Comment by webron** [comment]
This should no longer be an issue.
