### ISSUE TITLE
string format type 'text' (or maybe even html) wanted

### ISSUE THREAD

**Issue by dothebart** [swagger-api/swagger-ui#1578]
when specifying https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#itemsObject _type_ _string_ swagger UI renders an input line in the 'try this' window. 
a _format_ is currently not neccessary for _type_ _string_. 
To get a textarea in the browser a _format_ 'text' would be nice, maybe even _html_ which could include i.e. tinyMCE

**Comment by webron** [comment]
Not sure what you mean here, @dothebart.

**Comment by dothebart** [comment]
In text you may transport several sub-mimetypes, as is text/html text/markdown etc. 
An aid to the user to create these would be nice.

**Comment by webron** [comment]
Yes, but 2.0 doesn't quite support that. 3.0 will have better ways of describing it.

**Comment by webron** [comment]
This is somewhat out of scope for us - however, we'll accept a PR that handles an extension for it. This would be perfect to go into the plugin repository we don't yet have ;)

**Comment by dothebart** [comment]
but qualifying a mimetype would rather have to be part of the json definition?

**Comment by webron** [comment]
@dothebart sorry, not sure what you mean - can you explain?

**Comment by rboughani** [comment]
the textarea will be added in which version please ?
i'm using org.springdoc **springdoc-openapi-ui 1.4.3**

**Comment by elvisbegovic** [comment]
there are lot issues regarding this, we want formData type textarea, or merging in:body and in:formData together to formData on request call, actually it is not possible to do this. can you give some inputs please ?

note:due to this we can't juste communicate our swagger-ui URL to partners, in addition we need to explain that "acutally our doc doesn't send the in:body in  formData but you can do it in postman you will see it works" 

cc/ @webron
