### ISSUE TITLE
$ref to external response schema not resolving

### ISSUE THREAD

**Issue by DavidBiesack** [swagger-api/swagger-ui#1592]
I have a Swagger 2.0 document which refers to external schema. Swagger UI is not fully resolving these external schema, even though they exist. There is no authentication on these resources.

It appears Swagger does not recognize "$ref"  : "http://..." external schema.
This is important to us, as we want to share schema across APIs, and reuse them from a central schema server.

I have swagger-ui runnning on port 80 in a Linux web server swagger.na.sas.com/swagger-ui (on our intranet). The server also has two contexts defined for /schema and for /apis:

When I view the swagger in Swagger UI, 

http://swagger.na.sas.com/swagger-ui/?url=http://swagger.na.sas.com/apis/swagger.bugs/v1/swagger.json

the response schema are not resolved at all or not fully, even though I can view them all in the browser or via curl.

Example 1: operation "get" on "/c"  using

```
                "400" : {
                    "description": "Success",
                     "schema" : { "$ref" : "http://swagger.na.sas.com/schema/swagger.bugs/error/v1/schema.json" }
                }
```

does not even show a model schema for 400 even though that schema resource exists. Using "/schema/swagger.bugs/error/v1/schema.json" has the same effect.

Example 2: operation "get" on "/a" has

```
                "400" : {
                    "description": "Success",
                    "schema" : { "$ref" : "#/definitions/error" }
                }
```

but Swagger UI shows empty model schema. definitions/error looks like

```
    "error" : {
        "schema" : { "$ref" : "http://swagger.na.sas.com/schema/swagger.bugs/error/v1/schema.json" }
    },
```

Example 3: operation "get" on "/b"  with

```
                "400" : {
                    "description": "Success",
                    "schema" : { "$ref" : "#/definitions/errorResponse" }
                }
```

displays a model schema. "#/definitions/errorResponse" is embedded in the Swagger doc. However, that schema references an external property schema

```
            "links": {
                "type": "array",
                "description" : "An array of links to related resources and actions.",
                "items": { "$ref": "http://swagger.na.sas.com/schema/swagger.bugs/link/v1/schema.json" }
            },
```

which is not resolved; instead Swagger UI displays only "links" : [ null ]

A similar situation occurs when using an external $ref schema for a request body (parameter with "in" : "body" ) -- nested properties defined by external schema do not resolve and are presented as null

https://drive.google.com/open?id=0B6GUPYh362KvUmRnYUxkNlVuZXM contains
the sample swagger and schema files

apis/swagger.bugs/v1/swagger.json
schema/swagger.bugs/a/v1/schema.json
schema/swagger.bugs/error/v1/schema.json
schema/swagger.bugs/link/v1/schema.json

**Comment by Bwen** [comment]
Same bug here... When you reference an external file the Web UI does not display the model, it actually display the url for the model.

This feature is really important to me because the .json is growing at an exponential rate and starting to be hard to maintain by hand (since its legacy code I have no choice).

**Comment by webron** [comment]
Can you please try again with the latest release (2.1.3)?

**Comment by DavidBiesack** [comment]
I see the same behavior (external schema not resolved) 

For example, if I switch from viewing the (empty) 'Model Schema' to 'Model' for the "Response Class (Status 200)" on GET /a, the UI reports

http://swagger.na.sas.com/schema/swagger.bugs/a/v1/schema.json is not defined!

but that resource does exist

I did a `git pull` of master and 'git log' shows
 8bc2595 2015-09-19 | updated build (HEAD, tag: v2.1.3, origin/master, origin/HEAD, master) [Tony Tam]

and I see  * @version v2.1.3 in dist/swagger-ui.js

**Comment by webron** [comment]
Okay, thanks for verifying.

**Comment by Bwen** [comment]
any ETA on this fix?

**Comment by fehguy** [comment]
i hope to have a swagger-js & swagger-ui release this week.

**Comment by Bwen** [comment]
any ETA on this fix?

I'm sorry to insist, but without this fix Swagger-ui is not as useful since no structure shows up (everything is in external files for me).

**Comment by mrwanny** [comment]
any ETA on this fix?

**Comment by fehguy** [comment]
Well to be honest, this bug should have been closed with 2.1.4.  @mrwanny are you seeing an issue?  @Bwen still have a problem?  Response schemas are definitely supported and tested.  I don't know of any issues with them.

**Comment by Bwen** [comment]
@fehguy Not only does the master does not fix the problem but now it downloads around 20 times every external schema on first page load...

You only see contacts.json being loaded 10 times in the screenshot, but its actually a lot more than that... Look at the scrool bar.

![swagger-ui-1](https://cloud.githubusercontent.com/assets/748824/12579624/559c1588-c3f7-11e5-85bf-0221101e23a9.png)

**Comment by fehguy** [comment]
It may do this when there is a missing reference.  Can you please share the swagger spec?

**Comment by Bwen** [comment]
Our swagger ui is public although its not really being referenced. It has been made by hand because of the legacy we must deal with.

https://api.funio.com/swagger/
https://api.funio.com/1.2/swagger.json

**Comment by webron** [comment]
@Bwen - briefly going over a few of your spec files (since they are split), it looks like there are several issues with the spec itself. It may be easier to cover those in a quick online chat. Any chance you can hop on IRC? We're on irc.freenode.com at #swagger. You can also use the client in our website - http://swagger.io/irc.

**Comment by Bwen** [comment]
To save time I simplified the bug to a simpler example. One that you might recognize, the pet store example. I did 2 things to it.

http://newbiverse.com/swagger
http://newbiverse.com/swagger/swagger.json

**Firstly** I put the everything that was in paths["/pets"] into http://newbiverse.com/swagger/pets.json
Notice how the definition stayed in the swagger.json and its not only not giving my a proper data type but its loading it **SUCCESSFULLY** multiple times.
![swagger-ui-1](https://cloud.githubusercontent.com/assets/748824/12643979/a7692954-c58d-11e5-9472-4e9ed77644db.png)

**Secondly** I put the definitions.Order into http://newbiverse.com/swagger/definitions/order.json 
This time I only moved the definition. Notice how I still dont get a data type or a Model definition for the POST /stores/order ?
![swagger-ui-2](https://cloud.githubusercontent.com/assets/748824/12644047/21275090-c58e-11e5-9d84-71d304a8b633.png)

I dont want to be rude or anything but this took me under 15 minutes to setup. How was this tested again? 

If I'm doing something wrong please point it out to me because I cant see it.

Thank you.

**Comment by brandonson** [comment]
I've been seeing this as well - it really looks like references as the schema for parameters simply does not work.

As a reference, this does not work:
```
  parameters:
    - $ref: ../story_id.yml
    - $ref: part_id.yml
    - name: data
      description: The data to replace the existing story part with.
      schema:
        $ref: types/PartData.yml
```

Interestingly, $ref schemas for responses do seem to work.  i.e. something like this, from the same file:
```
  responses:
    200:
      description: Response containing the story data, including summary and other content.
      schema:
        $ref: types/PartData.yml
```

That said, I think the original issue here only dealt with response schemas - the issue being described (and the one I'm seeing) now appears to be with parameter schemas.

**Comment by webron** [comment]
And that's why I asked you to join IRC because it's much easier to cover in an interactive talk and not in comments. 

In short: That's not how JSON References work.

A bit more detailed: When you reference `#/..../` the `#` means 'this file' (sort of). JSON References are parsed based on the file they exist it. It looks like you assume that the way JSON References is by pulling everything into the top-level file and then dereferencing - that's not the case. 

And for further details, please refer to https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/REUSE.md.

**Comment by Grievoushead** [comment]
Any updates on this?
Not working for me, I have tried using ref as described here:
https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/REUSE.md#url

```
"$ref": "https://my.company.com/definitions/models.json#/models/Tag"
```

but still having an error:
![image](https://cloud.githubusercontent.com/assets/1427311/13432533/ba0672d4-dfd6-11e5-9933-b8049ca3f3d2.png)

**Comment by Bwen** [comment]
I've never really managed fixed it, moved on.

Made an example from the petstore example: http://newbiverse.com/swagger/

http://newbiverse.com/swagger/#!/pet/addPet
http://newbiverse.com/swagger/#!/user/createUser


Good luck :)

**Comment by fehguy** [comment]
Hi, a couple things.

First off, the reference _do_ work.  There are many places that they can go wrong, though, depending on server configuration, CORS, protocol, etc.

Next there have been substantial improvements in swagger-js for the repeated calls, etc.  I will reference this ticket on that merge.

**Comment by Grievoushead** [comment]
Ok, Is there is a way to make a ```$ref``` to parent without specifying full URL?

E.g.: I have definitions inside main swagger config: ```http://example.com/api.json``` and I have split all paths into separate files, like:```/countries/": {
            "$ref": "countries.json"
        }```, then how to inside countries.json responses specify ```$ref``` to api.json definitions section?
When I put ```"$ref": "#/definitions/Address"``` it's not working b/c definitions not in this file, even if I put  ```"$ref": "http://example.com/api.json#/definitions/Address"``` its not working, only thing that works for me is put the definitions in separate file and then make ref to it in api.json and countries.json.

But actually what I need is to have relative path instead of specifying full url. Something like ```"$ref": "../api.json#/definitions/Address"``` but this also not working. Can anybody help?

**Comment by fehguy** [comment]
@Grievoushead relative references work fine.  Please pull master, it has been updated with swagger-client-2.1.13.  If you are having issues with relative references, please take a look at the [tests](https://github.com/swagger-api/swagger-js/blob/master/test/resolver.js) and post your spec issues.

**Comment by fehguy** [comment]
The relative URI syntax should be fully supported now.  Open a new issue if you keep seeing this.
