### ISSUE TITLE
Default "optional" is displayed on all fields on response classes.

### ISSUE THREAD

**Issue by Zoooook** [swagger-api/swagger-ui#1601]
All fields default to optional and you have to explicitly make them required to override the default. Without an option to change the default, we at least need to be able to not display "optional" on every single field, without explicitly marking every field as required. That's the whole point of defaults, you don't have to explicitly state them.

**Comment by mar612** [comment]
Basically, you'd rather have the required fields labelled as 'required', while having the optional fields not labelled, correct?

**Comment by Zoooook** [comment]
Yes

**Comment by webron** [comment]
I'm confused by what you mean here, are you referring to optional in the model view part?

**Comment by mar612** [comment]
Yea, I think that's what OP is referring to.

**Comment by remesh22** [comment]
Without explicitly making all the fields as required using the annotation @ApiModelProperty(required = true),
is there a way to make all the fields as required by default so that i can expose the optional fields using @ApiModelProperty(required = false).In order to make one filed optional(openConnectSessionId), i am ending up with making all the other fields as required now as below:
public class LoginVO {

	@JsonProperty("open_connect_session_id")
	private String openConnectSessionId;
	@ApiModelProperty(required = true)
	@JsonProperty("ip_address")
	private String ipAddress;
	@ApiModelProperty(required = true)
	private String username;
	@ApiModelProperty(required = true)
	private String password;
}

**Comment by webron** [comment]
That's a question to swagger-core really, but the answer is no.
