### ISSUE TITLE
Multiple operations that share a path and method (but differ in content type) get deduplicated erroneously.

### ISSUE THREAD

**Issue by Lattyware** [swagger-api/swagger-ui#1694]
It appears that multiple operations that share a path are merged into a single operation, even if they are different. Say, [for example](https://gist.github.com/Lattyware/345a0dddf3b198e8fb33), I have two operations, one gives my resource as XML, one as JSON.

![image](https://cloud.githubusercontent.com/assets/1239492/10643201/85ed492a-7819-11e5-8ba7-2341d00b4af5.png)

Only one of the operations appears. This used to work correctly in previous versions, but appears to be broken now (using swagger-ui 2.1.3).

**Comment by webron** [comment]
In the current version of Swagger (and previous ones) a unique operation is a combination of a path and an HTTP verb. The content-type plays no part in it. Prior to 2.0, it was possible to add such definitions due to the structure of the JSON, but that was still invalid and unsupported. In 2.0, you simply cannot do that structure-wise. If you're using an older version, swagger-ui will first transform your spec to 2.0 which will lead to one definition clobbering the other. This is not a bug, this is by design.

**Comment by Lattyware** [comment]
I see, so this is just an extension of [issue #182 in swagger-spec](https://github.com/swagger-api/swagger-spec/issues/182). Ugh, really not a fan of that decision, but fair enough.

**Comment by webron** [comment]
Yup. Sorry about that, but it's been that way since day one of the spec. The only difference is it wasn't possible to enforce it versions prior to 2.0.
