### ISSUE TITLE
Can we include the Build Number in the Swagger Documentation

### ISSUE THREAD

**Issue by Jindam** [swagger-api/swagger-ui#1727]
Hi,
I am using the Swagger documentation for my WebApi project.Is there any way to show the Build number in the SwaggerUI.

**Comment by SimplicityMike** [comment]
That would be nice. We upgraded our UI yesterday and as i was looking at the new UI, i was thinking did i get the latest? Did i do that correctly?

**Comment by webron** [comment]
Build number of what?

**Comment by SimplicityMike** [comment]
i think i was looking for release number 2.1.3. We went a long time without upgrading, we were probably running 2.1.0 and yesterday i wanted some of the performance upgrades. We have a jenkins job to pull and push, so being lazy, we just hit the button, then i was looking at our ui and i kept thinking, did i get 2.1.3 or am i still running 2.1.0. I felt pretty good after we saw significant performance  improvements. 

And by the way, @webron  thanks for all you do. We have learned a great deal from you and the community. Thanks again. 

Mike

**Comment by webron** [comment]
@SimplicityMike - thank you for the kind words, much appreciated.

The version of swagger-ui can be found at the top of the swagger-ui.js file. For example, if you look at the online pet store, you'll see it at the comment right there - http://petstore.swagger.io/swagger-ui.js.

It's not currently displayed in the UI itself, though it's definitely something to consider, at least in a configurable way.

I suspect @Jindam was referring to the build number of his own application though, so want to make sure on that.

@SimplicityMike - one other point - we announce new releases on our [Twitter account](https://twitter.com/SwaggerApi), [Google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket), and as actual [Github releases](https://github.com/swagger-api/swagger-ui/releases). I admit sometimes we miss the announcements, but we do our best. Apparently, there are tools like [Sibbell](https://sibbell.com/) you can use to subscribe to new releases of relevant projects, so that may help as well.

**Comment by Jindam** [comment]
@webron - am referring to release number here. I am interested in showing the release number in the Swagger UI as same way the @SimplicityMike needs it.

**Comment by webron** [comment]
I see, so right now we don't expose it in a way that it can be easily displayed, but we'll take that into account as a feature request. Thanks for bringing it up.

**Comment by webron** [comment]
The version number in the new UI is now accessible via `versions`.
