### ISSUE TITLE
Swagger does not have a Horizontal scroll at the swagger-ui.html

### ISSUE THREAD

**Issue by TiMusBhardwaj** [swagger-api/swagger-ui#1734]
Recently I have been working with swagger when got stuck on this issue.

I have really long method and parameter names. which gets truncated on swagger-ui.
There is no horizontal scroll so that I can view complete param name.

Does anybody faced same kind of issue ?? Is there any way to get horizontal scroll on Swagger-ui.

![swagger-ui](https://cloud.githubusercontent.com/assets/15724105/11026625/cc6c1e36-86d2-11e5-9965-5d8fefdb15a0.jpg)

**Comment by DavidBiesack** [comment]
We see the same thing if a parameter name is longer than about 12 characters. A query parameter named `preserveFormat` results in the Data Type column being clipped; if the name is `preserveFormatting` the *Data Type* field is not even visible.

(Tip to the OP: It helps to define a `description` in your schema definition, so that Swagger-UI does not copy a `reallyLongParameterName` into the *Description* field.)

**Comment by mroskamp** [comment]
I ran into this issue as well. It'd be nice to have the scrollbars added to the UI, but I'm working around the issue by changing the name and description of the parameter, to eliminate the need for the scrollbar.

**Comment by webron** [comment]
This should no longer be an issue with the new UI.
