### ISSUE TITLE
Why are bower_components libraries not used?

### ISSUE THREAD

**Issue by eLarocque** [swagger-api/swagger-ui#1861]
I am looking over how the gulpfile.js tasks bundle the website and I am seeing that most of the build is generated from the /src and /lib directories.

What I don't understand is why a library like jQuery has been added manually in the lib directory instead of using bower?
Since there is a bower.json file in the project I was curious to know why dependencies such as jQuery aren't being retrieved with it.

I am assuming there is a reason for this and, being new to gulp / bower / node, I was hoping someone could shed some light on this.

Thanks.

**Comment by fehguy** [comment]
JQuery is not included because many people bring their own version of jquery, and bundling it up makes the library much larger.

That said, gulp/bower are rapidly evolving, and different techniques make sense day-to-day.  There may be other reasons to change the deployment, but this has been working well for folks.
