### ISSUE TITLE
Property names are not escaped and allow XSS

### ISSUE THREAD

**Issue by joevennix** [swagger-api/swagger-ui#1865]
To reproduce, point swagger-ui at a JSON schema file that uses a model with a property containing `<script>alert(1)</script>`. The script will execute. I've attached a sinatra server that demonstrates the issue by replacing the "photoUrls" property with `"photoUrls<script>alert(1)</script>"`:

https://gist.github.com/joevennix/b2bc8c04fd74f2f5d2b2

**Comment by danderson00** [comment]
Any update on when this might be fixed? Using a `Content-Security-Policy` header containing `connect-src 'self' online.swagger.io` mitigates this, but Internet Explorer is still vulnerable.

**Comment by webron** [comment]
@danderson00 - please consider submitting a PR to fix the issue, but we'll try to look into it as soon as possible as well.

**Comment by bradygaster** [comment]
@fehguy is there an ETA for this issue's resolution?

**Comment by fehguy** [comment]
Any day now

**Comment by fehguy** [comment]
See https://github.com/swagger-api/swagger-ui/commit/a906cffea4550eaa5369e4933a50753213cf09df

**Comment by hoomanb1** [comment]
Is there any CVE for this one?

**Comment by danderson00** [comment]
FYI, this is also still being reported as not fixed on the [nodesecurity.io advisory](https://nodesecurity.io/advisories/swagger-ui_xss-in-key-names) which is used by some dependency scanners like [david-dm](https://david-dm.org/Azure/azure-mobile-apps-node?type=dev). Not sure how to report the version it is fixed in.

**Comment by bradygaster** [comment]
@fehguy what's the status here?

**Comment by webron** [comment]
We've pushed out three close releases - 2.2.1, 2.2.2 and 2.2.3 handling all the known XSS issues we've had whether reported to us (publicly or otherwise) or with our own experience, including this one.

Should you find any new additional XSS issues, please open new tickets on those and we'll address them as soon as possible.

**Comment by fehguy** [comment]
@bradygaster I contacted the node security folks and they've updated their page to show that 2.2.1 has this fixed.

**Comment by danderson00** [comment]
Thanks for your work on this!

**Comment by bradygaster** [comment]
@fehguy thanks so much! got your email. looks like things are good.

**Comment by hoomanb1** [comment]
Just an FYI a [[https://access.redhat.com/security/cve/cve-2016-1000229|ve-2016-1000229]] has been assigned to this issue.
