### ISSUE TITLE
$ref in response example is not correctly processed

### ISSUE THREAD

**Issue by paulprogrammer** [swagger-api/swagger-ui#1882]
I have a responses block that uses `$ref` to include an example:

``` yaml
      responses:
        200:
          description: Success
          schema:
            $ref: 'profile-models.yaml#/ProfileSearchResponse'
          examples:
            application/json:
              $ref: 'ProfileExample.yaml#/ProfileSearchResponseExample'
```

The `$ref` for the schema is correctly processed and rendered in the swagger-ui, but the `$ref` for the example shows the following in the swagger-ui display:

![image](https://cloud.githubusercontent.com/assets/4042273/12402173/6cacd790-bde8-11e5-87de-a4f478a23376.png)

I would expect that the content of the `$ref` would appear as if it were inline.

**Comment by fehguy** [comment]
This use case should be covered already.  Can you verify the versions that you're using?  And assuming you have a file called `profile-models.yaml` at the same location as your swagger.json?

**Comment by webron** [comment]
Actually, I wouldn't expect this to be supported. The [Example Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#exampleObject) has a wildcard value and the results would be displayed as-is. While the spec is not explicit either way, personally that's how I'd interpret it (it is also not included in our reusability guide). Since it potentially makes sense, I'd suggest opening a ticket on the spec so the support for it would be more explicit in the next version.

**Comment by paulprogrammer** [comment]
@fehguy I downloaded from the `master` branch just a few days ago.

@webron That kinda makes sense, but it conflicts with the definition of `$ref` inherited from the json-schema spec which is supposed to behave the same way everywhere.

**Comment by fehguy** [comment]
@webron is right. Examples are taken as literal objects or strings and regardless of rendering they will not be processed for resolution.

**Comment by webron** [comment]
@paulprogrammer - your expectations are understandable, which is why I encourage you to open a ticket on it on the spec itself.

**Comment by paulprogrammer** [comment]
I opened an issue [in the specification #544](https://github.com/OAI/OpenAPI-Specification/issues/544) to address this.

**Comment by webron** [comment]
Already labeled ;)
