### ISSUE TITLE
There is no way to change api-key name

### ISSUE THREAD

**Issue by bssergy** [swagger-api/swagger-ui#1921]
How can I change 'api-key' name? In my API I use 'token' key name

**Comment by webron** [comment]
Take a look at https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L85-L86.

**Comment by bssergy** [comment]
I saw it, but how can I change key name in html, when I am using https://www.npmjs.com/package/swagger-tools for my api?

**Comment by webron** [comment]
I don't get the question. You edit the html.

**Comment by fehguy** [comment]
Depending on how you're using swagger-tools, there may be an index.html being served up automatically.  I'm not sure where that file "lives" but I'm certain that @whitlockjc has made it configurable.  You might ask in the [swagger-tools](https://github.com/apigee-127/swagger-tools) project repo because the default swagger index.html gets you started, but everyone needs to skin it or change the key name.

**Comment by bssergy** [comment]
Thanks guys! I ask this in swagger-tools team

**Comment by whitlockjc** [comment]
I'll respond there.
