### ISSUE TITLE
rendering fails when supportedSubmitMethods does not contains post or put

### ISSUE THREAD

**Issue by nfornaro** [swagger-api/swagger-ui#1949]
problem seems to be in function toggleParameterSnippet, missing a null validation.

I managed to get rendering working by adding the validation:

```js
 toggleParameterSnippet: function () {
    var contentType = this.$('[name=parameterContentType]').val();
    
**    if (!contentType) { return; }**
    
    this.toggleSnippet(contentType);
  }
```
but now textAreas for put parameters are visible.

**Comment by sansjunk** [comment]
+1
I was setting `toggleParameterSnippet` to empty array to disable the "try it out" feature and now rendering has started failing.

**Comment by fehguy** [comment]
@nfornaro @sansjunk can you please share your spec that is causing this?

@bodnia can you please look?

**Comment by sansjunk** [comment]
Spec is hosted here: [link]http://api.gnostice.com/stardocs/v1/api-docs[/link]

**Comment by bodnia** [comment]
@nfornaro @sansjunk if I understand the issue correctly - if there is no `consumes` in spec for some method there shouldn't be 'Try it out!' button and parameters for input visible. Current implementation is following: if there is no consumes types found in spec - by default JSON type is set into drop-down.
Thanks for providing the spec, unfortunately I do not see any issues with rendering.
I wonder if you could provide more details on this so that I can fix it? Thank you in advance!

**Comment by sansjunk** [comment]
@bodnia please see http://api.gnostice.com/stardocs/docui/index.html where the rendering is failing since `supportedSubmitMethods` is set to an empty array (line 50 of index.html). Instead if I set it to something like `['get', 'post', 'put', 'delete', 'patch']` then the rendering is fine.

**Comment by bodnia** [comment]
@sansjunk Thanks for providing the details. PR is created.

**Comment by webron** [comment]
@nfornaro @sansjunk - should be fixed in master now. Can you please pull and validate the fix?

**Comment by sansjunk** [comment]
@bodnia @webron Renders fine now. Thanks!

**Comment by nfornaro** [comment]
@bodnia @webron ok for me too, thanks!
