### ISSUE TITLE
`spec` query parameter does not work

### ISSUE THREAD

**Issue by soenkehahn** [swagger-api/swagger-ui#1960]
As I understand the documentation of the `spec` parameter, I should be able to provide a swagger spec in the url. I tried this url:

http://petstore.swagger.io?spec=%7B%22swagger%22:%222.0%22,%22info%22:%7B%22version%22:%22%22,%22title%22:%22%22%7D,%22paths%22:%7B%22%2F%22:%7B%22get%22:%7B%22responses%22:%7B%22204%22:%7B%22description%22:%22%22%7D%7D,%22produces%22:%5B%22application%2Fjson%22%5D%7D%7D%7D%7D

But `swagger-ui` seems to ignore the `spec` parameter.

Am I doing something wrong? Or is this a bug in `swagger-ui`?

(The spec is this, url-encoded: `{"swagger":"2.0","info":{"version":"","title":""},"paths":{"/":{"get":{"responses":{"204":{"description":""}},"produces":["application/json"]}}}}`)

**Comment by fehguy** [comment]
No, you can't pass it in the URL.  You set it in the options when constructing swagger-ui:

```js
      window.swaggerUi = new SwaggerUi({
        url: url,
        spec: mySpec,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
```

Load the variable `mySpec` in your html page.

**Comment by soenkehahn** [comment]
The README mentions about `spec`:

> This is useful for testing manually-generated specifications without hosting them.

IIUC your solution only works when I host `swagger-ui` myself. Is the documentation outdated? Or am I missing something?

**Comment by soenkehahn** [comment]
Oh, I see. Without hosting the swagger spec. I still have to host `swagger-ui` myself. Nevermind then and thanks.

**Comment by mkrufky** [comment]
I know it's off-topic, but maybe this would help you, @soenkehahn .  If you're trying to avoid hosting both swagger UI and the spec, you can use the Swagger UI Chrome plugin https://chrome.google.com/webstore/detail/swagger-ui-console/ljlmonadebogfjabhkppkoohjkjclfai?hl=en (now updated to Swagger UI v2.1.4) to read a spec served from localhost.   It's *very* easy to use node.js or any other solution to serve a local file out of your local machine, enabling only you access to it.  The chrome plugin can access localhost since it is running on the same machine.   Then again, you could also just use editor.swagger.io to generate a full node.js package that will serve a UI and spec from localhost... your choice.

**Comment by fehguy** [comment]
@soenkehahn yes, you don't "serve it" from a web server necessarily but you do have to have it available in an html file.

@mkrufky thanks for sharing that link, but you do know that you can read the spec file from localhost on a webserver right?  http://petstore.swagger.io?url=http://localhost:8080/my_spec.json

**Comment by mkrufky** [comment]
@fehguy I didn't realize that works.  ha!  I no longer see any value in the chrome plugin!  lol.  Thanks for the info.  :-)

**Comment by soenkehahn** [comment]
@mkrufky, @fehguy: Thanks for the suggestions. That helped.
