### ISSUE TITLE
Query parameters objects (like params[variable]=toto, ....)

### ISSUE THREAD

**Issue by Nox-404** [swagger-api/swagger-ui#2027]
Is there a way to describe object parameters like this :
- filter[name]=a
- filter[ip]=10.
- ...

What i got :
![Before](http://krondor.fr/img/actual.png)

What i need :
![Before](http://krondor.fr/img/new.png)

> The field between the brackets should be able to be a select (enum) or an input field

**Comment by Nox-404** [comment]
And when one is filled, it should add another one beneath it (and with an enum it should remove or not the selected value (configurable))

**Comment by webron** [comment]
You'd have to specify each filter separately. If you're looking for a wildcard definition, that's not supported by the spec.

**Comment by webron** [comment]
I think there's a ticket about it at https://github.com/OAI/OpenAPI-Specification but can't find it right now - feel free to browse, comment or add a new one. I don't really know how that would work in terms of describing it because it looks like different values would require different types - but that should be discussed under the OAI and not here.
