### ISSUE TITLE
Incorrect escaping of double quotes

### ISSUE THREAD

**Issue by tjwise** [swagger-api/swagger-ui#2058]
Using swagger.ui v2.1.4, And I have a service that POSTs one JSON string parameter.  Any double quote marks in that string gets escaped, and sent literally to the service, causing a parsing error.  That is, I enter in Swagger.ui Value field

{"Name":"Tom West", "City": "Boston"}

Both request and response content type are application/json.  However, what gets sent to the service is:

{\"Name\":\"Tom West\", \"City\": \"Boston\"}

The curl command shows similarly:

curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '"{\"Name\":\"Tom West\", \"City\": \"Boston\"}"' 'http://localhost:9000/service-under-test'

Notice that the entire string is enclosed in single and double quotes.  I can copy and strip the backslashes from the string, and the opening/closing double quote, and it will work correctly.

I'm running on Win 10.  The copy/paste of the curl fails with git-bash.

**Comment by cfaurer** [comment]
What's the status on this open issue? Any suggested workarounds?

My need is to support query against a date parameter:

targetResolutionDate query parameter field with value entered = {"$gte": "2016-04-31T17:12:30.617Z"} becomes query = {"targetResolutionDate":"{\"$gte\": \"2016-04-31T17:12:30.617Z\"}"}

When that query string is passed to Mongoose no records are found due to the escape of the double quote.

**Comment by hatrena** [comment]
i have the same problem with escaping the double quotes, any solution?

**Comment by fehguy** [comment]
Sounds to me like you're posting a JSON object as a `string` and expect it to remain as an unescaped JSON property.  That's not valid, and a string is a string.  Please share your spec and perhaps we can guide you more as to how to describe the parameter?

**Comment by hatrena** [comment]
yes i am sending a JSON as a string. the actual JSON i am using is too long so that i can not build a schema for it and it changes every time. so i need to send it as string. 

{"Name":"Saeed"} becomes {\"Name\":\"Saeed\"} . 

Why does swagger take validation responsibility whereas it belongs to the application we are using? like other REST client, chrome or postman, we take care about the validation in our application.

**Comment by fehguy** [comment]
It's a string, and it needs to be escaped.  If you don't want to model the actual payload, you can simply assign it as an object:

```yaml
schema:
  type: object
```

Problem solved--your payload will be passed as-is.  If it didn't escape the values, then it would cause problems that you'd not like.  What if the string is `=`?  well, that's a delimiter for query parameters and needs to be escaped.

The goal of this project is to let you use the client easily but if you choose to take a short cut and incorrectly model your api, you're going to have problems.

Consider the `type: object` solution, it's the right thing to do for your end users.

**Comment by cfaurer** [comment]
I'm defining a query parameter on GET and when I access the parameter in the generated node.js args.targetResolutionDate.value I get the following:

targetResolutionDate query parameter field with value entered = {"$gte": "2016-04-31T17:12:30.617Z"} 

becomes query = {"targetResolutionDate":"{\"$gte\": \"2016-04-31T17:12:30.617Z\"}"}

The query field is defined as follows:

{
"in": "query",
"name": "targetResolutionDate",
"description": "For filtering: the target resolution date.",
"required": false,
"type": "string"
}

How are you suggesting that this be defined in swagger so as to not result in an escaped string?

Thanks

**Comment by fehguy** [comment]
First, complex schemas in a query parameter are not supported by the Swagger Specification.  They _will_ be added in the 3.0 spec, now under the OAI:

https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md

Next, I suggest you use a POST with a body rather than a query string.  Then you can read the body--JSON or what have you, easily:

```
parameters:
  - in: body
    name: thePayload
    schema:
      type: object
```

**Comment by tjwise** [comment]
Thanks for your reply on June 16.  You indicate that I need to change my schema type - what is the proper annotation to accomplish that?  My spec is generated by the swagger-maven-plugin.  I must simply be missing it in the docs....

**Comment by zl-kolev** [comment]
Trying to put this string `<SchemaDefinition schemaRef="#/components/schemas/Order" />` inside a `description` to get a `yaml` output like this:
```yaml
description: |
    <SchemaDefinition schemaRef="#/components/schemas/Order" />
```
I'm escaping double quotes `"` by prefixing them with `\"` like this:
```
<SchemaDefinition schemaRef=\""#/components/schemas/Order\"" />
```
according to [this](https://yaml.org/spec/1.2/spec.html#id2787109) and I get this error:
```
@OA\Tag()->description is a "array", expecting a "string"
```
Anyone been through this?
