### ISSUE TITLE
array in header doesnt accept multiple entries

### ISSUE THREAD

**Issue by arilynN** [swagger-api/swagger-ui#2175]
- swagger-ui version : master

I have a problem with inserting multiple entries in an Array in the header. The code for this is : 

```
{
  "name": "token",
  "in": "header",
  "description": "token to be passed as a header",
  "required": true,
  "type": "array",
  "items": {
    "type": "integer",
    "format": "int64"
  },
  "collectionFormat": "csv"
}
```
I tried multiple collection formats, but none of them is working with my problem and I also changed the type to string ( originally i want a string with collectionformat pipes).

When I insert a single entry everything works fine, but when i make a comma or a line break the request doesnt call the method anymore.

**Comment by fehguy** [comment]
More details, please?  Do you mean that the call is made but the value is empty?  Can you share the output from the network console in your browser?

**Comment by arilynN** [comment]
right now my spec looks like this here: 
{
                        "name": "JsonArray",
                        "in": "header",
                        "description": "description",
                        "required": true,
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "pipes"
                    }

and when i type something like "test | test" into the ui there should be a array with 2 values, but what i got is an Array with the size 1 : [test| test]. It should be a list with the size of 2 and not 1. Did I do something wrong?

**Comment by fehguy** [comment]
OK, please pull master.  You should see something like this:

![image](https://cloud.githubusercontent.com/assets/249413/15520089/6cd85750-21b9-11e6-9106-dcf710bf0650.png)

So no need to add your delimiter when entering values.  With this parameter definition:

```json
"parameters": [
  {
    "in": "body",
    "name": "pet",
    "description": "Pet object that needs to be added to the store",
    "required": false,
    "schema": {
      "$ref": "#/definitions/Pet"
    }
  },
  {
    "name": "api_key",
    "in": "header",
    "description": "description",
    "required": true,
    "type": "array",
    "items": {
      "type": "string"
    },
    "collectionFormat": "csv"
  }
]
```

I see the correct headers being sent.  Please ensure that you have the correct `Access-Control-Allow-Headers` in your `options` response or the UI _may_ not send the headers.

**Comment by arilynN** [comment]
I just tried it with the Code that you have given and here its the same problem. I think the Request is been sent right :

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: text/html' --header 'api_key: 1,2' -d '{
  "id": 0,
  "name": "string",
  "tag": "string"
}' 'http://localhost:8080/api/resources'
```

but when I debug it with eclipse I have no list, there is just a single value and it should be a Array with 2 entries. 
![arraylist](https://cloud.githubusercontent.com/assets/4688550/15523385/5b4b87d0-221a-11e6-934d-6c0cfdbc4933.png)
Do I do something wrong here?

**Comment by fehguy** [comment]
ok hang on a bit.  Eclipse is a tool, not Swagger, and we need to rule out the source of error.  So do you see the headers being sent?

If so, you have a different issue.  I'm going to guess the following:

* The header is actually being sent as a single string value, which is correct.  The framework (which appears to be generated by the Swagger Codegen) is expecting an array.
* The actual value being sent is being unwrapped into an Array, and jersey doesn't know how to do this with a CSV type.
* If you changed your server to receive a `String` rather than a `List<String>` and try via curl, I'm guessing you'll see the string literal `1,2`.

If that's the case, then you should really open an issue on swagger-codegen.  The framework is relying on Jersey to unwrap a CSV into an array, which it really doesn't know how to do.  I believe the `multi` param type _will_ work out of the box, but I'm not sure.

**Comment by arilynN** [comment]
yes, when i send a string instead of a list I get the string 1,2 . I will open an issue in swagger-codegen then. Thanks for your help.
