### ISSUE TITLE
how can i make form data to json payload?

### ISSUE THREAD

**Issue by lolhyuck** [swagger-api/swagger-ui#2180]
- swagger-ui 2.4

I want to make form data to Json payload.

you can see what i want in below picture.

how can I do this???

I need to customize swagger ui?

![formpayload](https://cloud.githubusercontent.com/assets/12061740/15563069/0b82910e-2340-11e6-95fa-ce403fc0dad1.PNG)

**Comment by fehguy** [comment]
If you mean "HTML UI Form" when you say "form data", try enabling the Json editor (see the readme).  If you mean "form data" in the payload sense, there's no way to do that in Swagger.

**Comment by lolhyuck** [comment]
thx for reply.
I dont know I can express my question porpery, because I am not good at
English..

I want to get  key and value input box instaed of text area. and my api
server is Java language(Spring..)


2016-05-26 13:55 GMT+09:00 Tony Tam <notifications@github.com>:

**Comment by webron** [comment]
@lolhyuck - you need to do three things:
- make sure your spec is set to `consumes: appliication/json`
- use a `body` parameter to describe the JSON object you want, instead of using `formData`. `formData` is exclusively meant to be used with form-data related media types.
- In the configuration parameters of SwaggerUi, set `jsonEditor` to`true`. See more details at https://github.com/swagger-api/swagger-ui#parameters.
