### ISSUE TITLE
springmvc controller param not @RequestParam and param type is Boolean not work 

### ISSUE THREAD

**Issue by zhaiyuyong** [swagger-api/swagger-ui#2256]
When reporting a bug, please provide the following details:
- swagger-ui version 2.5.0
- a swagger file reproducing the issue  https://github.com/swagger-api/swagger-ui/blob/ebc5aa55f7ac2ccd301a59b00554b73feec0507b/src/main/javascript/view/ParameterView.js

when
public ResultObject<MessageCount> fetchMessageCount(Principal principal,Boolean isHidden)
isHidden has no @RequestParam 
it happen e.type.toLowerCase  type is null，type is null

**Comment by webron** [comment]
The code for SpringMVC is irrelevant. The problem is either with swagger-ui or the generated spec from the framework you use (which I assume is SpringFox). If you think the issue is with how swagger-ui displays it, please provide the spec file that shows the behavior. If the problem is with the generated spec, you'd need to open the ticket in the project that generates the spec.
