### ISSUE TITLE
send additional headers on each request

### ISSUE THREAD

**Issue by wodka** [swagger-api/swagger-ui#2257]
version: master

What I want to achieve: add 2 headers on each request for both authenticated and non authenticated requests.

Problems so far:
- the headers are only sent on requests without authentication
- to send it for requests with authentication they have to be added to the path security block (annoying, but ok)
- after adding them to the main security definition they show up in the authorization popup

this seems inconsistent to me - either require always a security block or never, but not partially both. And is there a way to remove entries from the authorization popup?

the Security config looks like this:

``` yml
oauth: 
  type: oauth2
mmt:
  type: apiKey
  in: header
  name: mmt
mmo:
  type: apiKey
  in: header
  name: mmo
```

I set the mmo and mmt headers programmatically by: 

``` javascript
window.swaggerUi.api.clientAuthorizations.add('mmt', new SwaggerClient.ApiKeyAuthorization('x-mmt', 'somevalue', 'header'));
window.swaggerUi.api.clientAuthorizations.add('mmo', new SwaggerClient.ApiKeyAuthorization('x-mmo', '1', 'header'));
```

![image](https://cloud.githubusercontent.com/assets/385731/16583839/75ef9e64-42b8-11e6-8efa-2848ad413808.png)

**Comment by webron** [comment]
Can you provide some more details? What is your `security` definition? Do you define it at the top level, or separately for each operation?

**Comment by wodka** [comment]
it looks similar to this:

```yml
swagger: "2.0"
info:
    version: 13.3.7
    title: something
host: somewhere
basePath: /
schemes:
    - https

produces:
    - application/json
    - application/xml

paths: 
    "/v2/somewhere":
        get: 
            summary: "get something"
            produces:
                - "application/json"
                - "application/xml"
            security:
                - { oauth: [] }
                - { mmt: [] }
                - { mmo: [] }
            parameters: []
            responses:
                200:
                    description: "list of something"

securityDefinitions:
    oauth:
        type: oauth2
        authorizationUrl: https://somewhere/oauth/v2/auth
        flow: implicit
    mmt:
        type: apiKey
        in: header
        name: mmt
    mmo:
        type: apiKey
        in: header
        name: mmo
```

**Comment by webron** [comment]
This is a bit to take in, so bear with me as I walk through the issues - I may miss a few things.
It sounds like some of the issues you're trying to solve can't be easily solved because the spec won't allow or support it.

Your shared security definition says `oauth` OR `mmt` OR `mmo`. According to what you described that you want to do, that doesn't seem to be it. It sounds like you need to describe it more as (`oauth` AND `mmt` AND `mmo`) OR (`mmt` AND `mmo`).

You can define that at the top level to affect all operations, but I'm not sure if that's what you're looking to do.

Obviously, adding those as security definitions will add those to the security pop-up - I don't really know what else you'd expect there to be.

**Comment by wodka** [comment]
Hi,

I would need something like: 

(oauth AND mmt AND mmo) OR (oauth AND mmt)

is this even possible?

**Comment by wodka** [comment]
Hi, can you give me a direction on how to specify this? I cannot find it in the spec :/

**Comment by webron** [comment]
Sure, assuming you have `oauth`, `mmt` and `mmo` defined as above in the `securityDefinitions`:

```yaml
security:
  - oauth: []
    mmt: []
    mmo: []
  - oauth: []
    mmt: []
```
