### ISSUE TITLE
Empty Joi.object() passed to Joi.array().items() will crash the frontend with a $ref error

### ISSUE THREAD

**Issue by srg2k5** [swagger-api/swagger-ui#2262]
ui-version: 5.1.0
No swagger file, sorry.

**Comment by webron** [comment]
there's no 5.1.0 - is that the version of Swashbuckle perhaps?
Without the spec file, we can't really investigate it.

**Comment by srg2k5** [comment]
That is the version id in hapi-swagger package.json.

And you are seriously telling me you can't load a Joi.array().items(Joi.object()) into a validator and load it to the swagger ui without a spec file? seriously?  It's not a complex error I'm telling you to reproduce here.

**Comment by webron** [comment]
Okay, with that attitude you're not going to get a lot of help. From what you describe, the issue seems to be related to hapi-swagger and should be opened there. I don't know which version of swagger-ui you use, and I'm not familiar with hapi-swagger, and no, I'm not going to test it for you. If you'd like to calm down and try to work together to try and figure this out, feel free to add a comment.

**Comment by srg2k5** [comment]
Ah see that's your problem.  You think you are helping me.  That's inaccurate.  I know exactly what the problem is. Swagger delivers you the JSON object fine.  You parse it giving a $ref error on a Joi Object that has no keys inside a Joi Array Items call.   It's very clearly crashing on the swagger ui side.  If you feel you don't care to fix a major bug in your code cause you don't like my attitude, more power to you, code still broken ;)

**Comment by fehguy** [comment]
if your integration is doing the wrong thing, then it's not a bug in swagger-ui.

**Comment by srg2k5** [comment]
You are right!  If integration is wrong it's not a swagger bug. Problem of course is this is all Swagger integration!  Swagger to Swagger-UI.   The Joi Validation works like a champ!  So um....It seriously takes 3 seconds to load this and verify it's broken lol, it's a one line schema.

**Comment by fehguy** [comment]
Nah, seriously.  If you share your swagger definition, like @webron asked, then we can see if it's a swagger issue.  If it's in your code, or we need to look at your code, it's an integration issue so please either share your swagger definition, the relevant parts, or open in on Hapi.

If we debug every integration in every language, we'd need 50 people.  So you can help by following the above, or lean on the Hapi folks.

**Comment by srg2k5** [comment]
I just shared the definition.  

var myCheck = Joi.array().items(Joi.object())

removing the Joi.object() or adding in even a single key swagger-ui works.  Leave it as an empty object, and swagger ui gives a $ref error cause there is no reference at that point, it's empty.

I really don't understand what you are missing, I gave you the exact definition required.

**Comment by fehguy** [comment]
So, that's not the definition.  Joi is software, and that's a swagger integration that some other (nice) person made.

A swagger definition is JSON or YAML, and looks like this:

http://petstore.swagger.io/v2/swagger.json

```json
{
  "swagger": "2.0",
  "info": {
    "description": "This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.",
    "version": "1.0.0",
    "title": "Swagger Petstore",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "petstore.swagger.io",
  "basePath": "/v2",
  "tags": [
    {
      "name": "pet",
      "description": "Everything about your Pets",
      "externalDocs": {
        "description": "Find out more",
        "url": "http://swagger.io"
      }
    }, ....
```

That's the interchange.  Javascript is not the interchange, nor is joi nor is hapi.  So if you share your definition, which will be like the above, then you may get help.

**Comment by srg2k5** [comment]
So you wrote a piece of software that relies on swagger, that relies on Joi.   I gave you the valid Joi definition.  Swagger is handing you a valid Joi representation.   I know what software stops where, that's why I came to you, Swagger works fine, your UI is breaking.  I'm done here, if you want to figure it out you will, I'm not about to break my code again, just to send you a simple test file you could generate in 2 seconds to fix your own software. Good day mate.

**Comment by fehguy** [comment]
You must be new to this whole software thing.  Swagger doesn't rely on joi.  Do we write Joi?  [No...](https://github.com/hapijs/joi).  Do we depend on it?  [No...](https://github.com/swagger-api/swagger-ui/blob/master/package.json)

I suggest you read up on OSS etiquette and how dependencies work.

**Comment by srg2k5** [comment]
So you are telling me right now that Swagger isn't using Joi to generate it's definition?  LOL, don't be an asshat.   Yes Joi is not swagger, but without Joi in the context of what we are talking about Swagger is freaking worthless. Again in this context.  Swagger is relying on Joi, and Swagger-UI on Swagger.   The important part is the Joi is accurate, and the swagger definition file is valid, the part that breaks is swagger-ui parsing the file looking for a $ref when there isn't one cause its empty.     And no I'm not new to software, I'm used to pricks like you passing the buck.   Swagger DEFINITELY relies on Joi in this circumstance.

**Comment by fehguy** [comment]
hah, ok you win.  I also invented the internet so when it's broke, just send along your requests.  Seriously, if somebody writes an integration that's all jacked up, and writes XML instead of JSON, for instance, is it my job to fix?  Nah.

I support this community like crazy.  But you're not welcome to my help if you're going to have a shit attitude.  Go use something else if you don't want to respect the authors, who don't get paid to do this.  No more replies from me on this, bye @srg2k5

**Comment by srg2k5** [comment]
Lol.   Now you are just straw manning.  The fact is the flow is Joi -> Swagger -> Swagger-UI.   That's the consumption model.  The model doesn't break until Swagger-UI.  Everything else works.   I am in no way blaming you for the internet, however you have to admit the conditions I gave you aren't hard to replicate at all.  You could have done it 15 times by now if you have a proper test suite, which you do right?   Look guy, I aint trying to give you a hard time, but you are me.  Seriously you are trying to give up complete responsibility of fixing your own code cause you don't like my attitude.  I have an attitude cause your requirements are ridiculous. I reported the bug to you, it aint my job to fix for you unless I got time.   If i get the time I'll submit you a patch and all that jazz, but for now if you attach that Joi definition to a hapi route and consume it with swagger your json is returned then you bork on processing it.  FFS man, I don't care what you fix in the grand scheme of things, but its apparent this is a SWAGGER-UI issue.

**Comment by fehguy** [comment]
If you don't share the JSON that goes to Swagger UI, or use one of the tools I work on, I am not going to bother replicating it.  My guess is you don't know what swagger JSON is, which is why you won't share it.

Integrations are your problem.  If you share the JSON, you can consider yourself lucky if I look at it because you're being a prick.  We don't test every integration made because there are over 3,000 of them.  If you choose to use a shitty one, or one that is broken, or better yet--if you don't know how to use it right, it's your job to work with the framework author.

Again, I have offered to look in the past (scroll up) but the common dialect is the swagger definition, i.e. JSON.  I don't care if you use Hapi, java, php, python, ruby or whatever.  I'm not running your server, your integration.  This is how you submit issues, again, read the etiquette on OSS.

Getting support on an open-source project, for free, is a privilege, not a right, and you lose the right when you act like the world owes you a lunch.

**Comment by srg2k5** [comment]
I don't need support, you do. It's not my error.   You act like you are fixing my bug, you aren't. you are fixing your bug, getting free support from the community to fix your bugs is a privilege, not a right.  And I know what swagger.json is lol, now you are intentionally being an asshole ;)  It's cool man, don't fix it, I know the work around, don't pass empty Joi.object() to a Joi.array.items() it will throw a ref error in swagger-ui.  Keep in mind buddy, I'm letting you know about YOUR bug, not mine. Not a single thing accomplished here will help me out.     I already fixed my code base to work around your error.
