### ISSUE TITLE
Wrong usage of Api Key when requesting the swagger file

### ISSUE THREAD

**Issue by cbornet** [swagger-api/swagger-ui#2299]
- swagger-ui version : current petstore.swagger.io (2.1.4?)
- a swagger file reproducing the issue : https://rawgit.com/cbornet/google-fcm-swagger/master/swagger.yaml

Click on "Explore"
Click on operation's authorize button
Enter a key and click on "Authorize"
--> `Can't read from server. It may not have the appropriate access-control-origin settings.`
This is because the browser tries to GET swagger.yml (again?) with the Authorization header added in a CORS request.
But the Authorization header is not to be used for the host of the spec but for the host of the API so it shouldn't have been added.

**Comment by hackling** [comment]
> This is because the browser tries to GET swagger.yml (again?) with the Authorization header added in a CORS request.

I think I'm having the same issue. I'm serving the `swagger.json` as a static asset from a Phoenix application. 
Everything works with Swagger-UI except this Authorize part.

I suspect that it's because the authorize action is sending an OPTIONS request, and I haven't configured the application to handle that, and it subsequently returns a 404 status code.

**Comment by bodnia** [comment]
@hackling @cbornet this is a current flow: to proceed with all requests with authorization. @webron @fehguy could you please clarify the details of how the flow and ui should be changed to fit the request?

**Comment by webron** [comment]
@cbornet can you check if you experience the same issue with 3.X?

**Comment by cbornet** [comment]
Seems OK. Great job on the new UI !
