### ISSUE TITLE
String example breaks UI

### ISSUE THREAD

**Issue by morris** [swagger-api/swagger-ui#2369]
Consider this Swagger File:

```
{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Bug"
  },
  "paths": {
    "/": {
      "get": {
        "description": "Bug",
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "properties": {
                "test": {
                  "type": "string",
                }
              }
            },
            "examples": {
              "application/json": "{}"
            }
          },
        }
      }
    }
  }
}
```

Importing this into Swagger UI 2.2.2 breaks with "jsyaml is not defined". Change the examples.application/json value to an unquoted {}, and it will work. Looks like Swagger UI expects an object there, even though a string is valid JSON, too.

Putting JSON inside a string example is not intended by the spec (http://swagger.io/specification/#exampleObject) but I would not expect Swagger UI to break. Maybe a console warning is enough.

Thanks for your effort!

**Comment by Narcotic** [comment]
+1

**Comment by kshakir** [comment]
This is the commit that seems to have caused the issue of "jsyaml is not defined": e4dc26478a106a92680ee3178f28d21c598da30e
A git bisect on master returns: 515f1420268e579445ebb91df47ba941e5cce2b3

The js-yaml js file is [still present](https://github.com/swagger-api/swagger-ui/blob/f7424a700989e89929e0404f12a8363cc8d27bfd/dist/lib/js-yaml.min.js) in this repo, and re-adding it back to dist/index.html seems to fix this issue. I don't know if re-adding the js regresses #2221. As I don't know how to test that issue, I'm forgoing a PR at this time.

FYI: Instead of the json reported earlier, we're using yaml and are having the same issue with a using a string value.

Broken
```yaml
swagger: '2.0'
info:
  title: Debug Yaml
  version: '2369'
paths:
  '/example':
    get:
      responses:
        '200':
          schema:
            properties:
          examples:
            application/json: |
              {}
```

Working
```yaml
swagger: '2.0'
info:
  title: Debug Yaml
  version: '2369'
paths:
  '/example':
    get:
      responses:
        '200':
          schema:
            properties:
          examples:
            application/json: {}
```

**Comment by webron** [comment]
No longer an issue in 3.X.
