### ISSUE TITLE
Infinite loops in Swagger UI Example values

### ISSUE THREAD

**Issue by AndrewCampbellSynchronoss** [swagger-api/swagger-ui#2417]
I'm getting infinite loops in my Swagger UI example values.

```
<?xml version="1.0"?>
<Folder>
  <folder>
    <folder>
      <!-- Infinite loop $ref:Folder -->
    </folder>
  </folder>
</Folder>
```

As you can guess from the name, I'm trying to describe a filesystem folder, which can contain other folders ([example swagger attached](https://github.com/swagger-api/swagger-ui/files/484670/example.txt))

I'm using version 2.2.0

**Comment by bodnia** [comment]
@AndrewCampbellSynchronoss this is expected behaviour as there is infinite loop into `Folder` definition. If you have a fork and would like to remove this comment [here](https://github.com/swagger-api/swagger-ui/blob/master/src/main/javascript/view/partials/signature.js#L872) you can remove
call of 
`output = getInfiniteLoopMessage(descriptor.name, descriptor.config.loopTo);` 
and equal it to empty string, for example.
Then build project with `npm run build`.
