### ISSUE TITLE
Unable to upload file

### ISSUE THREAD

**Issue by JaspreetKaur16** [swagger-api/swagger-ui#2491]
I am using following versions...
- springfox-swagger-ui-rfc6570-1.0.0.jar
- springfox-core-2.6.0.jar

There exists following controller in my project. By using dataType = file I am able to see choose file button, I select a file but the file contents are not shown in request payload neither I receive the file contents in my controller.
The inputStream is not populated with the file contents.
Can you please help me with this issue ?

@Controller
public class GreetingController {

	@ApiOperation(consumes="multipart/form-data", value = "Check in a new asset !!!")
	@RequestMapping( method = RequestMethod.POST, value = "/greet")
	@ResponseBody
	@ApiImplicitParams({
		@ApiImplicitParam(name="inputStream", paramType="form", dataType="file"),
		})
	public String greet(@ApiParam(name="inputStream") @FormParam(value="inputStream") @WebInputStream InputStream inputStream) throws IOException {
		if(inputStream.available()>0){
			System.out.println("Stream populated well !");
		}
		return "hello";
	}

}

Thanks,
Jaspreet

**Comment by webron** [comment]
Please open the ticket on Springfox.

**Comment by trip-somers** [comment]
I have this issue with SwaggerUIBundle as well. My issue matches OP's description except that I am using SwaggerUIBundle instead of Springfox.

**Comment by shockey** [comment]
@trip-somers, please open a new ticket and we'll look into it 😄

**Comment by trip-somers** [comment]
I appreciate the quick response, but I was about to figure this out after playing around with it some more.

I'm not sure exactly why Swagger-UI was showing an empty file, but my issue was (at least) that I was trying to process the file upload with a Laravel controller that was not reading the file because it was PUT request. When I switched it to POST in Laravel and in my Swagger YAML, the file starting working again.

It may be (probably is?) some HTTP spec thing I'm not aware of whereby multipart/form-data and PUT don't get along.

**Comment by shockey** [comment]
@trip-somers, yeah, sounds like it's a PHP thing. https://laravel.io/forum/02-13-2014-i-can-not-get-inputs-from-a-putpatch-request

`¯\_(ツ)_/¯`

Glad you got it working.
