### ISSUE TITLE
File download for application/zip corrupt

### ISSUE THREAD

**Issue by Ben305** [swagger-api/swagger-ui#2538]
Follow up from #1605 

Still having problems with 2.2.8:

Response headers
<pre>
Connection:keep-alive
Content-Disposition:attachment; filename=File.zip
Content-Length:1116714
Content-Type:application/zip
Date:Mon, 28 Nov 2016 22:13:50 GMT
Server:nginx/1.6.2
X-Powered-By:Sails <sailsjs.org>
</pre>

The downloaded file has a size of 2 MB, while downloading the file with curl results in a (valid) file with a size for 1,2 MB

Request headers
<pre>
GET /downloadFile HTTP/1.1
Host: my.server.com
Connection: keep-alive
Accept: application/zip
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
Authorization: JWT (removed token)
Referer: https://my.server.com/swagger-ui/?url=https://my.server.com/link/to/swagger.yaml
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
</pre>

**Comment by fehguy** [comment]
This has been confirmed to be fixed.

**Comment by RainerMueller82** [comment]
Hi, I'm using response.AsAttachment in Nancy, which resulted in a download link in the response body of swagger UI. This seems to have changed now. All data is shown as text in the response body field now. Is this really what's intended?

**Comment by fehguy** [comment]
All depends on the request definition and the response headers.  You'll need to share more information in a new ticket.

**Comment by RainerMueller82** [comment]
Ok, I just tried to reproduce this in order to record the used request definition/response headers. When I use "application/octet-stream" with "Response.AsAttachment" swagger displays a link in the response body. When this link is clicked the file is being downloaded - *thumbsUp*. Unfortunately the downloaded file still seems to have the observed Encoding problem (UTF-8?). The file is bigger than the original file, and therefore corrupted ... Is there anything I can provide to help hunting down this problem?

BR, Rainer.

**Comment by fehguy** [comment]
OK please open a new issue and share the swagger definition that is being used to render swagger-ui.
