### ISSUE TITLE
Swagger paths can't be expanded when tag has special characters

### ISSUE THREAD

**Issue by abelsilva** [swagger-api/swagger-ui#2561]
Sample

http://petstore.swagger.io/?url=https://gist.githubusercontent.com/abelsilva/11a1cd982c20fbf11d4cdf65e78bfd8f/raw/4a05727ba9695520a234ac6d226c182dc9d2ab0a/swagger.json

If you click on ```Languages - áè``` it will expand and show the paths, then, if you click on the path itself, it won't expand
![image](https://cloud.githubusercontent.com/assets/1167088/21101389/51118034-c04f-11e6-96bf-a544f7d8195b.png)

Happening with latest version and online demo version

**Comment by abelsilva** [comment]
If tag is HTML encoded, it's not even possible to open the tag itself

http://petstore.swagger.io/?url=https://gist.githubusercontent.com/abelsilva/11a1cd982c20fbf11d4cdf65e78bfd8f/raw/52338fcb33d4a18d348392c6e9aa51a75c7c7034/swagger_endoded.json

**Comment by lidajia** [comment]
since release version 2.2.1, if the resourcepath conatins '/' , the path can not expand.
example:
click on the path '/apis/hhhh/phoenix/v1/users/{user-id}' can not expand the path, click 
`Expand Operations` can expand all paths

![12345](https://cloud.githubusercontent.com/assets/7565495/21139969/7ff00dd6-c170-11e6-8f56-229125f0e1ff.png)

**Comment by abelsilva** [comment]
That 'workarround' works on my first sample, on the second one it doesn't

**Comment by monkeyFeathers** [comment]
I had a similar problem with ':' and threw up a PR that seems to fix that, but I haven't tested whether it fixes your url encoded tag issue.

**Comment by fehguy** [comment]
This should be fixed now.
