### ISSUE TITLE
Try it out doesn't make the correct request for authenticated endpoints

### ISSUE THREAD

**Issue by Silvea12** [swagger-api/swagger-ui#2663]
Hey! So, the try it out stuff seems to only send the OPTIONS header when running an authenticated request (authenticated by OAuth2). It never actually runs the correct method for the endpoint.

An example file where this breaks: https://hastebin.com/xopomoyafo.yml
(The host provided is running an old version of the API, not to this spec, but you can still see the issue if you inject a false key for testing or write your own OAuth2 server)

It also never sends the `Authorization` header.

Using master 38f74164a7062edb5dc80ef2fdddda24f3f6eb85

**Comment by frol** [comment]
You have to configure your server to handle CORS properly: https://github.com/swagger-api/swagger-ui#cors-support

**Comment by Silvea12** [comment]
Using node http-server works fine, and I already enable CORS, configure
caching via headers, etc.

**Comment by Silvea12** [comment]
I mean that's what I'm doing and it's not working still. I can send you all
the request data and response data that it sends if you wish.

**Comment by frol** [comment]
Providing all the information you can gather will help greatly.

I am using 2.2.10 release with my API server and OAuth2 (Password Flow) works fine. You may compare your requests/responses with ones my example server produces: http://flask-restplus-example-server.herokuapp.com/api/v1/ (sources are here: https://github.com/frol/flask-restplus-server-example)

**Comment by webron** [comment]
Make sure *all* the headers are included in your CORS configuration.

**Comment by Silvea12** [comment]
# General
- Request URL:http://127.0.0.1:8082/user
- Request Method:OPTIONS
- Status Code:403 Forbidden
- Remote Address:127.0.0.1:8082

# Response Headers
- Access-Control-Allow-Origin:http://127.0.0.1:8081
- Cache-Control:no-cache
- Content-Encoding:gzip
- Content-Length:57
- Content-Type:text/plain; charset=utf-8
- Date:Wed, 15 Feb 2017 15:36:54 GMT
- Vary:Accept-Encoding
- X-Content-Type-Options:nosniff

# Request Headers
- Accept:*/*
- Accept-Encoding:gzip, deflate, sdch, br
- Accept-Language:en-US,en;q=0.8
- Access-Control-Request-Headers:authorization
- Access-Control-Request-Method:GET
- Connection:keep-alive
- Host:127.0.0.1:8082
- Origin:http://127.0.0.1:8081
- Referer:http://127.0.0.1:8081/
- User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by frol** [comment]
Ah, I see. I have faced the same issue. It is nothing to do with Swagger. It is how preflight OPTIONS requests work due to CORS protection. You cannot include custom headers into the preflight requests:

* http://stackoverflow.com/questions/13994507/how-do-you-send-a-custom-header-in-a-cross-domain-cors-xmlhttprequest
* https://www.sencha.com/forum/showthread.php?265119-Authorization-header-not-sent-on-preflight-OPTIONS-request
* https://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0

Your API server MUST handle preflight requests differently or do not require authentication on OPTIONS requests. In my example server we have worked it out by detecting preflight requests and returning HTTP/200 with all implemented methods listed in `Access-Control-Allow-Methods`: https://github.com/frol/flask-restplus-server-example/commit/965339df4e71ac2d971b270e32e9cfab6feb4f7e
