### ISSUE TITLE
Swagger-UI using Spring boot loaded in AWS beanstalk: 404 error config../ui

### ISSUE THREAD

**Issue by codeMmaster** [swagger-api/swagger-ui#2687]
When reporting a bug, please provide the following details:
- swagger-ui version
- a swagger file reproducing the issue

I got the latest version of swagger 2 and swagger ui:  2.6.1

This is my swagger config

`@Configuration
@EnableSwagger2
public class SwaggerConfig {                                    
    @Bean
    public Docket api() { 
        return new Docket(DocumentationType.SWAGGER_2)  
          .select()                                  
          .apis(RequestHandlerSelectors.any())              
          .paths(PathSelectors.any())                          
          .build();                                           
    }
}`

My Main App.

`@SpringBootApplication
@EnableCaching
@EnableScheduling
public class ExternalCloudApplication {

	public static void main(String[] args) {
		new SpringApplicationBuilder(ExternalCloudApplication.class)
			.properties("spring.config.name:application,dev-application")
			.build()
			.run(args);
	}
}
`

On Localhost it works fine!
http://localhost:8080/swagger-ui.html

but on cloud...I get this;

![image](https://cloud.githubusercontent.com/assets/20556254/23207492/bfe00064-f8f1-11e6-972a-83b98d7d9612.png)

I am pretty new to Swagger and Spring boot

Thanks in advance!!

**Comment by webron** [comment]
Welcome to using swagger.

You're using Springfox and not swagger-ui directly. We don't keep track on which version they pack inside their library and can't tell from that which version of swagger-ui you use. Since you're saying it's working locally, the issue is related to the deployment of the tool and not to the tool itself. Please open the ticket on the Springfox project and ask for their assistance.
