### ISSUE TITLE
Execute button does not work if an operation has a constant parameter

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#2841]
Swagger UI v. 3.0.4 (as of commit bfe5963)
Chrome 56, Firefox 52 on Windows 7

Spec:
```
swagger: '2.0'
info:
  version: '1.0'
  title: test
host: httpbin.org
schemes: [https, http]
produces:
  - application/json
paths:
  /get:
    get:
      parameters:
        - in: query
          name: foo
          type: string
          required: true    # If you comment this line, "Execute" works
          enum: [bar]
      responses:
        '200':
          description: OK
```

This operation has a constant parameter (a required parameter limited to a single-value `enum`). When you do "try it out", the parameter value is auto-populated (as expected) but the "Execute" button does not work - nothing happens, no request is sent, cURL example is not generated. There are no errors in the browser console.

Expected result: "Execute" button generates a cURL example, sends a sample request and displays the response.

**Comment by echmielewski** [comment]
I think the issue is more with the selection box itself. I notice that with multiple parameters the execute button does not work until you change the select.

For example, if the parameter options are ["one","two"], the page loads and looks like "one" is selected.  However, the "Execute" does not work.  If you select "two", then back to "one", the "Execute" works as intended.

**Comment by webron** [comment]
Yeah, this issue and #2902 might be the same.

**Comment by bodnia** [comment]
@echmielewski exactly, the issue comes from select. I am working on this.
