### ISSUE TITLE
Swagger JSON generated by Springfox shows 'Consumes' for GET operations

### ISSUE THREAD

**Issue by davidporter65** [swagger-api/swagger-ui#2933]
This is a similar problem to #2042.

I have a GET API request which is showing up in the Swagger JSON as consuming 'application/json'.

It's a GET, so it doesn't consume anything. How can I stop this appearing in the Swagger?

**Comment by webron** [comment]
Can you share your spec and point to the operation in question?

**Comment by davidporter65** [comment]
By 'spec', do you mean the Swagger JSON? We generate this using Springfox. Sorry, I should have raised this issue on that project.

**Comment by webron** [comment]
Yeah, the Swagger JSON. Please check the following - in the JSON file, if you see `consumes` on the operation, then the issue is with the generation and should be opened on Springfox. In that case, please close the ticket here.

If it's not there, then the issue is with the UI. If you provide us with the file we can investigate further.

**Comment by davidporter65** [comment]
Yep, it's in the generated Swagger JSON.
