### ISSUE TITLE
Any guidance on rendering Swagger-UI in a react app?

### ISSUE THREAD

**Issue by GeekyTex** [swagger-api/swagger-ui#3000]
Hey guys,

Liking the new direction in Swagger-ui v3!

Our organization has found a ton of value in swagger/Open-API specs and using Swagger-UI to host interactive versions of our APIs. 

I've been working to extend our (internal) capabilities by creating a pretty light-weight, React based, single-page app that can display all of our uploaded spec files and dynamically render them (with different backend endpoints like dev, stage, prod) in Swagger-UI, all from a single web page. 

Going with react since the entire project is serverless and hosted in AWS. 

My question....

I know you guys are using react extensively under the hood, but the top level (i.e. swagger core) looks mostly like common js modules. Is there any guidance on consuming swagger-ui components directly inside of a react based project? Has anyone tried it yet? I've hit a more than a few speed-bumps up till now (in fairness, react/JSX is pretty new to me still).

At this point, I have a path forward embedding swagger-ui as an iframe in my project and having the target URL for the API spec get pulled from a query parameter, but it would be awesome if there were a more direct way to consume swagger-ui in react.

Thanks for any clarification or guidance in advance. Also curious if I've gone completely off-course with how I think react works at this point ;)

**Comment by aaronfullerton** [comment]
I'd also be extremely interested in learning if there is a recommended way to consume SwaggerUI in a React application without importing the entire build. If there's currently not a way to do this, I would be more than happy to create a PR, if I could get a nudge in the right direction from the team.

For anyone who just wants to embed SwaggerUI in a React application, here's a simple component that may be helpful. 

```jsx
import React, {Component} from 'react';
import SwaggerUi, {presets} from 'swagger-ui';
import 'swagger-ui/dist/swagger-ui.css';

class SwaggerTest extends Component {
  componentDidMount() {
    SwaggerUi({
      dom_id: '#swaggerContainer',
      url: `http://petstore.swagger.io/v2/swagger.json`,
      presets: [presets.apis],
    });
  }

  render() {
    return (
      <div id="swaggerContainer" />
    );
  }
}

export default SwaggerTest;
```

**Comment by shockey** [comment]
Thanks for the kind words @GeekyTex!

So far in v3, we have prioritized support for non-React use cases because they're the largest swaths of users of the tooling. We have a few interfaces available, but a top-level React wrapper is not something we have yet. That said, we do _not_ want to turn a blind eye to the growing React dev community, so this feedback is super helpful.

> ...I've hit a more than a few speed-bumps up till now...

Have you happened to stumble upon a `Only a ReactOwner can have refs` error? We're currently listing the `react` package as a dependency, which comes to mind as a roadblock to consuming Swagger-UI as a child component - since it results in `swagger-ui` bringing its own React, which breaks things.

You having to put Swagger-UI in an iframe is unfortunate, and not the developer experience we're aiming for. Please feel free to share some code here or ask questions if you're stuck... One of us has probably seen the error you're seeing before 😄 

---

@aaronfullerton, that's a great start. I'd love to see a named export that provides a top-level component for React consumers. Feel free to open a PR adding this component to the UI core, and we'll hash out the details (the name for the component comes to mind as a discussion point, as does how to map props to configuration options for the constructor).

**Comment by GeekyTex** [comment]
Thanks for the replies @aaronfullerton and @shockey 😃 

> Have you happened to stumble upon a Only a ReactOwner can have refs error?

No, I didn't hit that one specifically, though I'm fairly confident my original approach broke well before I'd even get to that point 😉 

I have made progress though! A **huge** thanks to @aaronfullerton for steering me in the right direction. In my initial attempts, I was getting very vague react timer errors (I tried to revert back to the initial code/conditions, but was unable to reproduce the original error, **sorry to future search clickers!**). 

I was missing two critical pieces that @aaronfullerton covered above. Namely:
* Use **componentDidMount()** to wait for component to be available since we need to directly modify the DOM. [More details here](https://facebook.github.io/react/docs/react-component.html#componentdidmount)
* Directly specify the DOM ID in the div returned from the class component. 

A couple other minor issues I saw surface depending on project complexity and libraries used were:
* If your project also uses babel-polyfill, you'll likely get an error like this
   * `ERROR in ... only one instance of babel-polyfill is allowed`
* Some early skeleton code I was using actually ran the localhost dev server via node, which would result in a `window is not defined` error when trying to run webpack 
   * I haven't had any issues with that since switching over to webpack-dev-server

Here's an example of what my working code looks like now. It's a small expansion on what Aaron already provided and allows me to specify **url** or **spec** via props.

swagger.js
```jsx
import React, {Component} from 'react';
import PropTypes from 'prop-types';

import SwaggerUi, {presets} from 'swagger-ui';
import 'swagger-ui/dist/swagger-ui.css';

class SwaggerUI extends Component {

    componentDidMount() {
        SwaggerUi({
            dom_id: '#swaggerContainer',
            url: this.props.url,
            spec: this.props.spec,
            presets: [presets.apis]
        });
    }

    render() {
        return (
            <div id="swaggerContainer" />
        );
    }
}

SwaggerUI.propTypes = {
    url: PropTypes.string,
    spec: PropTypes.object
};

SwaggerUI.defaultProps = {
    url: `http://petstore.swagger.io/v2/swagger.json`
};

export default SwaggerUI;
```

And a sample top-level App component to consume it:

index.js
```jsx
import React, { Component} from 'react';
import ReactDOM from 'react-dom';

import SwaggerUI from './components/swagger';

import getSpec from './spec/sample_spec';

class App extends Component {

    render() {

        const sample_spec = getSpec();

        return (
            <div>
                <SwaggerUI
                    spec={sample_spec}
                />
            </div>
        )
    }
}

ReactDOM.render(<App />, document.querySelector('.container'));
```

**Note:** You could simply specify `<SwaggerUI />` and it would default to rendering the PetStore example.

I didn't implement the other configuration options yet due to time and need, but they should be pretty minor to add. 

Thanks again guys, very happy I can lose the iframe approach.  👍

**Comment by shockey** [comment]
cc @ponelat! i know you're dealing with this/will be soon.

**Comment by olslash** [comment]
Anyone know if we need to call something to destroy/release resources from SwaggerUi() on `componentWillUnmount`?

**Comment by ponelat** [comment]
So we do have a mechanism where you can use a pure-react approach. But there are uglies, that would need to get ironed out ( we want this, but of course... time!)

- babel-polyfill is one of them, need to replace with babel's transform-runtime... as well as clean up any code that use's unsupported instance methods (eg: `Array.prototype.includes`).
- React/React-DOM as peerDependencies, the current workaround is the use webpack aliases, to ensure only one React ends up on the page.
- Some minor issues around styling, which we're sorting out anyway.
- documentation, documentation... oh and documentation. There is a method, so deeply hidden. But it create a root-level react component that has a binding of props-to-actions, so that you can control swagger-ui ( ie: one such prop would probably be `spec` ).

This is probably not a complete list, and much as I'd like to write some up. I don't have a sample to share yet. But perhaps soon.

**Comment by wongterrencew** [comment]
Hi! I tried to follow the example provided by @GeekyTex in his comment [here](https://github.com/swagger-api/swagger-ui/issues/3000#issuecomment-298679801) but when I try to view my page, I'm getting an error `Error: Cannot find module "."`

I created a repository and a PR that demonstrates this: https://github.com/wongterrencew/swagger-react-example/pull/1

Any ideas what might be my issue?

**Comment by aaronfullerton** [comment]
@wongterrencew We ran into a similar problem early on. If you're problem is the same is ours, it has to do with how webpack attempts handle the conditional imports in the `yaml-js` dependency. I didn't want to spend much time debugging the real issue, and since mocking `fs` in the webpack config didn't resolve things for us, I developed a workaround by forking the `yaml-js` repo and removing the offending code. 

If you want to see if this works for you, in your `package.json`, add this to your dependencies:
`    "yaml-js": "git+https://github.com/cloud-elements/yaml-js.git"`

Then you need to tell webpack to use that version of `yaml-js` when bundling. I did this by adding an alias, like so: 
```js
  resolve: {
      extensions: [...],
      alias: {
        'yaml-js$': path.resolve(__dirname, 'node_modules/yaml-js/lib/yaml.js')
      },
    },
```

Good luck!

**Comment by wongterrencew** [comment]
@aaronfullerton it worked for me, thanks!

**Comment by shockey** [comment]
Closing this since the original problem has been addressed!

Better support for this use case will live on in #3158.

**Comment by nrathi** [comment]
Has anyone seen this error before: `swagger_ui_1.default is not a function`?

**Comment by shockey** [comment]
@nrathi, if you're still having trouble with Swagger-UI, feel free to open a new ticket.

**Comment by dinakar2705** [comment]
@GeekyTex thanks for your help, but my react app is rendering without any css styles being applied, can you help me with that?

Code:
import React from 'react';
import PropTypes from 'prop-types';
import getSpec from './sample_spec.json';
import SwaggerUi, {presets} from 'swagger-ui';
import 'swagger-ui/dist/swagger-ui.css';

class SwaggerUI extends React.Component {

    componentDidMount() {
        SwaggerUi({
            dom_id: '#swaggerContainer',
            url: this.props.url,
            spec: this.props.spec,
            presets: [presets.apis]
        });
    }

    render() {
        return (
            <div id="swaggerContainer" />
        );
    }
}

SwaggerUI.propTypes = {
    url: PropTypes.string,
    spec: PropTypes.object
};

SwaggerUI.defaultProps = {
    url: `http://petstore.swagger.io/v2/swagger.json`
};

class Spec extends React.Component {

    render() {
<img width="478" alt="screen shot 2018-03-28 at 4 40 45 pm" src="https://user-images.githubusercontent.com/5356525/38062054-d3705cf6-32a6-11e8-80d9-e93c551696d2.png">

        return (
            <div>
                <SwaggerUI
                  spec={getSpec}
                />
            </div>
        )
    }
}

export default Spec;
