### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by bjne** [swagger-api/swagger-ui#3006]
1) Sorting of operations is by default based on the _order of a unordered object_ (but can be set in operationsSorter)
2) Same goes for tags/apis, based on the order of a unordered object, and not even able to override (apisSorter is gone)
3) Not "possible" to override css without rebuilding
4) Tags actually _are_ ordered in the /tags array, so it would be logical to base ordering by default on that order
5) the logical default operations sorter imho is: https://pastebin.com/raw/a3WVuxvV
6) methods are defined in lowercase, for example "post", which is really not a http method, POST is (but this is a detail)
7) building is not documented

The way the ordering is currently implemented, will produce random results if:
1) api documentation is autogenerated
2) json_pp < swagger.json > swagger.json.new && mv swagger.json.new swagger.json

**Comment by shockey** [comment]
Sorry for the delay here, this got lost in the fray a while back. I will ask that if any of these are still an issue, that you open an individual issue for each item.

1) We do our best to pick up on the original ordering of the JSON/YAML document, but JS objects don't guarantee key order in memory, so we don't either. It hasn't been an issue in any major browsers AFAIK!
2) Tags are ordered by the order of tags in the global `tags` array by default, and custom behavior can be defined through `tagsSorter`.
3) You can always override CSS, the C stands for cascading :smile: I haven't been able to think of a more elegant way to allow CSS extension, do you have any ideas?
4) It does (this may not have been the case in April, but I think it was)
5) Feel free to open a PR or issue for this, and we can discuss.
6) This isn't us, this is the OpenAPI Specification team's decision. You should open an issue there for this issue.
7) See https://github.com/swagger-api/swagger-ui/tree/master/docs/development!

I'm closing this out since it's quite old (our fault). Feel free to reply if you'd like to continue the conversation!
