### ISSUE TITLE
SwaggerUIBundle onComplete callback

### ISSUE THREAD

**Issue by supsup** [swagger-api/swagger-ui#3028]
v3

Currently there is no callback on completion of the ajax calls from SwaggerUIBundle
Is this done via a plugin?

If not can we have a property like:
onComplete:  function 
where the function will execute after SwaggerUIBundle has loaded all ajax requests.

**Comment by 1Map** [comment]
+1

**Comment by webron** [comment]
Yeah, we're aware this is missing. Seeing 4 people interacting on this ticket already. Can you share how you'd use the onComplete? Curious to hear about different use cases.

**Comment by 1Map** [comment]
One use case is for example:

1) Currently I cannot collapse the "Models" part in the UI at runtime (after loading).  I want, for example the "Models" part to be collapsed by default.

2) Second case is:  I have a "password" parameter and assigned the format as "password".  Problem is that the UI does not mask this edit field, so I cannot do, for example, a demo to clients and login as they see my password.  So, I want to modify this parameter field, somehow, by maybe using jquery to alter the input type from text to password.

As you can see, most of the problems are because of UI bugs, so you have to find a way to work around this bugs as I do not have time to wait for bugs to be fixed.  If the problems above were not there, then the onComplete was not needed in my case.

**Comment by supsup** [comment]
@webron  
It is nice to have a hook in to know when swaggerUi is done loading all it's dependencies.
I will know it's in the documentation state, if I want to inject things into the format I can.
Otherwise I have to poll the page looking for items that are injected.

**Comment by webron** [comment]
@1Map Both of those are features and not bugs. If you're already working on workarounds to fix those, why not contribute to the project in general and submit PRs to add those features, instead of waiting for us to fix them?

Just like any project, we have limited resources and we appreciate community contributions. One of the many benefits of this being an open source project.

**Comment by dunglas** [comment]
@webron We integrated Swagger UI 2 in @ApiPlatform to automatically load the full UI when an API URL is requested from a browser (`Accept` HTTP header set to HTML), then we run and display a JSON query from Swagger UI to the requested URL.

It was very easy to do with `onComplete`: https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/public/init-swagger-ui.js#L24-L43

It looks more complicated with the new version.

**Comment by dunglas** [comment]
For those interested by a similar feature, here is a somewhat working snippet:

```js
const op = document.getElementById('operations,get-/foos,Foo'); # This is mandatory because "operations,get-/foos,Foo" isn't a valid identifier according to the CSS spec
op.querySelector('div').click(); # Open the main div
op.querySelector('.try-out__btn').click(); # Open the sandbox mode
op.querySelector('.opblock-control__btn').click(); # Run the query
```

**Comment by heldersepu** [comment]
@webron 
Here is one more example use of the onComplete:
https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Core/SwaggerUi/CustomAssets/index.html#L79

I'm updating Swashbuckle to swagger 3.x and without onComplete we wont be able to inject customScripts as we did in 2.x

**Comment by dunglas** [comment]
Here is a more complete example using `MutationObserver` to control SwaggerUI programmatically: https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/public/init-swagger-ui.js#L30-L58

**Comment by jonnyry** [comment]
Is there any workaround for this?  Currently want to hook the "Try It" button with Javascript but the page hasn't finished loading when my Javascript runs.
