### ISSUE TITLE
multipart/form-data request payload shouldn't be url-encoded

### ISSUE THREAD

**Issue by NatalieBorovykh** [swagger-api/swagger-ui#3101]
**Steps:**
1. Navigate to http://editor.swagger.io
2. Paste the sample YAML from this file: [swagger.txt](https://github.com/swagger-api/swagger-ui/files/1010443/swagger.txt)
3. Execute the POST request (you can provide any file) and check the request payload:
![2017-05-18_1254](https://cloud.githubusercontent.com/assets/5817317/26196935/351248b4-3bc9-11e7-87a5-a35d76107214.png)

**Expected Result:**
JSON object passed in the "testJSON" parameter isn't url-encoded

**Actual Result**
JSON object is url-encoded

**Comment by ponelat** [comment]
@buunguyen do we encode the values _before_ we pass them to FormData?

**Comment by buunguyen** [comment]
We encode https://github.com/swagger-api/swagger-js/blob/master/src/http.js#L204.

Should we not do that?

**Comment by buunguyen** [comment]
fwiw, we also encode non-form data: https://github.com/swagger-api/swagger-js/blob/master/src/http.js#L208. Basically all values are encoded. I'm not sure of the rationale either.

**Comment by ponelat** [comment]
ok, so my understanding of formData is as follows...

- We should encode the key, and encode the value ( but not the `=` between them ). In application/x-www-form-urlencoded ( hence the urlencoded part :D ) 
- We should not encode _any_ value in multipart/form-data. Which makes sense since, a part of it could be file-data, which is sent in binary form.
- We should not encode any other body type

@buunguyen let me know if I missed something.

**Comment by ponelat** [comment]
The original issue isn't fixed. It might be possible that swagger-ui is doing its own encoding. @bodnia ? @buunguyen ?

Tested on 
```swaggerEditor: "3.0.10/gb2e3da6-dirty"
swaggerUi :"3.0.9/ga068f78"
```

**Comment by owenconti** [comment]
hey @ponelat, are you still able to reproduce this on http://editor.swagger.io/?

When following steps in the OP, this is my request payload:

```
------WebKitFormBoundaryYtjn5uQc7Kd5G9re
Content-Disposition: form-data; name="testJSON"

{ "name":"John", "age":31, "city":"New York" }
------WebKitFormBoundaryYtjn5uQc7Kd5G9re
Content-Disposition: form-data; name="testFile"; filename="swagger.txt"
Content-Type: text/plain


------WebKitFormBoundaryYtjn5uQc7Kd5G9re--
```

**Comment by ponelat** [comment]
Hey @owenconti!

yeah, that looks to be ok. Two issues I came across while verifying...
1. No indication, if you try to `Execute` without providing a file ( it should shake, or something )
2. The OP had a host for `smartbear.com`, which given the test endpoint shouldn't work but should show something... the result...
![image](https://user-images.githubusercontent.com/8438485/27640161-c0a7abc0-5c18-11e7-8381-ccb815a62955.png)
And
![image](https://user-images.githubusercontent.com/8438485/27640183-d117b8f6-5c18-11e7-9c7a-734df6cfe29b.png)

So this issue seems fixed. Will close it out.
The error message is likely similar to https://github.com/swagger-api/swagger-ui/issues/3072
The required file, we can track here.... https://github.com/swagger-api/swagger-ui/issues/3309
