### ISSUE TITLE
Unguarded expression in Models

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#3102]
Some expressions in Models are unguarded...
This sometimes affects downstream components, and happens while typing in the editor.

![image](https://cloud.githubusercontent.com/assets/8438485/26200490/ae167fb4-3bce-11e7-8f80-85a2652306bd.png)

sample spec...
```yaml
swagger: '2.0'
info:
  version: "1.0.0"
  description: Unguarded expressions
  title: Hello
host: example.com

paths: 
  /one:
    get:
      summary: ok
      description: ok
      responses:
        200:
          description: OK
    

definitions:
  Josh: true # <---- herein lies the issue.
    
```

Updating it after seems to throw some errors
![image](https://cloud.githubusercontent.com/assets/8438485/26200931/e5cacbac-3bd0-11e7-8dce-cee3a4d85442.png)

@shockey that should be picked up by the render try-catch? Or is that a little out of scope?

**Comment by shockey** [comment]
@ponelat, the global try/catch isn't getting this because the `Model` component is consumed without going through `getComponent`, which does the try/catch render protection (see [here](http://github.com/shockey/swagger-ui/blob/760d1eba802ed063d57ef79a5e2b426724176e29/src/core/components/model.jsx#L195) and [here](https://github.com/shockey/swagger-ui/blob/760d1eba802ed063d57ef79a5e2b426724176e29/src/core/components/model.jsx#L84).

You'd think, at first glance, that try/catching the root component would solve this for every component, but that isn't the case. Each component needs to have it.

We can fix this by just assigning `Model` to a getComponent call when it's used, even though it's in the same file. Even better, we could refactor `model.jsx`to have one component per file.

**Comment by shockey** [comment]
@ponelat, have you tried this with the editor? Does it break rendering until app reload, or just causes the one cycle to fail?

**Comment by ponelat** [comment]
It breaks the update flow ( ie: the UI doesn't update after that ).
Using: `Object {swaggerEditor: "3.0.10/gb2e3da6-dirty", swaggerUi: "3.0.9/ga068f78"}`
