### ISSUE TITLE
Create New Component

### ISSUE THREAD

**Issue by moserke** [swagger-api/swagger-ui#3194]
I am trying to create a new component that can be used to replace Topbar.  I am using the dist of swaggerui and then a SwaggerUIBundle in my html script.  But I can't figure out how to get a new component.  I can get Topbar to return null so as to not show, but not how to overwrite it.  Any help would be wildly appreciated.

**Comment by webron** [comment]
@moserke we're aware that our documentation is unfortunately lacking. Right now we have limited resources, and instead of just letting this question sit idly, I wanted to tell you that it might take us a bit of time to get back to you on this one. We'll try to give you at least some initial guidelines that would hopefully put you on track.

**Comment by moserke** [comment]
Yeah, even just some hints/pointers to get me started would be great.  What it feels like is I just don't have access to the React libraries in the minified "dist" version, is that true?  So I wouldn't be able to create new React components without carrying the full src around?

**Comment by webron** [comment]
You should be able to control everything by adding your own plugins (which can negate existing ones as well). @shockey could provide initial guidance, but as said, it might take a few days. Trying to set the expectations.

**Comment by shockey** [comment]
hi @moserke! 

i'll circle back on this when i have time, but until then, here's some previous discussions of customization that may be helpful: https://github.com/swagger-api/swagger-ui/issues/2813 https://github.com/swagger-api/swagger-ui/issues/3000 https://github.com/swagger-api/swagger-ui/issues/3103#issuecomment-302623899.

basically: in order to create a new component, you'll want a build system to spit out react components for you. you can either (a) use swagger-ui as a module in a react application that you build, or (b) clone our repo, make your changes in a new plugin you create, and use our build system to spit out new dist files.

the tickets i linked to cover both use cases. please read through what i linked and drop any questions you have here - i'll get back to you as soon as i can!

**Comment by shockey** [comment]
bumping this ticket - @moserke are you still seeking help with your topbar customization?

**Comment by moserke** [comment]
Sorry about that!  I should have responded.  What you pointed me helped me get over the hurdle.  My issue was that I didn't understand the need to build my own react app that needed to be built.  I was trying to just modify things from the compiled app.  Once you pointed that out as using swagger-ui as a module it all came together!!  From my perspective this can be closed.

**Comment by shockey** [comment]
awesome! glad to be of assistance.

thanks for using swagger!

**Comment by webron** [comment]
@moserke Going to take advantage of this, and say that this is your opportunity to help us as an open source project, time permitting of course. We're looking for help not just with PRs and code, but also with documentation - either in this repository or as blog posts on our website. If this is something you'd like to try, please hit us up!
