### ISSUE TITLE
Extending spec validator in 3.x

### ISSUE THREAD

**Issue by moon0326** [swagger-api/swagger-ui#3251]
Hi,

I'm trying to use Swagger spec with our own API gateway. We've defined additional data needed as 'x-requests' in each path. The only problem we have now is that there is no way to validate definition in 'x-requests'. I learned about "x-" prefix on https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/EXTENSIONS.md

Is there a way to let UI to validate definition in "x-" properties?

**Comment by webron** [comment]
The UI doesn't do validations. The UI uses the [Validator Badge](https://github.com/swagger-api/validator-badge/) to give you the small badge at the bottom of the page. Since it's an open source project, you can modify it further if you need.

The Editor has its own validation mechanism which is different.

**Comment by moon0326** [comment]
@webron Thank you Ron. I think I'm interested in how the editor validates and displays error message on the UI. Is there a way to extend that functionality? I want to display syntax error for the custom "x-" properties with my own definition.

**Comment by webron** [comment]
You can follow https://github.com/swagger-api/swagger-editor/issues/1351 for more information.

**Comment by moon0326** [comment]
@webron Thank you Ron, but that issue does not seem to have any more information than this ticket. I will follow that ticket instead since it was created earlier.
