### ISSUE TITLE
Unable to debug in production using source maps

### ISSUE THREAD

**Issue by scottohara** [swagger-api/swagger-ui#3263]
Perhaps this is just my misunderstanding of how webpack `cheap-module-source-map` is supposed to work, but:

1. Open http://petstore.swagger.io/ in Chrome (any Chrome version will do...I'm using v61)
2. Open DevTools, and go to the Sources panel
3. In the Sources list expand `Top`, then `webpack://`, and click on `swagger-ui-bundle.js`
4. In the panel where I presume the original (source mapped) code *should* appear, it is empty (see attached pic)

![image](https://user-images.githubusercontent.com/289327/27315623-f83d1c66-55bd-11e7-9ad3-81229503fb5c.png)

I can open the bundle and view the minified, bundled code; but there doesn't seem to be a way to view the original (source mapped) code.

![image](https://user-images.githubusercontent.com/289327/27315686-4b6699b2-55be-11e7-8737-302bf7dcd51a.png)

I've also tried Firefox & Safari, with no success.

Is this supposed to work?

**Comment by shockey** [comment]
I'm experiencing the same, not sure when this stopped working. It's been a while since I needed a sourcemap in a deployment.

Looks like Webpack is having some problems with sourcemaps: https://github.com/webpack/webpack/issues/3165

SurviveJS has a good primer on the Webpack side of sourcemaps: https://survivejs.com/webpack/building/source-maps/

I suspect there's some interaction between Webpack, Babel, and UglifyJS that's breaking the sourcemaps.

**Comment by scottohara** [comment]
Ah yes, there's this comment in the SurviveJS primer:

> cheap-module-source-map is currently broken if minification is used and this is a good reason to avoid the option for now.

...and links to here https://github.com/webpack/webpack/issues/4176.

So I suspect that may be the problem.

Maybe we should switch from `cheap-module-source-map` to the `source-map` option, as I believe that doesn't have this same issue (and provides better fidelity source maps anyway).

I'm happy to do the PR if you agree?

**Comment by shockey** [comment]
@scottohara Sure, any PRs around this would be much appreciated! Please test it locally first - I did a quick test of the change and wasn't having any luck.
