### ISSUE TITLE
Intention of locked vs unlocked for authorize-operation-btn?

### ISSUE THREAD

**Issue by dballance** [swagger-api/swagger-ui#3322]
Swagger UI version: 3.x

Images used to denote authorization seem backwards to me - can anyone shed some light on the intention here? As it is right now, they start unlocked and transition to locked after authorization. Makes more sense to me that they would begin locked and transition to unlocked after the user authorizes.  

Before authorizing
![image](https://user-images.githubusercontent.com/1234523/27750677-72a4ef00-5d9e-11e7-8408-a2e2c4471f6d.png)

After authorizing
![image](https://user-images.githubusercontent.com/1234523/27750709-9e2569de-5d9e-11e7-8181-d4999b35f68e.png)

Repro: 
1. http://petstore.swagger.io/
2. Notice Authorize button is "unlocked"
3. Notice all operations are unlocked
4. Click Authorize button
5. Provide "special-key" under Api Key Authorization
6. Authorize
7. Close and notice that some operations now have a "locked" icon / state.

Will go ahead and submit a PR and link.

**Comment by webron** [comment]
Maybe the lock itself is not the best icon, but the current implementation is as intended. It's open when you're unauthenticated, and closed when you've supplied the authentication details.

**Comment by dballance** [comment]
Okay - I do agree that they're not the best icon, but I also understand the intent better after some pondering. Will close this and remove the PR. Thanks!

@webron - Is there a gitter or something where swagger-ui team members hang out? I have a few questions about plugins. I've created several to customize the package and it's pretty straightforward - really more curious on how you guys envision packages delivered outside of core.

**Comment by webron** [comment]
@dballance we do not use gitter, but we're considering our options. If something opens up will make an announcement.

**Comment by alxgnon** [comment]
In my opinion it's more logical to have the lock closed and transparent when unauthenticated, and have the lock open and opaque after authorization. The current implementation is backwards to me.

I think we use real world objects as icons in user interfaces because we are familiar with them, and that helps us figure out how the interfaces function. I believe all people who have ever encountered a padlock expect a closed one to not let them in, and expect it to open with the right **key**, thereby giving them access to whatever it is locking.

I disagree that the lock is not the best icon. It is a great icon if used correctly. However, used how it is used currently, I think it's confusing.

**Comment by HamedSiasi** [comment]
any progress on this matter?
obviously the lock should be close before authentication and open after it ...

**Comment by jcramalho** [comment]
I have the same opinion and I am struggling with customers for them to accept this reversed logic representation... You should change it: closed=unauthorized; open=authorized

**Comment by KukoCL** [comment]
These icons are telling us that we are not allowed to acces to something that has an open lock on it, and that we have access to something that has a closed lock.

This is still backwards.

**Comment by jackysupit** [comment]
May be it was a mistyped, and then it became a feature #programmersjoke  :)))
