### ISSUE TITLE
Rendering swagger UI is extremely slow

### ISSUE THREAD

**Issue by gingters** [swagger-api/swagger-ui#3365]
With the given swagger file, which is auto generated by Swashbuckle, the swagger UI needs about 2 to 3 minutes to show the API documentation.

The swagger file is delivered in about 300ms, and after that the browser stalls and waits for about 2 to 3 minutes. Chrome issues a warning: `[Violation] 'readystatechange' handler took 160649ms`.

We cannot update to a newer swagger ui as we use swashbuckle that includes swagger ui for our .NET api.
Is there a problem with the generated swagger file which we could fix, or is this a problem in swagger UI itself?

When reporting an issue, please provide the following details:
- swagger-ui version 2.2.10
- a swagger file reproducing the issue  [swaggerfile.json.txt](https://github.com/swagger-api/swagger-ui/files/1138648/swaggerfile.json.txt)

**Comment by webron** [comment]
Try using the latest swagger-ui, seems to render a lot faster.

**Comment by gingters** [comment]
Thanks for that idea, but as already stated in the issue, we need to use Swashbuckle.Swagger in our .NET api project which bundles swagger ui 2.2.10 and there is no other version with a newer swagger-ui available. So updating to swagger ui 2 is not possible.

If that is an issue with 2.2.10 we would need a fix for that so that swashbuckle can upgrade to that, or if that is an issue with the generated swagger file, I need to try to resolve that, but I have no clue how I could test that out.

**Comment by webron** [comment]
It's not an idea, it's the solution. There are performance issues in swagger-ui 2.x and it is no longer under development, so you can't expect further performance improvements in it.

The fact that Swashbuckle bundles swagger-ui 2.x doesn't mean you can't bundle swagger-ui 3.x in your app and use it instead.

**Comment by shockey** [comment]
The Swashbuckle folks are discussing moving to Swagger-UI 3.x here: https://github.com/domaindrivendev/Swashbuckle/issues/1064

@gingters, the Swagger-UI 3.x series is quicker because it's a complete rewrite using different technologies - so there's no way we could possibly port our performance changes to the 2.x series. For what it's worth, I loaded your spec into Swagger-UI 3.0.18 and it loaded in about three seconds.

The Swashbuckle team is looking for maintainers, by the way - consider pitching in over there if you have the time 😄 

---

I'm closing this since there's nothing actionable here for current versions of Swagger-UI.
