### ISSUE TITLE
Tags - externalDocs field not displayed (Version 3.0.19)

### ISSUE THREAD

**Issue by PhilippeChab** [swagger-api/swagger-ui#3397]
Hi!

I wanted to add hyperlinks to my tags, so I added an externalDocs field to their configuration. Since nothing was displayed, I thought I did something wrong but the externalDocs fields of the Swagger Petstore example are not displayed either. Is it a bug or simply not supported by Swagger-UI? 

Thank you!

**Comment by shockey** [comment]
> Is it a bug or simply not supported by Swagger-UI?

IMO, the fact that it's not supported is a bug 😄

**Comment by shockey** [comment]
@Minasokoni, thoughts on how to style external docs for tags?

**Comment by Ohems** [comment]
It'd be nice if this matter proceeded. My personal suggestion is to align the external document links (description) to the right side of the tag bar, left of the arrow. This means that the tag description and externalDoc description would share the same line which can become a problem, but neither description is apparently supposed to be very long. What exactly happens when they overlap would be up to you.

**Comment by shockey** [comment]
This is fixed - thanks for the request @PhilippeChab!

**Comment by PhilippeChab** [comment]
Thanks to you, Shockey! I'll try it out.
