### ISSUE TITLE
Unable to use parameter `?urls=...` as url query string (`url` parameter works)

### ISSUE THREAD

**Issue by laguiz** [swagger-api/swagger-ui#3415]
Summary : I'm not able to make `?urls=` work via Query Strings with these versions 3.0.18 (dist folder), 3.0.19 (dist folder) and online pet store demo

### `?url`

Looks to work very well

`http://petstore.swagger.io/?url=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml` Ok load the `yaml` file properly

`http://petstore.swagger.io/?url=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore.json` Ok load the `json` file properly

### `?urls`

I'm not able to make it work (tried with 3.0.18, 3.0.19 and online pet store demo)

Here are the links I tried (via Chrome) : 

Not encoded
`http://petstore.swagger.io/?urls=[{name:"A",url:"https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml"}]`

Partially encoded json :
`http://petstore.swagger.io/?urls=[{name:%22A%22,url:%22https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml%22}]`

Fully encoded param
`http://petstore.swagger.io/?urls=%5B%7Bname%3A%22A%22%2Curl%3A%22https%3A%2F%2Fraw.githubusercontent.com%2FOAI%2FOpenAPI-Specification%2Fmaster%2Fexamples%2Fv2.0%2Fyaml%2Fpetstore.json%22%7D%5D`

## JS Error looks like this and a white html page is displayed on screen

![image](https://user-images.githubusercontent.com/550822/28357670-7f7331d8-6c6c-11e7-9369-850f617661e6.png)

## Question
Did I miss something? Maybe it's not possible to do it via Query String. It's not clear if parameters mentioned on README `https://github.com/swagger-api/swagger-ui/blob/master/README.md#parameters` are all supported via URL query string params.

Keep very good work and let me know if I can help here.

**Comment by shockey** [comment]
So, this is a current limitation of the query string config system - we're not actually parsing the values at the moment, just [mapping the raw values from the query string directly to config keys](https://github.com/swagger-api/swagger-ui/blob/master/src/core/utils.js#L558), so everything ends up being a string.

There's some discussion of this in https://github.com/swagger-api/swagger-ui/issues/3302 - that issue is about boolean values in query strings, but the same idea applies to JSON values (and both could be solved by using `JSON.parse()`, I imagine).

We'd be happy to review a pull request that fixes this if you have the time to help out 😄

**Comment by laguiz** [comment]
@shockey Thank you for your quick feedback. I will look closer to the source code and see if I can find some time to help.

**Comment by shockey** [comment]
Closing this in favor of #3302. Thanks for the report, @laguiz!
