### ISSUE TITLE
Environment variables aren't helpful in docker

### ISSUE THREAD

**Issue by Codealist** [swagger-api/swagger-ui#3467]
- swagger-ui version: master branch
- a swagger file reproducing the issue: `docker-run.sh, dist/index.html`

I wonder how to setup a dockerized version with oauth. It seems that entrypoint does nothing when the following is running:
```
replace_in_index myApiKeyXXXX123456789 $API_KEY
replace_or_delete_in_index your-client-id $OAUTH_CLIENT_ID
replace_or_delete_in_index your-client-secret-if-required $OAUTH_CLIENT_SECRET
replace_or_delete_in_index your-realms $OAUTH_REALM
replace_or_delete_in_index your-app-name $OAUTH_APP_NAME
if [ "$OAUTH_ADDITIONAL_PARAMS" != "**None**" ]; then
    replace_in_index "additionalQueryStringParams: {}" "additionalQueryStringParams: {$OAUTH_ADDITIONAL_PARAMS}"
fi
```

Because we don't have such placeholders in `dist/index.html` anymore.
However, there is a file `dev-helpers/index.html` with ones.

Is it an issue or i miss something ?

**Comment by vanbalken** [comment]
I'm having the same issue. Passing oath enviroment variables to the swagger-ui docker container doesn't has any effect because the placeholders in `dist/index.html` are missing since version 3.0.0.

Are there any reasons why the following isn't included in `dist/index.html`:
```
  ui.initOAuth({
    clientId: "your-client-id",
    clientSecret: "your-client-secret-if-required",
    realm: "your-realms",
    appName: "your-app-name",
    scopeSeparator: " ",
    additionalQueryStringParams: {}
  })
```

How can I add this and provide it as a pullrequest? Because `CONTRIBUTING.md` says: "**Don't** include any changes to files in the `dist/` directory"

**Comment by webron** [comment]
It looks like we didn't update the Dockerfile properly when moving to 3.X. 

The solution to bring back the support for OAuth config would not be to modify the index.html but rather the docker-run.sh script, which would end up adding what's needed and modify something existing.

**Comment by iancward** [comment]
Any updates on this?

**Comment by ithr0n** [comment]
Still no update?
