### ISSUE TITLE
Is it possible to have a Username and password prompt for anyone who access the swagger page 

### ISSUE THREAD

**Issue by shivanka-thunderbolt** [swagger-api/swagger-ui#3515]
I'm using Swashbuckle 5.6.0 to configure swagger to WEB API 2 project. would appreciate if someone can guide me options to allow only those who should access swagger  page.

**Comment by shockey** [comment]
[HTTP Basic auth](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#Basic_authentication_scheme) should serve your needs well.

I'm closing this now because it's out of scope for the swagger-ui project. StackOverflow would be a better place to ask general web application questions like this.

Cheers!
