### ISSUE TITLE
Swagger 3 adds "origin" header to requests - how can I omit it?

### ISSUE THREAD

**Issue by dankirkd** [swagger-api/swagger-ui#3573]
A call to a simple GET endpoint with Swagger 2 produces the following request headers:

```
Host: myhost.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://myhost.com/myapp/resources/swagger2/
```

The same call through Swagger 3 adds an "origin" header that we don't want:

```
Host: myhost.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
origin: https://myhost.com
Referer: https://myhost.com/myapp/resources/swagger3/
```

I cannot figure out what causes this to be added, and how to have it not included.

**Comment by dankirkd** [comment]
This appears to only happen using Firefox.  It does not happen using Chrome or Safari.  But again, it is only happening for Swagger 3 and not Swagger 2.

**Comment by shockey** [comment]
By "Swagger 2" and "Swagger 3", do you mean Swagger-UI or the Swagger/OpenAPI specification?

**Comment by dankirkd** [comment]
I mean the Swagger UI.  Sorry if that was ambiguous.

**Comment by shockey** [comment]
Ah, got it. No worries - but for future reference, there wouldn't have been a miscommunication if you had used our default issue template :wink:

The `Origin` header is a byproduct of the new Fetch API, which is a lower-level browser API that we started using in v3 of the JS tools (instead of good old XMLHttpRequest). The header is used to reliably indicate what host a browser request is coming from.

Per the [fetch WHATWG spec](https://fetch.spec.whatwg.org/#origin-header):

> The `Origin` header ...  is used for all HTTP fetches whose CORS flag is set as well as those where request’s method is neither `GET` nor `HEAD`.

Here's some further discussion of this header within WHATWG, if you'd like to get familiar with why they chose this path: https://github.com/whatwg/fetch/issues/91 & https://github.com/whatwg/fetch/issues/225.

The specification discussion gets pretty dense, but basically the Origin header is always set for any HTTP method that is used for processing user input (that is, not `GET` or `HEAD`), with an eye towards preventing CSRF attacks.

---

What _is_ strange to me is that you're experiencing this with a GET request.

Some questions for you:
- You mention that your UI instance and live API are on the same host - are you sure they're on the [same origin](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) (scheme + host + path)?
- Was the `origin` header lowercased in the request, or was that a typo?

It could be that this is a Fetch implementation bug within Firefox, but a cursory search for a bug like this didn't turn up anything.

**Comment by dankirkd** [comment]
Yes, Swagger and the API are at the exact same origin (scheme + host + path), and the header is lowercase, that is not a typo.  However, if I edit the request header to be "Origin" and resend I still get a 403.

But I am concerned by another part of your answer that suggests that this could be an issue for POSTs, PUTs and DELETEs (although we don't have a CORS flag set that I know of).  We could just declare that Swagger UI 3.x just won't work with Firefox, but that sounds like an unsatisfactory outcome.

**Comment by shockey** [comment]
> Yes, Swagger and the API are at the exact same origin (scheme + host + path)

Is your Swagger document on the same origin as Swagger-UI and your API server as well? Just checking all the bases here.

> the header is lowercase, that is not a typo

This seems a little fishy to me - if the browser is attaching this header, I'd expect it to be `Origin`, not `origin`, since it's `Origin` in the specification.

> we don't have a CORS flag set that I know of

This would actually be on our side - we built up a request [here in `swagger-client`](https://github.com/swagger-api/swagger-js/blob/master/src/execute.js#L74), but there's no `mode` option set ([see the Request constructor docs](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode) for info).

Notably, those docs mention the default mode for Chrome:

> > mode: The mode you want to use for the request, e.g., cors, no-cors, same-origin, or navigate. The default is cors. In Chrome the default is no-cors before Chrome 47 and same-origin starting with Chrome 47.

Firefox's is `no-cors` (as of 2015...):

> > The Request’s mode is used to determine if cross-origin requests lead to valid responses, and which properties on the response are readable. Legal mode values are "same-origin", "no-cors" (default) and "cors".
> 
> > https://hacks.mozilla.org/2015/03/this-api-is-so-fetching/

I will say at this point that the cross-browser defaults for this are sounding pretty nutty.

---

> if I edit the request header to be "Origin" and resend I still get a 403.
> ...
> We could just declare that Swagger UI 3.x just won't work with Firefox

This seems heavy-handed. Is your API very picky about which headers are coming in with a request?

**Comment by shockey** [comment]
Also, I feel that we're getting a bit into the weeds here. Can you provide me with an API definition that's giving you problems (preferably one set up against the live server that's giving you trouble)? It would definitely help if I could see what's going on.

**Comment by dankirkd** [comment]
> Is your Swagger document on the same origin as Swagger-UI and your API server as well? Just checking all the bases here.

Yes, the JSON file is also at the same origin.

> Is your API very picky about which headers are coming in with a request?

Not that I know of.  We require certain headers, but we don't restrict them.  We are running on Tomcat on AWS.

When you ask for API definition, can you indicate in what format you're seeking that in?

**Comment by shockey** [comment]
Sure, I'm referring to the JSON or YAML file that you're loading into Swagger-UI. If the file is publicly accessible, a URL to the file will work!

If you'd prefer to not share the file/URL publicly, I can provide you with my email address.

**Comment by dankirkd** [comment]
I'm not going to be able to share that I'm afraid due to it being a non-public API, but if there are particular parts of it that you think are of interest I can try and obfuscate those enough to provide you with something useful.

**Comment by webron** [comment]
Pretty much anything that would reliably allow us to reproduce the issue would work.

**Comment by dankirkd** [comment]
Here's the essential spec: 
```{
  "swagger" : "2.0",
  "info" : {
    "version" : "v1",
    "title" : "API Reference"
  },
  "basePath" : "/epc",
  "tags" : [ {
    "name" : "Status API"
  } ],
  "paths" : {
    "/service-status" : {
      "get" : {
        "tags" : [ "Status API" ],
        "summary" : "Service status",
        "operationId" : "getServiceStatus",
        "responses" : {
          "200" : {
            "description" : "Request completed with no errors.",
            "schema" : {
              "$ref" : "#/definitions/ServiceStatus"
            }
          },
          "400" : {
            "description" : "Error of some kind."
          }
        }
      }
    }
  },
  "definitions" : {
    "ServiceStatus" : {
      "type" : "object",
      "properties" : {
        "state" : {
          "type" : "string",
          "enum" : [ "HEALTHY", "WARN", "FATAL" ]
        },
        "schema" : {
          "type" : "string"
        },
        "stateString" : {
          "type" : "string"
        }
      }
    }
  }
}
```

**Comment by shockey** [comment]
Thanks, I was able to reproduce an Origin header in a request based on that spec.

I'm still not clear on why this header is causing trouble for you, though. Is your API server not able to tolerate the header being present?

**Comment by dankirkd** [comment]
Apparently not.  I don't know why though.

**Comment by webron** [comment]
@shockey the real wonder is why the behavior is different between the different browsers.

fyi - headers are case insensitive. `origin`, `Origin`, `ORIGIN`, `oRiGin` are all the same. I prefer the last variant.

**Comment by shockey** [comment]
@webron, yeah, that seems strange to me. I would have thought that fetch would be pretty consistent across browsers by now.

You're right, they're not case sensitive - but I would _think_ that a browser implementation would follow the PascalCase convention for HTTP headers. The lower case made me think that it was a third-party library injecting the header, but so far I can tell that it's not our code (could be a library we use, though).

**Comment by dankirkd** [comment]
So are you able to reproduce the finding that FF is adding the header while Safari and Chrome do not?

**Comment by shockey** [comment]
@dankirkd, correct.

Firefox 55 + macOS Sierra:

![image](https://user-images.githubusercontent.com/680248/29338638-f21fecbc-81ca-11e7-9bbe-aeb3af60584a.png)

Chrome 60 + macOS Sierra:

![image](https://user-images.githubusercontent.com/680248/29338644-f9f0cd80-81ca-11e7-9b63-8b89c10126d7.png)

Note that I had to host the spec on the same origin as my UI in order to correctly reproduce it.

**Comment by shockey** [comment]
Also, Safari 10:

![image](https://user-images.githubusercontent.com/680248/29338746-8e9ab432-81cb-11e7-9c9a-1a6fb99b8fcc.png)

I'm still of the mind that your server should be more tolerant towards browser-controlled HTTP headers 😄

**Comment by dankirkd** [comment]
I should also point out that running on localhost I don't have the problem, even though the "origin" header is being sent:

```
Host: localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
origin: http://localhost:8080
Referer: http://localhost:8080/myapp/resources/swagger3/
Cookie: Idea-d9998cbb=2b382610-6497-4ccb-9467-77bc0608f6ff
Connection: keep-alive
```

**Comment by dankirkd** [comment]
One other difference: locally we are not running within a Docker container.  On the AWS servers we are.

**Comment by webron** [comment]
If you're running on the same host but a different port - that would trigger cors interaction.

Also, if your app is working as expected locally but not on aws - that seems like something you'd need to solve in your app.

**Comment by dankirkd** [comment]
We're running on the same port.

I would agree with you regarding the problem being the app if the problem not a function of the browser.  I've also seen that localhost is often treated differently, so perhaps something like that is why it works.

Back to one of my original questions: is there a way to override the behavior so that "origin" headers are not part of any request?

**Comment by shockey** [comment]
I don't think it's possible for any web application to override that header.

Per MDN, [`Origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) is a forbidden header name, which is defined as:

> an HTTP header name that cannot be modified programmatically
>
> https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

If you're having serious trouble diagnosing this server-side, a workaround could be to install an extension that lets you intercept and mutate the request before it goes out, stripping the Origin header.

**Comment by shockey** [comment]
Closing since this has been inactive, and there doesn't seem to be anything actionable here.

Feel free to reply with any further thoughts, and we'll reopen this!
