### ISSUE TITLE
Tag list strange rendering when endpoint has 2 tags

### ISSUE THREAD

**Issue by kirkins** [swagger-api/swagger-ui#3582]
When I use 2 tags on a single endpoint the UI changes. It looks like a bug to me but it's possible that this is the intended behaviour:

Here is a screenshot of my tags when only using a single tag on each end-point:

![untitled](https://user-images.githubusercontent.com/9503662/29369048-72ccb9e0-826f-11e7-81a1-7be0dec85c7b.png)

Here is what it looks like when I have 2 tags on an end-point:

![untitled](https://user-images.githubusercontent.com/9503662/29369090-975ff3c6-826f-11e7-87c4-413132429bd3.png)

```
      tags: 
        - Camera
        - Recording
```
Is this intended or a bug?

**Comment by shockey** [comment]
It looks like you're using Swagger-UI 2.x, which is not under development anymore - but I'm not sure, since you opted to not provide the information we ask for in our template for all new issues 😕

If you are on 2.x, consider migrating to the 3.x series. As far as I know, this issue is not present in the new version, which is a complete rewrite of the project.

I'm closing this due to lack of information, but if you're on 3.x, bump this thread - this will be considered a valid bug. 

Thanks for reaching out!

**Comment by kirkins** [comment]
Ok it is 2.0 so I will leave it closed
