### ISSUE TITLE
Seeing "fetching resource list" and no API

### ISSUE THREAD

**Issue by boriss2013** [swagger-api/swagger-ui#361]
Hi
I'm running a Tomcat with SSL support
After installing the SwaggerUI version from "dist" and starting the server, I'm receiving the following results:
https://localhost:8443/myapp/dist/index.html
loads and tries to load the API for http://petstore.swagger.wordnik.com/api/api-docs
I see a message fetching resource list: http://petstore.swagger.wordnik.com/api/api-docs
and nothing happens. No API is displayed.
Same goes when I try to display my own API (which works using a forked version of SwaggerUI from here: https://github.com/martypitt/swagger-springmvc-example  )
What do I need to do in order to allow the mainstream SwaggerUI to work on Tomcat over SSL ?
Thanks in advance

**Comment by neumond** [comment]
Happens if I use api_key security definition with `in: query`.

First, I open swagger ui and it works well. Then I press "Authorize", enter my apikey and it starts to reload definitions. It fetches them all, as usually does, but with api_key GET parameter appended (I can see this in server log). Then API should appear, but nothing happens: no messages in browser console, no api shown, just seeing "fetching resource list". GET parameter doesn't affect jsons on my server, so we are getting absolutely same swagger scheme, which worked before authorization attempt.

**Comment by webron** [comment]
@neumond please try the latest release and latest master. If you still encounter an issue, open a new ticket.
