### ISSUE TITLE
Swagger UI render error with no detail

### ISSUE THREAD

**Issue by erajkovic** [swagger-api/swagger-ui#3615]
While testing the latest version of swagger UI (guessing it's v3.1.7 from github current master) I found an issue with our external swagger file: https://apicatalog.oraclecloud.com/api-docs/all-apicatalog-service.json

UI contains only "Failed to load spec." while the bottom icon let me believe the swagger is valid - seeing the green OK ui element.

Link I used - http://petstore.swagger.io/?input=https://apicatalog.oraclecloud.com/api-docs/all-apicatalog-service.json# - did not find the syntax to make it the default URL.
 
our version: v2.2.10 
live link: https://apicatalog.oraclecloud.com/api-docs/

| Bug or feature request?         |  not sure if this is expected behavior and we should explain better why it's failing to read remote file or if it should just works, as before.
| Which Swagger/OpenAPI version?  | v2.0
| Which Swagger-UI version?       | v3.1.7
| How did you install Swagger-UI? | used public version
| Which browser & version?        | chrome Version 60.0.3112.101 (Official Build) (64-bit)
| Which operating system?         | Mac OS-X

From the developer console window, I guess I have found the root cause - would be nice to have some link or other kind of message rendered to the user if this is the expected behavior.

Fetch API cannot load https://apicatalog.oraclecloud.com/api-docs/all-apicatalog-service.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://petstore.swagger.io' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Expected Behavior
render the document content, as we used to do with previous releases.

### Current Behavior
display a generic message "Failed to load spec." with a red color URL, which let me think there is a problem inside the linked swagger spec.

**Comment by shockey** [comment]
> Fetch API cannot load https://apicatalog.oraclecloud.com/api-docs/all-apicatalog-service.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://petstore.swagger.io' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

This is a CORS error 😄 CORS is a security mechanism built into all browsers which limits a website's ability to make requests to different hosts.

In order to allow the browser to get your spec from your server, you need to set some CORS headers. Here's a good resource: https://enable-cors.org

That being said, it looks like these headers are set on your server now.

---

> Link I used - http://petstore.swagger.io/?input=https://apicatalog.oraclecloud.com/api-docs/all-apicatalog-service.json# - did not find the syntax to make it the default URL.

Try using http://petstore.swagger.io/?url=https://apicatalog.oraclecloud.com/api-docs/all-apicatalog-service.json instead. This config option, along with many others, are documented in our README: https://github.com/swagger-api/swagger-ui#parameters.

---

> From the developer console window, I guess I have found the root cause - would be nice to have some link or other kind of message rendered to the user if this is the expected behavior.

This is fair - CORS errors are a bit hard to catch, but we could definitely do a better job of communicating exactly what went wrong.

**Comment by erajkovic** [comment]
Working fine now - thanks for pointing me at the readme for the 'url' parameter.
