### ISSUE TITLE
Calling an endpoint which returns file does not download content

### ISSUE THREAD

**Issue by seanch87** [swagger-api/swagger-ui#374]
When calling an endpoint that has a response with Content-Disposition attachment or a Content-Type such as application/zip, swagger will only show the bytes in the response,  instead of a download prompt from the browser.

**Comment by tartakynov** [comment]
+1

**Comment by brokensandals** [comment]
@fehguy thanks for your advice. I was able to get a hacky implementation working, but there are a couple obstacles to doing a clean implementation in swagger-ui:

* The only way to do binary downloads in jQuery is to write a custom transport. You more or less have to copy/paste the default transport (about 150 lines) straight out of jQuery and modify it - I couldn't find any way to just inject the extra functionality into the existing transport at runtime. (Someone did [wrap a binary transport into a plugin](https://github.com/henrya/js-jquery/tree/master/BinaryTransport) but it doesn't look like it retains all the functionality of the default transport.)
* When constructing its own response object, swagger-js only uses the `responseText` field from the jQuery response object. If the custom transport uses some custom field to store the binary response, swagger-js needs to be modified to copy that forward. On the other hand, if the custom transport stores the binary response in the responseText field (doesn't seem like a great idea), swagger-js needs to be modified to not try to call JSON.parse on it since it won't be a string.

So this feature seems to require modifying swagger-js; I see a couple options:

1) include a custom transport in swagger-js and add a field to the response object to contain the blob response
2) support some options in swagger-js so that consumers can plug in their own custom transport and get additional fields copied to the response object

**Comment by fehguy** [comment]
Hi @brokensandals got it.  Did you look at newer versions of JQuery?

I'd love to move this logic all into swagger-js.  The shred http client has a pretty low-level functionality to it, and we can probably work in the code somehow.  Can you share the changes you made to jQuery in a gist so I can see?

**Comment by brokensandals** [comment]
> Did you look at newer versions of JQuery?

I've mostly looked at 1.8.0 and 1.9.1 so far, though based on jquery/jquery#1525 it doesn't sound like the situation has really changed.

> Can you share the changes you made to jQuery in a gist so I can see?

Here's the custom transport: https://github.com/brokensandals/swagger-ui/commit/fab1bfe336f2e3d74cdc848d18649feeac6e6e06#diff-4

This gist shows the diff of that with the jQuery file it's based on: https://gist.github.com/brokensandals/be6911a3f7d06f93b15d (the xhrOnUnloadAbort stuff isn't relevant). Basically it just has to set the response type on the XHR, avoid calling xhr.responseText (which would trigger errors), and copy the xhr response into the responses object. See e.g. [this blog post](http://www.henryalgus.com/reading-binary-files-using-jquery-ajax/).

The rest of the commit above (which is a little noisy since I regenerated the dist files) shows how it can be used: the jQuery ajax options must set `dataType` to route to the transport and `responseFields` to ensure the blob field is copied into the jQuery response object.

**Comment by tarikbenmerar** [comment]
@brokensandals I have create a plugin that resolves this issue as you said in the comment there won't be support in jQuery any soon. The plugin here : https://github.com/acigna/jquery-ajax-native/. Good luck, hope you find it very useful.

**Comment by fehguy** [comment]
Thank you @tarikbenmerar !  Have you ever integrated it with swagger-ui?  I'll look into this in the next few days.

**Comment by tarikbenmerar** [comment]
@fehguy no, I have came here because someone has referenced the issue jquery/jquery#1525.

**Comment by calfzhou** [comment]
+1

**Comment by mohsen1** [comment]
https://github.com/swagger-api/swagger-ui/pull/1079

**Comment by hamx0r** [comment]
Looking at the code in this pull within OperationView.js, it looks like contenType is first tested for specific types, then eventually assumed to be a generic  file download (line 606-).  However, when running the respective develop-2.0 branch, Chrome's Developer Tools console shows `Uncaught TypeError: Cannot read property 'test' of undefined` in swagger-ui.js:21394 (same lines of code mentioned in OperationView.js).   The progress animation runs forever.

The Content-Disposition in my response is `attachment; filename=file.zip` and the response is a valid ZIP.  Perhasp the `filename=file.zip` part is messing up the test?    The relevant parts of the Swagger Spec feeding the UI are:

```
		"/flights/csv/{flight_id}": {
			"parameters": [{
				"required": true,
				"type": "string",
				"name": "flight_id",
				"in": "path"
			}],
			"get": {
				"tags": ["flights"],
				"summary": "\n        Return CSV of flights, one for each flight \"id\" (a CSV list of id's is acceptable)\n        ",
				"responses": {
					"200": {
						"type": "file",
						"description": "CSV ZIP File"
					}, ...
				},
				"parameters": [{
					"name": "flight_id",
					"required": true,
					"in": "path",
					"type": "string",
					"description": "CSV list of flight IDs"
				},
```

The [Swagger 2.0 Spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#data-types) says to use the `type` of `file` for files instead of a `schema` - not sure if my syntax is wrong there because the Swagger Editor says that `type` is not allowed here.  

What's the expected Swagger JSON syntax and Header fields in order to allow file downloads?

**Comment by webron** [comment]
@hamx0r - can't comment in the behavior you experience, but spec-wise, it does say to use `type` *instead* of `schema` but rather your `schema` can have the `"type": "file"` where elsewhere it is not permitted.

So response part is not a valid spec. It should be:
```js
				"responses": {
					"200": {
						"schema": {
							"type": "file"
						},
						"description": "CSV ZIP File"
					}, ...
				}
```

FWIW, it's normally better to open new issues on rather than comment on closed ones if more than a few days have past. It's true that we get email notifications but it's easy to miss a few in the load and we can't follow comments on closed issues otherwise. You can always refer to a closed issue by using the reference number.
