### ISSUE TITLE
Errors showing when nulls present in the swagger.json

### ISSUE THREAD

**Issue by heldersepu** [swagger-api/swagger-ui#3789]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | Latest
| Which Swagger-UI version?       | Latest
| How did you install Swagger-UI? | Via Swagger-Net
| Which browser & version?        | Chrome
| Which operating system?         | Win10

### Demonstration 

http://nhc-noaa.azurewebsites.net/swagger/ui/index?url=http://nhc-noaa.azurewebsites.net/docWnulls.json

### Expected Behavior
There should not be errors 

### Current Behavior
There are errors

### Context
I've never encountered that issue before, all my swagger.json have no nulls. 
but someone raised [that issue](https://github.com/domaindrivendev/Swashbuckle/issues/1187) and I was able to reproduce it.

**Comment by webron** [comment]
They raised that issue because I asked them to. `null` is not a valid value making the API definition invalid, and yes, that might end up breaking the UI. Closing as `won't fix`.

**Comment by heldersepu** [comment]
@webron 
I'm curious... why is ```null``` invalid?
according to [the json specs](http://www.json.org/) null is a valid value.
> A value can be a string in double quotes, or a number, or true or false or null, or an object or an array. These structures can be nested.

I will definitely try to help them, but if they can not provide a

**Comment by webron** [comment]
Oh, it's valid in JSON, it's not valid in OpenAPI. In 2.0, the only fields that can have a `null` value are extensions. In 3.0.0, they are also supported in examples. 

If you look at the OpenAPI spec, you'll see that each field specifies the type that's allowed for it. It can either exist with that type as a value, or not exist at all (unless it's required, meaning you have to provide a value with that type).

Even when the type is `Any`, it doesn't include `null` because that's not a valid data type as defined in the data type section. The only place where it would be allowed is where it explicitly says so.

**Comment by heldersepu** [comment]
Thanks, and from a size point of vie it makes a lot of sense! 
with the nulls the file is 1213KB after cleaning it goes down to just 212KB

**Comment by webron** [comment]
Yup, that's a tiny improvement ;) (which is why I never recommend sending `null`s over the wire unless they have a meaning). If it makes you feel any better, we had a similar issue in swagger-core a few years back and had to solve it there as well. It was just a matter of telling the serializer to not serialize null fields.

**Comment by heldersepu** [comment]
Ye, I think that is where the problem is, they probably using a custom serializer...
but they have not provided a minimal project reproducing the issue, without that troubleshooting is very difficult.

Thanks again
