### ISSUE TITLE
multipart/form-data using Swagger-UI with Petstore Image Upload API

### ISSUE THREAD

**Issue by stevendearborn** [swagger-api/swagger-ui#3806]
I searched all of the open issues and I did not see this one, however I would assume that the Petstore APIs work with Swagger UI.
![screen shot 2017-10-23 at 4 35 41 pm](https://user-images.githubusercontent.com/6518685/31911938-46409168-b810-11e7-9df0-d15c4d4cee71.png)

The curl command [within Swagger UI] does not generate the --form/-F arguments for the multipart/form-data parameters, however the Jersey2 example that is generated [by Swagger Codegen] works correctly when I perform curl with the correct arguments on the command line.

I tested with the [latest] online version of Swagger UI and got similar result.

I used SwaggerUI in both FireFox and Safari web browsers.

**Comment by stevendearborn** [comment]
This is the curl command:
curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' -F additionalMetadata=comment%3D%27so%20cute%27  -F file=@Users/stevendearborn/pictures/Scan.jpeg 'http://localhost:8080/v2/pet/3/uploadImage' --trace-ascii /dev/stdout

**Comment by stevendearborn** [comment]
Here is the result in Firefox: closer to expected, however the path to the file is omitted.
![screen shot 2017-10-23 at 4 40 40 pm](https://user-images.githubusercontent.com/6518685/31912161-086ac718-b811-11e7-8ac1-18947081cfde.png)

**Comment by webron** [comment]
The lack of `-F` seems specific to Safari. It works well on Chrome and Firefox.

Not sure we can get the full path, but can't really consider that a big issue.

**Comment by stevendearborn** [comment]
I will implement a default implementation that reads the binary file input and see if that works [from Swagger UI not curl].  I suspect it will.

**Comment by shockey** [comment]
I spent some time on this tonight, and haven't been able to get to the bottom of it yet - I believe it has something to do with the File web API implementation between browsers.

Our curlify function is getting these body values:  `{file: File}` in Chrome and `{}` in Safari. Since it's getting bad data at that layer, I wouldn't expect it to work.

**Comment by shockey** [comment]
Okay, found what's wrong! Buckle up, it's a fun one.

The execute code fires the `setRequest` action right before the actual request firing, in order to save the request we're going to fire so we can look at it later. This leads us to the reducer for that action:

https://github.com/swagger-api/swagger-ui/blob/8dab91f184103be794ae2fcfeb67b02126730e88/src/core/plugins/spec/reducers.js#L102-L104

Later, the Curl component is given the same piece of state that `SET_REQUEST` set above, as the request to construct a cURL command for:

https://github.com/swagger-api/swagger-ui/blob/c6a664302a1336c4c3a3891922c2dcdb90a710e0/src/core/components/live-response.jsx#L43

https://github.com/swagger-api/swagger-ui/blob/c6a664302a1336c4c3a3891922c2dcdb90a710e0/src/core/components/live-response.jsx#L63

As I mentioned before, in Chrome the request coming into Curl has the File object included, as we would expect - but in Safari, it's simply missing.

Upon further investigation, I noticed that the resulting state from the `SET_REQUEST` reducer was the point at which the browsers diverged in functionality - the File was never making it into state at all in Safari.

It turns out that the call to `fromJSOrdered` in the `SET_REQUEST` reducer was the problem:

https://github.com/swagger-api/swagger-ui/blob/8dab91f184103be794ae2fcfeb67b02126730e88/src/core/utils.js#L54-L65

The second conditional in that function is an exception that returns File objects as we recurse through our original object and convert to Immutable data scructures. In Chrome, we hit this conditional - in Safari, we do not.

Ultimately, the way Immutable's constructors treat FormData objects in Chrome and Safari was the problem. Below are some screenshots that illustrate the differing results in converting a FormData object to an Immutable OrderedMap.

`js` is our FormData object coming from the request's body, and `ui.Im` is a built-in UI helper that provides the Immutable library.

In Chrome:
<img width="245" alt="messages image 176307113" src="https://user-images.githubusercontent.com/680248/32200676-18ca066c-bd90-11e7-9e7e-58eed37dc0f6.png">

In Safari:
<img width="276" alt="messages image 1467431775" src="https://user-images.githubusercontent.com/680248/32200714-3fabd77e-bd90-11e7-89bd-44f2a4ee91df.png">

---

The FormData object's data is lost in Safari! I don't think this is Immutable's fault - it's likely that Safari's native implementation is missing methods that Immutable uses to test for iterability.

Likely solution is to patch `fromJSOrdered` to manually handle FormData objects in a cross-compatible way.

**Comment by neopaf** [comment]
cool work, Kyle.
any concrete suggestion as to how to patch `fromJSOrdered`?
(I guess, that would speed things up?)

**Comment by neopaf** [comment]
news update:
next safari
https://developer.apple.com/safari/technology-preview/

will have it normal:
![2017-12-15 12 13 07](https://user-images.githubusercontent.com/4362564/34034945-7f3adfc8-e191-11e7-9ded-10b7d41fd1d9.png)

maybe we don't need to change much.

**Comment by shockey** [comment]
Hmm - if the next version of Safari fixes this, I'm inclined to label this a browser bug and call it a day.

@webron, care to weigh in on this?

**Comment by shockey** [comment]
I'm going to go ahead and close this out as a browser-specific bug. Everyone, feel free to dissent if you feel this isn't the right answer :smile:

**Comment by figodeng** [comment]
how to do this?can you make a example for details?thanks!

**Comment by neopaf** [comment]
just create a POST method, that accepts MultipartFile (copy/pasting some scala code):
```scala
  @RequestMapping(value = Array("/path1"), method = Array(RequestMethod.POST))
  def method1(@ApiParam(value = """some description""", required = false)
                     @RequestParam(value = "param1", required = false) globalCodesFile: MultipartFile,
```
