### ISSUE TITLE
requestBody content dropdown menu does not change Example value

### ISSUE THREAD

**Issue by mikk150** [swagger-api/swagger-ui#3904]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       |  3.4.4?
| How did you install Swagger-UI? | http://editor.swagger.io/
| Which browser & version?        | Opera/Chrome
| Which operating system?         |  Linux

### Demonstration API definition
```yaml
openapi: 3.0.0
info:
  title: Link Example
  version: 1.0.0
paths:
  /2.0/user:
    post:
      operationId: createUser
      requestBody:
        description: swäggins
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
          application/xml:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: The User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
          links:
            userRepositories:
              $ref: '#/components/links/UserRepositories'
components:
  schemas:
    user:
      properties:
        username:
          type: string
        uuid:
          type: string
      type: object
      xml:
        name: user
  links:
    UserRepositories:
      operationId: getRepositoriesByOwner
      parameters:
        username: '$response.body#/username'

```

### Expected Behavior

if you change `Request Body` type, then `Example Value` should change

### Current Behavior
when changing `Request Body` type, then `Example Value` does not change.. It does change tho if you press `Try it out` button

**Comment by TimtationOne** [comment]
I'm still facing the problem described by @mikk150 

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  BUG
| Which Swagger/OpenAPI version?  | 3.0.0
| Which Swagger-UI version?       | 3.5.0, 3.6.0, current Master
| How did you install Swagger-UI? |  nodejs http-server
| Which browser & version?        | Chrome 63, Firefox 57
| Which operating system?         |  Windows 10

### Demonstration API definition
```
openapi: 3.0.0
info:
  version: 0.0.0
  title: test
paths:
  /users:
    post:
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 5
        name:
          type: string
          example: Bob
```
### Expected Behavior
When I change the selection from 'application/json' to 'application/xml' in the request body I want to see the the xml example content.

### Current Behavior
The selection jumps back to 'application/json' and the example shows the json example when I try to choose 'application/xml' for the request body.
When I press 'try it out' it shows the the xml example but doesn't let me choose application/json in 'try it out' mode.
