### ISSUE TITLE
links within the document (internal links) rendered with target="_blank"

### ISSUE THREAD

**Issue by palanik** [swagger-api/swagger-ui#3963]
### How to refer links within the document (internal links) in Rick Text fields

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.x
| Which Swagger-UI version?       | 3.4.5
| How did you install Swagger-UI? | `npm install swagger-ui-dist`
| Which browser & version?        | Google Chrome 62.0.3202.94
| Which operating system?         | macOS Sierra 10.12.6

### Demonstration API definition

```json
        "deprecated": true,
        "description": "Use [`appInfo`](#/app/appInfo) instead",
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
    url: "http://localhost/project/swagger.json",
    dom_id: '#swagger-ui',
    deepLinking: true,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
}
```

### Expected Behavior

Internal links should not open on a new tab/window.

### Current Behavior

Internal links go to the right location, but open on a new tab

### Possible Solution

Detect internal links (starts with `#`) and render without `target` attribute.

### Context

Adding notes to the deprecated endpoints and referring to other endpoints to use as an alternative. 

Other use case is linking to related endpoints - _See also:_

**Comment by shockey** [comment]
Hey @palanik - thanks for the report.

Currently, the deep linking feature isn't suitable for linking dynamically to operations as you are in your example - see #3958 for discussion on this. It's mostly useful as a way to share links to a particular operation to colleagues, or get back to what you were looking at when reopening a tab.

I'm going to close this, because part of implementing #3958 will involve addressing the `target="_blank"` - but I'd like to highlight that you filing this did help out, I hadn't thought of this particular use case 😄 

Cheers!
