### ISSUE TITLE
Invalid host header

### ISSUE THREAD

**Issue by Gobliins** [swagger-api/swagger-ui#3996]
Tried out as you described:

git clone git@github.com:swagger-api/swagger-ui.git
cd swagger-ui
npm install
npm run dev
Wait a bit
Open http://serverurl:port/

but when opening the URL, i am getting displayed "invalid host header" on an empty page.

I have node 6.11 and npm 3.10

**Comment by shockey** [comment]
@Gobliins, what browser are you using?

**Comment by Gobliins** [comment]
I am using Google Chrome (OS Windows) .

**Comment by shockey** [comment]
@Gobliins, are you behind a proxy or VPN? This error usually comes up when you aren't accessing your localhost directly.

**Comment by Gobliins** [comment]
Sorry if my info was a bit missleading, i acces the machine from another server but normaly our proxy only comes into play when using https not http. But i will research this issue on our side.

**Comment by shockey** [comment]
Sounds good, @Gobliins. FYI, the development server (`npm run dev`) isn't really meant to be used if you just want to have a copy of Swagger-UI hosted somewhere, things can definitely get weird if you aren't accessing it from localhost. Swagger-UI will also be slower and larger because the development server retains extra code for debugging in the application.

If you aren't developing Swagger-UI on the fly from this server, I suggest serving the static files from a web server or using Docker image instead :smile:

**Comment by Gobliins** [comment]
Yes on our Meteor we have done it like this 8serving the static files). 
You can close this issue, because it seems that the header is a problem in our environment.
