### ISSUE TITLE
Identify and reduce the number of redundant actions in a re-render

### ISSUE THREAD

**Issue by ponelat** [swagger-api/swagger-ui#3998]
## Identify and reduce
Identify and reduce the number of redundant or "fixable" actions that occur during a change to the spec date (ie: it all starts with specActions.updateSpec ).

Using
- Profiling with Chrome ( or any browser ) to identify the CPU hogging actions
- Redux dev tools: justify each action in the list, is it required?
- Actions fired as part of rendering, ie: during some life cycle methods.

**Comment by shockey** [comment]
Arguments to actions are not 100% correct, they're just notated for context.

Thoughts based on findings:
- Many extraneous actions (i.e., consumes/produces, parameter values) are due to components sending their default choices into state.
- Updates to the spec content state keys should be minimized, as we currently have to re-render most everything when that value changes.
- 

Loading a definition (Swagger-UI)

Overall, this looks sane to me. There are a couple actions out of place that we can address, but there's no major follow-on effects that would make me concerned about performance.

- spec_update_url(petstoreUrl)
    - no state update; presumably from the url already being set by the config
    - this is ok, since nothing is on the page, also doesn't affect SH
- spec_update_loading_status(loading)
- configure_auth({...})
- spec_update_loading_status(success)
- spec_update_spec(textContent)
- err_clear(source: parser)
- spec_update_json(jsContent)
- spec_update_url(petstoreUrl)
    - what's triggering this?
- err_clear(type: thrown)
- spec_update_resolved(resolvedContent)
- set_scheme(scheme: http)


Loading a definition (Swagger-Editor)

Potential gains here include investigating the set_scheme duplication, and combining the semantic/structural error clearing into one action (which would also improve the performance of the filtering itself).

- spec_update_spec(textContent)
- err_clear(source: parser)
- spec_update_json(jsContent)
- err_clear(type: thrown)
- spec_update_resolved(resolvedContent)
- set_scheme(scheme: http)
- set_scheme(scheme: http)
- err_clear(source: semantic)
- err_clear(source: structural)


Editing an operation description (Swagger-Editor)

This one is clearly overkill. The biggest thing is the operation_value actions - these definitely tickle the Operations container, and are not conceptually necessary the second time around.

This touches on what I think was a flaw in our initial spec plugin design. Metadata and state around the spec content should not be stored within the json/resolved keys, it should have its own subtrees to live in.

- spec_update_spec(textContent)
- spec_update_operation_value(producesValue: application/json)
- spec_update_operation_value(consumesValue: application/json)
- err_clear(source: parser)
- spec_update_json(jsContent)
- err_clear(type: thrown)
- spec_update_resolved(resolvedContent)
- spec_update_operation_value(producesValue: application/json)
- spec_update_operation_value(consumesValue: application/json)
- err_clear(source: schema)
    - Is this a mistake? I think this should be structural.
- err_clear(source: semantic)
- 

Editing an Info description (Swagger-Editor)



- spec_update_spec(textContent)
- err_clear(source: parser)
- spec_update_json(jsContent)
- err_clear(type: thrown)
- spec_update_resolved(resolvedContent)
- spec_update_operation_value(producesValue: application/json)
- spec_update_operation_value(consumesValue: application/json)
- err_clear(source: schema)
- err_clear(source: semantic)


Loading/editing a definition with multiple semantic errors (Swagger-Editor)

The main problem here is that the new semantic validation system fires a newSpecErr action for each error.

**Comment by shockey** [comment]
Looking at the many produces/consumes actions that are fired when an operation is the first to expand since page load... It's coming from `OperationContainer` (https://github.com/swagger-api/swagger-ui/blob/adf03e49ae1df968219f7340f646d534f5e76c59/src/core/containers/OperationContainer.jsx#L97).

Expanding Petstore's `POST /pet` operation takes 280ms the first time, and 99.1ms afterwards. It looks like most of that weight is coming from these extraneous actions.

**Comment by ponelat** [comment]
That'll help a bunch to reduce that. 
The logic there was to add the first value of the produces/consumes into state... such that it matches what the dropdown shows. And if the definition gets updated dynamically ( ie: swagger-editor ) then it updates there again.
