### ISSUE TITLE
Swagger UI ignores line breaks in description (<br> or \n )

### ISSUE THREAD

**Issue by EricAtMSFT** [swagger-api/swagger-ui#4126]
Affected Version: Swagger UI V3.x

<code>
paths:
  /pet:
    post:
      tags:
      - "pet"
      summary: "Add a new pet \n in the store or < b r > in this service"
</code>

### Expected Behavior
I would expect the swagger UI to show:
Add a new pet 
in the store or 
in this service"

### Current Behavior
"Add a new pet in the store or <br> in this service"

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature
| Which Swagger/OpenAPI version?  | All
| Which Swagger-UI version?       | V 3.x works fine in V2.x

**Comment by shockey** [comment]
Hi @EricAtMSFT!

The `summary` field is displayed as a single line because the summary text is inside of a `<span>` element. Being an inline element, the span ignores `\n` characters.

Further, your `<br>` is not showing up because the `summary` field is a simple string field, as opposed to `description`, which is a Markdown field:


> `summary`: An optional, string summary, intended to apply to all operations in this path.
> 
> `description`: An optional, string description, intended to apply to all operations in this path. CommonMark syntax MAY be used for rich text representation.

Markdown fields allow HTML (though we strip most HTML tags out in Swagger-UI, for protection against XSS attacks), but regular string fields do not, they're just displayed as-is.

Within Swagger-UI, we expect that your summary will only be one line, since it was added to the OpenAPI specification with the intention of being a shorter version of an operation description. Allowing multi-line summaries would require us to rework our summary and operation UI, and IMO would go against the spirit of the summary and description fields.

FYI, I tested your example string in the `description` field, and it worked as I would expect it to (breaking lines on `<br>` and `\n`).

Hopefully this helps!

**Comment by EricAtMSFT** [comment]
Hi @shockey 
Thanks for the info. Apparently the line breaks worked for non markdown fields for folks in Swagger UI V2.x (according to the customer asking us what happened)

Can you confirm that the removal of this is new to the V3 UI?

Thanks!

/Eric

**Comment by shockey** [comment]
>  Apparently the line breaks worked for non markdown fields for folks in Swagger UI V2.x

I just tried your example in the 2.x editor (http://editor2.swagger.io) and it exhibited the same behavior as v3, everything on one line:

`summary: "Add a new pet \n in the store or <br> in this service"`

![messages image 1157807041](https://user-images.githubusercontent.com/680248/35076175-9ea2c50c-fbbc-11e7-9fa0-b500630547a4.png)

---

This is on the last released version of v2, so earlier versions may have behaved differently. 

Unfortunately, I wasn't involved in the v2 development, so I can't pinpoint where such a change was made. Sorry about that!

**Comment by EricAtMSFT** [comment]
We must have an older version of V2. Here's line breaks in action. I'll close this. Thanks for the clarification.
![image](https://user-images.githubusercontent.com/17344631/35079418-292c83d0-fbbc-11e7-8e1f-43630257c305.png)

**Comment by shockey** [comment]
No problem, glad I could help.

Btw: if you'd like to restore the breakable functionality in V3, I could point you in the right direction for writing a custom plugin for that :smile:
