### ISSUE TITLE
springfox support interface versioning?

### ISSUE THREAD

**Issue by ly853602** [swagger-api/swagger-ui#4195]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       |
| How did you install Swagger-UI? | 
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

```yaml
your: "API definition goes here"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "your": { "constructorConfig": "here" }
}
```

`?yourQueryStringConfig=here`

**Comment by ly853602** [comment]
for example.I have defined two interface like this:   http://test/v1/hello;    http://test/v2/hello; when consumer invoke the interface,the path can changed by version that have defined by provider

**Comment by scottohara** [comment]
Hi @ly853602,

(note: I'm not a maintainer of this project; but I'm just jumping in to help triage a few issues).

Reading through your issue description, it isn't clear (to me) what you are actually requesting.  

Could you please fill in the issue template with some more details on what this issue is about (e.g. bug vs feature, expected/current behaviour etc.)

The more information you can provide, the easier it will be for the the Swagger UI team to assess your request.

Thanks.

**Comment by shockey** [comment]
Thanks for the assist, @scottohara!

@ly853602, Springfox questions should be directed to https://github.com/springfox/springfox 😄 

I'm going to close this, @ly853602 if you do have a question related to Swagger-UI, feel free to reply and I'll reopen.
