### ISSUE TITLE
Wording of "Done" Button => "Cancel"

### ISSUE THREAD

**Issue by hoereth** [swagger-api/swagger-ui#4211]
Version: [ 2.8.0]

What kind of issue is this? Change Request.

We experienced usability issues with the springfox-swagger-ui. The authorization window shows a "Done" button (see screenshot) which acts like a "Cancel" button. I like to suggest to rename it, because users might be tempted to click "Done" to perform the authorization. In fact they should click "Authorize". You would improve awareness by renaming "Done" to "Cancel".

![swagger-authorization](https://user-images.githubusercontent.com/22708947/36038404-e971a188-0dbf-11e8-9d5f-85ddb42e613b.PNG)

**Comment by charlescapps** [comment]
This is funny. We have a usability issue at our company (if there isn't a `Done` button) where *after* you are done authorizing, it's confusing that there's just a `Logout` button and an `x`. Many users will just click `logout` because it's the big button present, and it's not 100% clear that clicking the `x` will let you keep your authentication.

I put up a PR to add the `Done` button to the OAuth dialog where it's currently missing, see https://github.com/swagger-api/swagger-ui/pull/4212

I would suggest we arrive at a compromise, either
A) The `Done` button is only present after you have at least one authorization, so that users aren't just presented with `logout`. This would solve both of our problems.
B) We could just make it configurable whether or not there's a `Done` button. I could adjust my PR to make it a config option that's off by default.

Thoughts?

**Comment by hoereth** [comment]
I understand that "Cancel" can also be misleading. The button seems to have been introduced as "Close" action. It seems that "Close" could serve both parties. (?) :)

**Comment by charlescapps** [comment]
I'd be fine with `Close` if that's cool with you, @hoereth . I can update my pull request to call it `Close` instead of `Done`. I'll do so now! 

Thanks for finding such an easy compromise. Cheers!

**Comment by charlescapps** [comment]
OK, #4212 should satisfy this feature request now I believe.

**Comment by hoereth** [comment]
@charlescapps : thank you! :)
