### ISSUE TITLE
How to change the host name for operations in Swagger UI 3.0

### ISSUE THREAD

**Issue by madhanJayaprakash** [swagger-api/swagger-ui#4302]
consider this use case when i am executing the operation
1.It will hit the host like "http://www.example.com/operationname"
2.This host has multiple service running for this operation whichever the service has less load it will return that endpoint(URL).
3.after i am getting that Endpoint i have to execute the operation.

Is this possible or not?

**Comment by webron** [comment]
That sounds like a case for a load balancer, not swagger-ui.

**Comment by shockey** [comment]
Yes, this is possible, but you wouldn't describe this logic in your OpenAPI document - you'd just have two endpoints, and a `servers` definition that allows you to inject the host that you want.

That said, I agree with @webron - generally you'd want to hide multiple servers behind a load balancer with a single address, instead of handing out URL pointers.. it creates less HTTP overhead and is easier to conceptualize.

Closing for now!
