### ISSUE TITLE
Openness to accept PR? Dynamic request builder, in-app JSON validator, line numbers

### ISSUE THREAD

**Issue by JonKohler** [swagger-api/swagger-ui#4343]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature
| Which Swagger/OpenAPI version?  | OAI 2.0
| Which Swagger-UI version?       | swagger.latest
| How did you install Swagger-UI? | clone
| Which browser & version?        | many
| Which operating system?         | many

We're working on a few custom tweaks to suit our needs for swagger-ui 3.0 in react, including what we're calling a dynamic request builder, that makes building a sample response to try out much easier, as well as some in-app JSON schema validator, and some enhancements to the input boxes for entering in JSONs (like adding line numbers, in line/in tree "copy" button, similar is to the copy button recently worked on here #4312, but more granular).

Was wondering if the community would be open to accepting PRs for these types of enhancements. I did some looking around at both open issues and past/present PRs, and didn't see these jump out at me.

if so, besides the general contributing guidelines, are there any other tips that we should follow, such as willingness (or lack thereof) to have dependencies from other projects, etc?

**Comment by heldersepu** [comment]
> Was wondering if the community would be open to accepting PRs for these types of enhancements

Sure, on my experience the team always welcomes new contributions

>  are there any other tips that we should follow

Keep your Bug/Features shorts, clear & easy to reproduce.
You mentioned "a few custom tweaks" don't just send one PR for everything instead break it down.

And last, make sure your changes have UnitTests

**Comment by webron** [comment]
@JonKohler - As @heldersepu mentioned, we try to be open in accepting PRs and appreciate the help we get from the community in terms of helping us improve the project.

The options you brought up sound interesting, and are definitely worth exploring. In order to figure out whether each one of those makes sense for the project, I'd suggest either opening a separate feature ticket for each one, with a more detailed explanation of the proposed changes, or alternatively, we can make this ticket a longer thread and expand the details here. 

I'd rather you didn't submit PRs right away as some of the changes sound substantial, and I'd like us to have the opportunity to discuss the implications before having you spend the extra time on submitting the PRs.

Looking forward to your further input.

**Comment by JonKohler** [comment]
absolutely @webron - Thats why I asked, I'd hate to waste either of our time working on something that doesn't make any sense. Let me spend a bit of time mocking up the details, and will open separate tickets to discuss them when we have those details.

Will close this out for now, thanks for the feedback!
