### ISSUE TITLE
Method GET does't support form param in swagger-ui.  

### ISSUE THREAD

**Issue by ICrazyMouse** [swagger-api/swagger-ui#4391]
My http interface has a random size param,it works well, only swagger-ui can't invoke it rightly.
The param like:
> @RequestParam Map<String, String> formData

Request like `http://...url?a=1&b=2&c=3` will give a map with data of size 3 which meet my expectations .

But on swagger-ui the request will become `http://...url?formData=a%3d1%26b%3d2%26c%3d3`.

Full code is below:

```
    @ApiImplicitParam(name = "formData", value = "###", paramType = "form")
    @RequestMapping(value = "/###", method = RequestMethod.GET)
    public Object status(@RequestParam Map<String, String> formData) {
        ...
    }
```

I am Chinese, sorry for my poor English.....

**Comment by webron** [comment]
@ICrazyMouse - it's hard to tell if this issue is with Swagger-UI or Springfox. Since the root of it is with Springfox, please file the ticket there. If after analysis you realize the issue is with swagger-ui, please reopen the ticket here and provide us with the version of swagger-ui (not springfox) that you use.
