### ISSUE TITLE
mouse wheel scrolling stop working

### ISSUE THREAD

**Issue by gonenduk** [swagger-api/swagger-ui#4441]
swagger-ui-dist version 3.13.4
Happens both on Chrome and Edge.

Place the mouse cursor on one of the Responses "example values" (or an actual response). No need to click on it. Try to use the mouse wheel to scroll the page. Nothing happens.
When switching to "model" instead of "example value" the wheel is working.

Does not happen on editor.swagger.io (is it the same version?)

**Comment by heldersepu** [comment]
Probably caused by #4397

**Comment by shockey** [comment]
Hi @gonenduk!

This is by design: response containers are now scrollable, so we’re trapping scroll events so that they only affect the scrollable element itself, and not the surrounding page.

Are you looking at a small (i.e. non-scrollable) response? In that case, it would make sense to me to disable the scroll trap.

**Comment by heldersepu** [comment]
@shockey I was testing on: http://petstore.swagger.io/#/pet/addPet
Yes it has a small example and the issue happens on the parameters as well

**Comment by gonenduk** [comment]
Hi,

Yes, I was looking at a small response with no scroll bars. I believe if there is no scroll bar shown - there the scroll trap should not be disabled.
This is the behavior in GitHub. Just checked...

**Comment by shockey** [comment]
fixed! thanks for reporting this, @gonenduk
