### ISSUE TITLE
swagger version 3 error NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by lijodigiledge** [swagger-api/swagger-ui#4586]
swagger 3.0 error
i tried get request
Undocumented | TypeError: NetworkError when attempting to fetch resource.
-- | --
but in localhost server it is showing 300 redirecting

**Comment by shockey** [comment]
Hi!

Unfortunately, your ticket is a bit thin on details as a result of it not following the provided issue template.

We'd be happy to take a look if you open a new issue, and follow the template. Feel free to tag me in the new ticket so I see it.

Thanks!

**Comment by IceflowRE** [comment]
This could happen because the server dont allow `Access-Control-Allow-Origin` and `Access-Control-Allow-Credentials` (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)
Short version send this headers with the response:
`Access-Control-Allow-Origin` with `https://app.swaggerhub.com`
`Access-Control-Allow-Credentials` with `true`

**Comment by shockey** [comment]
@goldyliang, please open a new issue if you're having a problem 😄
