### ISSUE TITLE
Example in Response Not Used

### ISSUE THREAD

**Issue by dgrahn** [swagger-api/swagger-ui#4610]
### Q&A
 - OS: Windows 10
 - Browser: Chrome
 - Version: 66
 - Method of installation: website and npm
 - Swagger-UI version: 3.14.2
 - Swagger/OpenAPI version: OpenAPI 3.0.1

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.1
info:
  version: 1.0.0
  title: Example of Bug
paths:
  '/':
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MySchema'
              example:
                a: asdf
                b: 1234
components:
  schemas:
    MySchema:
      type: object
      properties:
        a: 
          type: string
        b:
          type: number
```

### Describe the bug you're encountering
The example listed in the response is not used.

### To reproduce...
1. Go to https://editor.swagger.io/
2. Copy and paste the above schema.
3. Navigate to the '/' endpoint.
4. See error, no example

### Expected behavior
The example should be used.

**Comment by hkosova** [comment]
Thanks for the report! This issue is being tracked in #3437.

**Comment by dgrahn** [comment]
Looks like this should have been fixed a long time ago. The number of open issues on this project is a little disturbing.

Do you have a contribution guide?

**Comment by shockey** [comment]
> Looks like this should have been fixed a long time ago. 

Yeah, looks like the issue was tagged in a milestone, which we stopped actively using a while ago. 

We track statuses in a private GitHub project now - FYI, that issue is currently 10th on our "next items to work on" board. I've removed the stale milestone marker, to avoid confusion.

> The number of open issues on this project is a little disturbing.

As an open-source project, our bandwidth is limited - I'm the only code maintainer of this project along with Swagger-Client and Swagger-Editor. 

We do our best, as our 2,900 closed issues indicate 🙂

> Do you have a contribution guide?

Yes! See [`CONTRIBUTING.md`](https://github.com/swagger-api/swagger-ui/blob/master/CONTRIBUTING.md). We also have unit and integration tests, as well as an ESLint configuration to guide you as you make changes.

If you have any specific questions, feel free to send me an email (address in profile) or send me a PM on Gitter.

---

I'm going to close this as a duplicate, but I'm happy to continue discussion here.
