### ISSUE TITLE
Add support for “multi” path parameters

### ISSUE THREAD

**Issue by Rinzwind** [swagger-api/swagger-ui#47]
I have an API with tree resources, which are handled by a single handler method in the implementation. The URL template for these resources is something like: (in [RFC 6570](http://www.rfc-editor.org/info/rfc6570) syntax)

```
/tree.{format}/{name}{/nodeid*}
```

So `/tree.json/foo` points to a JSON representation of the root node of the tree named “foo”, `/tree.json/foo/4/2` points to the second child node of the fourth child node of the root node and so on. There doesn't seem to be a convenient way to describe these resources as a single API GET operation in Swagger. The [Swagger specification](http://swagger.wordnik.com/spec) implies that the “allowMultiple” attribute can only be used for query parameters, not for path parameters.

**Comment by tarunsingh18** [comment]
I am new to this forum. We need this multi path parameter support in swagger-ui as we are using it to display and test api operations. Swagger being the API framework should support the API operations which can have multi path parameters but doesn't want API operation path to be defined for every possible path combination.
For ex. as captured by Rinzwind 
/tree.{format}/{name}
/tree.{format}/{name}/{nodeid1}
/tree.{format}/{name}/{nodeid1}/{nodeid2}

Please advise if this bug is fixes in swagger editor 2.0 or later

**Comment by webron** [comment]
@tarunsingh18 - the spec just doesn't support it. As they say, it's not a bug, it's a feature.

**Comment by offero** [comment]
We have the same exact use case and I am pretty sure that a lot of people do. Why is it a "feature"?

**Comment by lucklove** [comment]
I have the same use case.
@webron I don't think it's a feature. It's more likely a defect. It's not possible to describe tree resource with swagger.
