### ISSUE TITLE
store.subscribe() callback doesn't get invoked when the global state changes

### ISSUE THREAD

**Issue by srpalomino** [swagger-api/swagger-ui#4717]
I'm trying to invoke a callback inside the OperationTag component whenever the global state updates. The problem is that the callback never gets invoked, and I have no idea why.

Here's my [implementation](https://gist.github.com/srpalomino/b97a8d45546bf2ef78ae44da197fa5cc#file-operation-tag-js-L31)

Thanks!

**Comment by shockey** [comment]
Hey @srpalomino, the issue here is that you're creating a new store (on [line 8](https://gist.github.com/srpalomino/b97a8d45546bf2ef78ae44da197fa5cc#file-operation-tag-js-L8)) and subscribing to that - that isn't the store that Swagger UI is using, so nothing is happening within that store.

More broadly... instead of listening to the store (which is a very low-level way to react to changes), you should use the selectors provided to OperationContainer to pass the desired data to OperationTag (like [this](https://github.com/swagger-api/swagger-ui/blob/7e9881d885383a507584bcf9ffd534ca7d27fa93/src/core/components/operations.jsx#L66), instead of `"whatever"` you could call a selector, i.e. `myProp={specSelectors.url()}`).

OperationContainer, being a container component, will automatically re-render when the store's state changes. Each time a render happens, the selector you use will grab the freshest value out of the store - which accomplishes what you are trying to do with `subscribe`, without the complexity of having to build out the subscription/reaction lifecycle yourself.
