### ISSUE TITLE
Security settings applied to curl but not to ajax calls

### ISSUE THREAD

**Issue by papayasoft** [swagger-api/swagger-ui#4777]
### Q&A
 - OS: macOS
 - Browser: chrome
 - Version: [e.g. 22]
 - Swagger-UI version: [e.g. 3.17.6]
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Using the Petstore UI (http://petstore.swagger.io/) and feeding it my own Swagger resource file via querystring `?url=https://example.com/path/to/my/swagger.json`. In the Swagger resource file, I have the following security settings:

```json
   "security": [
        {
            "authKeyInHeader": []
        }
    ],
    "securityDefinitions": {
        "authKeyInHeader": {
            "type": "apiKey",
            "in": "header",
            "name": "Authentication"
        }
    }
```

### Describe the bug you're encountering

Our API is using a header of the form `Authentication: <your-api-key-here>`, hence the `security`/`securityDefinitions` above.

When using the "Authorize" and functionality, the UI correctly detects/reads the `securityDefinitions` and `security` settings above and solicits the api-key value.

On "Try It Now" execution, I can see by inspecting the XHR Network traffic that the `Authentication` header is *not* being sent by the UI. Of course, my server responds with 401 and the request fails in the UI. I imagined that my `securityDefinitions` and `security` settings must be incorrect.

But here's the thing: In the `curl` displayed in the UI, the Authentication header *is* provided. Pasting that `curl` into a Terminal window results in a perfect request that the server accepts and processes. This suggests that the `securityDefinitions` and `security` sections are ok and that the problem is with the UI itself.

Why does the request generated by the UI for use in AJAX/XHR *fail* to include the defined `Authentication` header, but the generated/displayed `curl` *does* include the header?

**Comment by shockey** [comment]
Hey @papayasoft!

First things first: is your server _allowing_ Swagger UI to send an Authorization header? 

You need to respond to `OPTIONS` method requests with an [`Access-Control-Allow-Headers: *`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers) header, otherwise your browser will only allow Swagger UI to send the simple headers (Accept, Accept-Language, Content-Language, and Content-Type).

The larger mechanism at work here is called CORS (Cross-Origin Resource Sharing), which you can learn more about here: https://enable-cors.org

**Comment by shockey** [comment]
> I should open up the API so that a naked (no auth headers) OPTIONS request to any of the actual API endpoints will return 200 with the CORS headers, and that will make the UI happy.

Exactly 😄

**Comment by papayasoft** [comment]
@shockey Many thanks! 😄  Closing...
