### ISSUE TITLE
Stray swagger-ui-dist-3.17.5.tgz in swagger-ui-dist 3.18.0 npm package?

### ISSUE THREAD

**Issue by axnsan12** [swagger-api/swagger-ui#4795]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: N/A
 - Version: N/A
 - Method of installation: npm install swagger-ui-dist
 - Swagger-UI version: 3.18.0
 - Swagger/OpenAPI version: N/A

### Describe the bug you're encountering
There is a ``swagger-ui-dist-3.17.5.tgz`` present in the 3.18.0 npm bundle of ``swagger-ui-dist``.

### To reproduce...

```sh
$ npm install swagger-ui-dist
[...]
$ ls -l node_modules/swagger-ui-dist | grep tgz
-rwxrwx---+ 1 axnsan axnsan 2276742 Jul 20 02:04 swagger-ui-dist-3.17.5.tgz
```

### Expected behavior
No stray archive.

**Comment by shockey** [comment]
Thanks for the report, @axnsan12!

This was due to testing we were doing with our new release job -specifically, we hadn't set `PUBLISH_DIST=true` in the environment yet, so `npm pack` ran for `swagger-ui-dist`:

https://github.com/swagger-api/swagger-ui/blob/c9e8a67579abcf2b87224b0f058c02fa63561fba/swagger-ui-dist-package/deploy.sh#L15-L19

The new build job doesn't clear out its workspace between builds, so the file persisted in recent releases.

I've manually cleared out the workspace, which should solve this. 

If it ends up happening again, I can add a script that cleans out the workspace before each release, or modify [`swagger-ui-dist-package/.npmignore`](https://github.com/swagger-api/swagger-ui/blob/master/swagger-ui-dist-package/.npmignore) to be a whitelist instead of a blacklist.

Closing! 😄
