### ISSUE TITLE
Question about default behavior for empty servers array

### ISSUE THREAD

**Issue by CameronGo** [swagger-api/swagger-ui#4936]
### Q&A (please complete the following information)
 - OS: all
 - Browser: chrome
 - Version: most recent
 - Method of installation: docker image
 - Swagger-UI version: 3.19.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### How can we help?
I am hosting my documentation behind the same hostname as my APIs.  Example:
https://api.domain.com/v2/members is one resource and 
https://api.domain.com gives you the swagger UI interface, which retrieves the yaml file from a public S3 bucket URL like https://public-bucket/v2/openapi.yaml.

I read that an empty servers array is treated as "/" and so I was expecting that to mean the root of the host serving the page.  It appears; however, to use the URL of the config not the host serving the page.  So the Try It Now interface attempts to send requests to https://public-bucket/members.  I'm not sure if this is a bug or not, but I would think using the host serving the page would make more sense.

As it stands today I can access my Swagger console by:
https://api.domain.com
https://api-dev.domain.com
https://api-staging.domain.com

Doing it this way addresses any CORS concerns and makes it easy and intuitive to flip back and forth between environments, or have a window open for each environment.  But it is redundant if the end user also has to select the server from a drop down, which is why using the default "/" seemed appealing, but is not working as expected.

Ultimately I'm trying to simplify the server selection so that the person using the Swagger UI console isn't manually flipping back and forth between servers in the drop down list.

**Comment by shockey** [comment]
Hey @CameronGo!

What you're observing is our intended behavior. The OpenAPI specification says the following about server URLs (emphasis mine):

> A URL to the target host. This URL ... MAY be relative, to indicate that the host location is relative to **the location where the OpenAPI document is being served**.
> 
> https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#server-object

The implicit default of `/` is also subject to this, which is leading to the behavior you're seeing.

Have you considered hosting your OpenAPI document alongside your live service? This is a pretty common convention - people like to do this because it makes the service itself "OpenAPI-enabled".

If you're married to the idea of hosting your document in a bucket, let me know - there's a way to rewrite the request URL in an interceptor that I can show you, but it's a bit of a weird implementation.

**Comment by CameronGo** [comment]
Thanks @shockey, I'm not married to hosting the document in a bucket, it just seemed to be the best way to load the api doc while using the public swagger UI docker image.  I suppose I could create an image that would download the api doc at runtime. Is that what you had in mind, or is there another implementation of that which makes more sense?

**Comment by shockey** [comment]
I suggest that you make your OpenAPI document available through your API as a static file, so that you can `HTTP GET http://api.domain.com/openapi.yaml` to load the document (as Swagger UI will when it loads). If you wrote it by hand, it makes sense to put the OpenAPI document in version control alongside the API implementation so that you can see it change over time with your implementation, and manage changes to it.

You can then point the Swagger UI Docker image at that by setting `API_URL=http://api.domain.com/openapi.yaml` on the image, and Swagger UI itself will fetch the document each time a user loads Swagger UI's page.

**Comment by CameronGo** [comment]
I don't think hosting the API doc with the implementation will fit in our case since our API implementation consists of about a half dozen+ micro services (roughly 1 service for each top level resource).  I think I've got a solution I may go with using our CICD solution to publish the API doc to the bucket and run sed on the doc before it goes out so that the server reference uses the URL for the proper environment.

Thanks @shockey for the clarification on intended behavior.
