### ISSUE TITLE
Problem to install js-yaml dependence

### ISSUE THREAD

**Issue by SilvaLA59** [swagger-api/swagger-ui#4941]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: chrome
 - Version: [e.g. 22]
 - Method of installation: npm
 - Swagger-UI version: Lastest
 - Swagger/OpenAPI version: 

 Hello, I'm facing a problema that when I try to install this package I get 404 Error when It try to install @kyleshockey/js-yaml
I think this dependence is wrong in package.json. It should be just "js-yaml", shouldn't it?

**Comment by shockey** [comment]
Hey @SilvaLA59, the entry is correct, it references this module: https://www.npmjs.com/package/@kyleshockey/js-yaml. It's a [scoped module](https://docs.npmjs.com/misc/scope), which has been a part of npm since `npm@2`.

If you're on an older npm version: upgrade! If you're on a newer one, post the output you're seeing so we can take a look at what's going on.

**Comment by SilvaLA59** [comment]
Hello @shockey , thanks for you answer. I'm using npm version 6.4.1, should I install something diferent to use this "npm@2" ?
When I run "npm install js-yaml" It works.

This is my output:

npm ERR! code E404
npm ERR! 404 Not Found: @kyleshockey/js-yaml@^1.0.1

npm ERR! A complete log of this run can be found in:
npm ERR!     \npm-cache\_logs\2018-10-12T11_33_18_298Z-debug.log

**Comment by SilvaLA59** [comment]
I fixed running "npm uninstall npm -g" then "npm install npm -g"
