### ISSUE TITLE
The Response Id round-up why? swagger 2.9.2

### ISSUE THREAD

**Issue by nadjin** [swagger-api/swagger-ui#5044]
![img20181122200422](https://user-images.githubusercontent.com/23130767/48902007-2c42a080-ee92-11e8-85ba-bafc8d94d2b7.png)

![img20181122200955](https://user-images.githubusercontent.com/23130767/48902146-9fe4ad80-ee92-11e8-9c40-73a1449fbe94.png)

the response id always round-up. why? if  the controller @ApiImplicitParam  I don't add  paramType = "path" ,the id if should 515240706323775433,but if you debug u will find the id change to 515240706323775400. 
Thank U .

**Comment by shockey** [comment]
Hi @nadjin!

Basically... Swagger UI is a JavaScript application, and JavaScript stores all numbers as [IEEE 754 double-precision floating-point numbers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER#Description). Your number is much larger than the highest integer JavaScript can safely handle:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/680248/48960533-9da35180-ef6d-11e8-907e-30956083d6f1.png">

We've covered this before, in https://github.com/swagger-api/swagger-ui/issues/2030. The number is being changed in the response because we're using JavaScript's built-in JSON parser, which mangles the number because it's too big.

Solutions for this in Swagger UI include using a `JSON.parse` library that handles big numbers correctly, or adding an option to show a raw JSON instead of a parsed one (see #4018). For now, the only workaround is to return your big number as a string in the JSON you send back.

If this is a show stopping bug for you, consider making a pull request to fix this 😄 

I'm going to close this out, since the tickets mentioned above cover this issue well. Thanks for reaching out!
