### ISSUE TITLE
SwaggerUi won't download specs in urls

### ISSUE THREAD

**Issue by rfauglas** [swagger-api/swagger-ui#5173]
### Q&A 
 - OS: linux
 - Browser: chrome
 - Version: Version 66.0.3359.181
 - Method of installation: npm
 - Swagger-UI version: 3.20.7
 - Swagger/OpenAPI version:  Swagger 2.0

### Content & configuration

Swagger-UI configuration options:
```js
SwaggerUI( 
           {
                dom_id: '#swaggerContainer',
                urls: [
                    {
                        url: 'http://localhost/api/docs.json',
                        name: 'SaaS API',
                    },
                ],
            }
)
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering
The "urls" configuration  is ignored. 
 The swagger api is not fetched.
I receive a "No API definition provided." message.

### To reproduce...

1. create a ReactJS component:
class Swagger extends Component {
    componentDidMount() {
        SwaggerUi(...

2. Load component

### Additional context or thoughts
Documentation mentions a Topbar plugin... Am i missing something?  
An example or an improved presets/plugins documentation  would help...

**Comment by shockey** [comment]
Hi @rfauglas,

Indeed you are missing the Standalone preset, which includes the topbar plugin!

Import the preset like so: 

```js
import StandalonePreset from 'swagger-ui/dist/swagger-ui-standalone-preset'
```

then add this option to your Swagger UI call:

```js
presets: [
  SwaggerUI.presets.apis, 
  StandalonePreset
]
```

_Note: `SwaggerUI.presets.apis` is the default value for `presets`, Swagger UI needs it in order to function. It must be included when overriding the `presets` option._

I'm going to keep this open, since the documentation could use improvement.

Also, keep an eye on our work in [label: `epic: usage in react@16`](https://github.com/swagger-api/swagger-ui/issues?q=is%3Aopen+is%3Aissue+label%3A%22epic%3A+usage+in+react%4016%22), we're going to be fixing some bugs related to using Swagger UI in React and likely publishing a new module specifically for React end-users, which will export a Swagger UI component instead of a constructor function. If you'd like to help test before we ship it, please email me (address in profile) and I'll be in touch.

**Comment by rfauglas** [comment]
Hi @shockey ,
This works perfectly !
