### ISSUE TITLE
Impossible to run Docker image under DC/OS because ${PORT} conflicts with a system var

### ISSUE THREAD

**Issue by mimmus** [swagger-api/swagger-ui#5203]
It is actually impossible to run swagger-ui Docker image under Mesosphere DC/OS in bridge mode because var ${PORT} - used in its start.sh - conflicts with a system var (https://docs.mesosphere.com/1.12/deploying-services/service-ports/).
Consequently, swagger-ui listens always on a random port instead of 8080.

**Comment by shockey** [comment]
@mimmus, thanks for the report. 

This will take a while to resolve, because dropping support for $PORT in our image would be a breaking change.

In the meantime, I recommend exploring workarounds that allow you to pass an env var directly to the Swagger UI container itself, without affecting the surrounding DC/OS system.

**Comment by mimmus** [comment]
I was able to run swagger-ui under DC/OS using host mode, instead of bridge mode.

**Comment by shockey** [comment]
@mimmus it's a breaking change because folks using our image today may rely on Swagger UI respecting a `PORT` value in order to correctly route requests to a custom port.

**Comment by smparekh** [comment]
@mimmus, you can also fork the project and replace `$PORT` with `$SWAGGER_UI_PORT` in the run.sh and `SWAGGER_UI_PORT` in Dockerfile. Build and deploy to a docker repo and deploy. I have a forked branch here with the fix: https://github.com/smparekh/swagger-ui/tree/port-fix.

**Comment by mimmus** [comment]
Thank you very much.
In the meanwhile, we was able to run swagger-ui on DC/OS using Host mode
