### ISSUE TITLE
Upgrade btoa to version 1.2.0

### ISSUE THREAD

**Issue by ahumph** [swagger-api/swagger-ui#5205]
### Is your feature request related to a problem?

btoa < v1.2.0 has a security vulnerability - [CVE-2018-3745](https://nvd.nist.gov/vuln/detail/CVE-2018-3745).

### Describe the solution you'd like

Upgrade btoa dependencies to v1.2.0 or later.

**Comment by shockey** [comment]
Per the CVE's associated HackerOne report:

> It allows to extract sensitive data ... in setups where typed user input can be passed ... on Node.js 4.x and lower.

Our usage of btoa on user input is limited to the browser. Furthermore, even in Node.js this is safe, since only 4.x is vulnerable - which was pronounced End-of-Life [almost a year ago](https://github.com/nodejs/Release#end-of-life-releases).

I'm going to keep this open because I know that the npm warnings are annoying and scary to folks installing Swagger UI... but I'm going to keep this low priority so no core members pick it up, because this is not a real security issue for anyone using Swagger UI - there's simply no attack surface here.

**I welcome anyone who wants to open a PR bumping our minimum `btoa` version to do so.**

**Comment by shockey** [comment]
Closing -- our audit outputs are clean now (see [OSS JavaScript Security Audits](https://jenkins.swagger.io/view/OSS%20-%20JavaScript%20Security%20Audits/)), and as I previously mentioned this vulnerability can't be leveraged against Swagger UI users.

Thanks for reporting, @ahumph!
