### ISSUE TITLE
Swagger UI error should be more descriptive

### ISSUE THREAD

**Issue by jvhih** [swagger-api/swagger-ui#5366]
Based on the error from this [issue 2123](https://github.com/RicoSuter/NSwag/issues/2123).

I was using a property that wasn't marked deprecated and the error displayed on the UI and console were unable to point me in the right direction as to what was wrong.

When using IServiceCollection.AddOpenApiDocument() I was adding an IOperationProcessor that was setting a parameter that is deprecated for Open API.

The following was causing me an issue:
```
public class SampleHeaderOperationProcessor : IOperationProcessor
{
    public Task<bool> ProcessAsync(OperationProcessorContext context)
    {
        context.OperationDescription.Operation.Parameters.Add(
            new SwaggerParameter {
                Name = "Sample",
                Kind = SwaggerParameterKind.Header,
                Type = NJsonSchema.JsonObjectType.String,    // problem line
                IsRequired = false,
                Description = "This is a test header",
                Default = "{{\"field1\": \"value1\", \"field2\": \"value2\"}}"
            });

        return Task.FromResult(true);
    }
}
```

The following fixed it:
```
public class SampleHeaderOperationProcessor : IOperationProcessor
{
    public Task<bool> ProcessAsync(OperationProcessorContext context)
    {
        context.OperationDescription.Operation.Parameters.Add(
            new SwaggerParameter {
                Name = "Sample",
                Kind = SwaggerParameterKind.Header,
                Schema = new JsonSchema4 { Type = NJsonSchema.JsonObjectType.String },    // solution line
                IsRequired = false,
                Description = "This is a test header",
                Default = "{{\"field1\": \"value1\", \"field2\": \"value2\"}}"
            });

        return Task.FromResult(true);
    }
}
```

[The unhelpful error](https://i.stack.imgur.com/EjKlV.png).

Possible solutions:
1. Mark the field as obsolete with a description saying to use the 'Schema' property for Open API or
2. Update the UI with something a little more descriptive instead of simply displaying "Could not render this component, see the console."

**Comment by shockey** [comment]
Swagger UI generally expects a valid OpenAPI definition -- if it's invalid, the behavior is undefined, which can result in rendering errors (as you've seen). [Swagger Editor](http://github.com/swagger-api/swagger-editor/), the UI's sister project, does include a validation engine.

If you were editing your OpenAPI by hand, you'd see that this is an error in Swagger Editor:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/680248/58123708-4a7b2600-7bc1-11e9-9c2e-5ca92598378b.png">

You're using an annotation library. In my opinion, validating your inputs is the responsibility of the annotation library itself, since it functions as an abstraction between your code and the resulting OpenAPI document.
