### ISSUE TITLE
Cannot read property 'swaggerOptions' of undefined 

### ISSUE THREAD

**Issue by gandarez** [swagger-api/swagger-ui#560]
I'm new to Swagger framework. I'm using the latest distribuition of all libraries.
swagger 2.0.38
swagger-ui 2.0.22

After followed all examples I'm getting an error as described below

Cannot read property 'swaggerOptions' of undefined 
![image](https://cloud.githubusercontent.com/assets/782854/4165118/18283dc2-34ff-11e4-9ac5-3c6eabc7daed.png)
![image](https://cloud.githubusercontent.com/assets/782854/4165696/d07690f4-3504-11e4-8bd0-e56e238bb066.png)

**Comment by wulfuric** [comment]
@gandarez @tnikkine Did either of you find a resolution for this?  I'm currently experiencing the same issue on the swagger-ui develop_2.0 branch, please let me know if you have any insights into this, thanks

**Comment by webron** [comment]
@wulfuric - which version do you use?

**Comment by gandarez** [comment]
Actually I'm using swagger-ui 2.0.23. Probably got fixed by the team.

**Comment by rf-** [comment]
This can be caused by using a stock copy of Backbone 1.1.2 without this monkey patch: https://github.com/swagger-api/swagger-ui/blob/master/lib/backbone-min.js#L5-L15

One workaround is just to add the patch to your JS build, but in a perfect world it would be cool if the views that need this behavior could just override their own constructors instead of messing with Backbone.
