### ISSUE TITLE
Request bodies with content types such as application/zip do not have a file upload input

### ISSUE THREAD

**Issue by danielflower** [swagger-api/swagger-ui#5636]
### Q&A (please complete the following information)
 - Swagger-UI version: 3.23.11
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

```json
"requestBody": {
          "content": {
            "application/zip": {
              "schema": {
                "type": "string",
                "format": "binary"
              }
            }
          }
```

### Describe the bug you're encountering

When a request body has `application/zip` as the content type, the input box on swagger-ui is a textbox with "string" as the default value. It should be a file input box.

### Additional context or thoughts

Changing the content type to `application/octet-stream` results in a file upload box, but I'd rather have the more specific content type in my openapi description. I think it would be better to look at the schema's type and format rather than the mime type to decide whether or not to use a file upload.

**Comment by DylanGom** [comment]
This is actually almost for all application/* i have the same issue using application/pdf

**Comment by jmoraleda** [comment]
I am also experiencing this issue. 

I agree that a more sophisticated way of deciding between a button and a textbox would be beneficial, but I wonder if in addition it would be useful to have a way to provide an explicit hint to swagger-ui of whether to use an upload button or an input text box. 

I can imagine there being cases where, depending on the intended use case, one or the other might be more appropriate and there would be no way to deduce it. For example, there might be cases, where even for json input, an upload is more desirable than just typing. More over there are custom media types of the form `application/x-foobar` for which there is no way to prefer a text box over an upload button or viceversa.

Moreover, I feel this issue is symmetric on how to present the output of a method, whether in a text box, or as a download button.

By the way, I have opened this issue in other projects but closed those issues and moved my comments to here, where hopefully they are more appropriate: https://github.com/OAI/OpenAPI-Specification/issues/2185 and https://github.com/springdoc/springdoc-openapi/issues/515

**Comment by manoswerts** [comment]
Isn't `format: binary` the indication to Swagger UI to show a file upload component?

Related to this: mime type `application/octet-stream` denotes a file of any type according to the OpenAPI spec. When designing an API that accepts any file, but does need the `Content-Type` header to determine what type it is, you cannot test this with the current Swagger UI. The UI should allow you to enter a custom `Content-Type` header in this case. Listing all existing mime types would be a tedious task.

**Comment by neiser** [comment]
To add to the confusion, if one uses content types such as `image/png` or `audio/wav`, Swagger UI 3.49 indeed shows an upload button. I agree with @manoswerts that `format: binary` should be enough for Swagger UI to decide if an upload button should be shown. I don't see the need for a specific extension.

Here's a complete example with different content types, sometimes the upload button is shown, sometimes not:

```
{
  "openapi": "3.0.1",
  "info": {
    "title": "API for App46",
    "version": "unknown"
  },
  "paths": {
    "/": {
      "get": {
        "operationId": "download_Audio_Image_Zip",
        "responses": {
          "200": {
            "description": "Default response",
            "content": {
              "audio/wav": {
                "schema": {
                  "$ref": "#/components/schemas/string_binary"
                }
              },
              "image/png": {
                "schema": {
                  "$ref": "#/components/schemas/string_binary"
                }
              },
              "application/zip": {
                "schema": {
                  "$ref": "#/components/schemas/string_binary"
                }
              }
            }
          }
        }
      },
      "post": {
        "operationId": "upload_Audio_Image_Zip",
        "requestBody": {
          "content": {
            "audio/wav": {
              "schema": {
                "$ref": "#/components/schemas/string_binary"
              }
            },
            "image/png": {
              "schema": {
                "$ref": "#/components/schemas/string_binary"
              }
            },
            "application/zip": {
              "schema": {
                "$ref": "#/components/schemas/string_binary"
              }
            }
          },
          "required": false
        },
        "responses": {
          "204": {
            "description": "Default response"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "string_binary": {
        "type": "string",
        "format": "binary"
      }
    }
  }
}
```
