### ISSUE TITLE
Validator icon is not displayed

### ISSUE THREAD

**Issue by Hill-98** [swagger-api/swagger-ui#5669]
- OS: Windows 10
 - Browser: Chrome
 - Version: 80.0.3947.0 Canary
 - Method of installation: dist assets
 - Swagger-UI version: 3.24.0
 - Swagger/OpenAPI version: OpenAPI 3.0.2

Swagger-UI configuration options:
```js
SwaggerUIBundle({
            url: "https://api-doc.mivm.cn/data/ggs",
            dom_id: '#swagger-ui',
            deepLinking: true,
            presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
            ],
            plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
            ],
            layout: "StandaloneLayout"
        })
```

### Describe the bug you're encountering
The Validator icon at the bottom of the page does not appear

### To reproduce...
 Go to '[https://api-doc.mivm.cn/ggs](https://api-doc.mivm.cn/ggs)'

### Expected behavior
Validator icon display

### Additional context or thoughts

My this page ([https://api-doc.mivm.cn/swagger-petstore](https://api-doc.mivm.cn/swagger-petstore)) [swagger.json](https://petstore.swagger.io/v2/swagger.json) use as a data source, Validator icon can be normal, but can not [https://api-doc.mivm.cn/ggs](https://api-doc.mivm.cn/ggs) I find it very strange.

**Comment by webron** [comment]
@shockey - we might have a regression here. The badge doesn't appear in petstore3 either.

**Comment by Hill-98** [comment]
I'm looking forward to.

**Comment by kaibra** [comment]
I just came across this issue as well and tried to understand, what the cause is.
It still works fine for v2.0 specs:
[petstore with v2.0 spec](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml&validatorUrl=https://validator.swagger.io/validator)

But it does not for v3.0:
[petstore with v3.0 spec](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml&validatorUrl=https://validator.swagger.io/validator)

In the v3.0 case, the validator request still happens and returns an image. I saw it in the network TAB. But somehow it does never render. ValidatorImage.render() always returns null, since this.state.loaded is never true.
