### ISSUE TITLE
Misleading error on failing to load URL

### ISSUE THREAD

**Issue by setpill** [swagger-api/swagger-ui#5676]
### Q&A (please complete the following information)

 - OS: Arch Linux
 - Browser: Firefox and Chromium
 - Version: Respectively 70.0-1 and 78.0.3904.70-1
 - Method of installation: Installing what, my browsers? Through pacman. I did not install the swagger ui as I used https://petstore.swagger.io/.
 - Swagger-UI version: Whatever version was live on 2019-10-31
 - Swagger/OpenAPI version: Not relevant

### Content & configuration

Whatever is used in production; you know this better than me.

### Describe the bug you're encountering

When trying to load a URL into the swagger UI, a misleading error is given when the URL given does not return a swagger file. More specifically, I tried loading some json file from some project on Github into the swagger UI, but, being the bumbling fool that I am, directly used `https://github.com/some/project/blob/master/some/dir/something.swagger.json`. Of course I should have used `https://raw.githubusercontent.com/some/project/master/some/dir/something.swagger.json` (and this did work). However, when the first link did not load successfully, the error states it's a NetworkError and suggests a CORS issue as the cause, when in fact the link given simply returns a HTML document rather than the intended JSON.

### To reproduce...

1. Go to https://petstore.swagger.io/.
2. Input `https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml` into the textfield at the top.
3. Press "Explore"
4. It gives the following error:

> # Failed to load API definition.
> 
> ## Errors
> 
> **Fetch error**
> NetworkError when attempting to fetch resource. https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
> **Fetch error**
> Possible cross-origin (CORS) issue? The URL origin (https://github.com) does not match the page (https://petstore.swagger.io). Check the server returns the correct 'Access-Control-Allow-*' headers.

5. Retry with `https://raw.githubusercontent.com/swagger-api/swagger-petstore/master/src/main/resources/openapi.yaml`
6. It works.

### Expected behavior

An error message that reflects the problem more accurately and does not leave a noob to believe that the problem is unfixable (by them).

### Additional context or thoughts

Related issue: https://github.com/swagger-api/swagger-editor/issues/2070

**Comment by shockey** [comment]
@setpill, you're getting this CORS error because `https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml` doesn't serve CORS headers in its response, which bars Swagger UI from being able to look at the content at the URL at all. This is all due to [the browser's CORS security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) enforcement.

Unfortunately, since the browser won't tell us anything other than "sorry, can't give you the content at that URL", there's no way for Swagger UI to indicate whether the content is valid — we never see it in the first place.

Hope this helps, feel free to reply if there are any lingering concerns!
