### ISSUE TITLE
how to show map class in model

### ISSUE THREAD

**Issue by 813221068** [swagger-api/swagger-ui#5697]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
 # your YAML here
 ```

 Swagger-UI configuration options:
 ```js
 SwaggerUI({
   // your config options here
 })
 ```

 ```
 ?yourQueryStringConfig
 ```

**Comment by webron** [comment]
Hello - I understand this is your first time filing an issue. Unfortunately, your issue is missing quite a few details. Please file an issue again, and you'll notice that in the issue text box there are directions on what information we need in order to provide help (including versions and so on).

Furthermore, the title itself is not clear. It's best if you provide a description of what you're trying to do, what you end up getting and what you'd like to see instead. Looking forward to seeing your new issue.
