### ISSUE TITLE
Is it possible to document the API of ASP.NET MVC controller actions using Swagger?

### ISSUE THREAD

**Issue by Legends** [swagger-api/swagger-ui#5722]
Is it possible to document the API of ASP.NET MVC controller actions using Swagger?

**Comment by webron** [comment]
Yes. Please check out projects like https://github.com/domaindrivendev/Swashbuckle and https://github.com/RicoSuter/NSwag.

**Comment by HeikeMyer** [comment]
I'm not sure if i got it right.
Do you mean it's possible to configure access to Swagger docs and UI from ASP.NET MVC project (though anyway only controllers from System.Web.Http can be documented)?
I'd like to know if it's possible to document controllers from System.Web.Mvc.
It seems there's no way to do that with Swashbuckle, since it only works with HttpConfiguration class from System.Web.Http (so all the filters, routing and controllers are also supposed to be from System.Web.Http).
I would be truly grateful if you could make it clear.
