### ISSUE TITLE
$ref not being rendered in response example

### ISSUE THREAD

**Issue by naesean** [swagger-api/swagger-ui#5787]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 79
 - Method of installation: docker
 - Swagger-UI version: 3.24.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  version: '1'
  title: ''
  description: 'Demo of a bug in swagger'
paths:
  /api/foo:
    post:
      summary: Foo
      description: Does foo stuff
      responses:
        200:
          description: Successful request
          content:
            application/json:
              schema:
                type: string
              example:
                $ref: '#/components/examples/fooExample'
components:
  examples:
    fooExample:
      value: {foo}
```

Swagger-UI configuration options:
none

### Describe the bug you're encountering
The $ref described in the `example:` does not render. Instead, it displays the $ref string.

### To reproduce...

1. Create an named example within /components/examples/
2. Use the name example with a $ref within /paths/{path name}/{method}/responses/{http response code}/content/{content type}/example

### Expected behavior
Swagger UI renders the referenced example in the response

### Screenshots
![image](https://user-images.githubusercontent.com/49377730/72181527-6c1e5d00-339e-11ea-9218-8fa0555976af.png)

### Additional context or thoughts
None

**Comment by webron** [comment]
According to the spec, `example` fields cannot `$ref` anything and their values will always be taken as-is. To reference an example, you need to use the `examples` field. See http://spec.openapis.org/oas/v3.0.2#media-type-object for more information.

**Comment by naesean** [comment]
> According to the spec, `example` fields cannot `$ref` anything and their values will always be taken as-is. To reference an example, you need to use the `examples` field. See http://spec.openapis.org/oas/v3.0.2#media-type-object for more information.

Sorry, I'm not seeing where the specification states such a limit for `example` fields. Can you directly quote the spec?

**Comment by webron** [comment]
Reading it, it can use some clarification. However, when the type is `Any`, it means that any value is acceptable. Since there's no way of distinguishing between actual references and an example of a reference, it's a way of saying it's not supported. I'll put a note to add further clarification there

**Comment by naesean** [comment]
Thanks @webron! I'll close the ticket.

**Comment by cweedall** [comment]
I came across this issue because I see the same issue.  However, despite what @webron mentioned above, [the OpenAPI 3.0 documentation](https://swagger.io/docs/specification/adding-examples/) seems to explicitly indicate that this is valid 

> in various parameter descriptions, request and response body descriptions, objects and properties

![Screenshot of OpenAPI 3.0 documentation on reusing examples in request and response body descriptions](https://github.com/swagger-api/swagger-ui/assets/5010253/1264e59e-c161-4ce5-824f-ae776d00a0a9)

Is this a documentation issue?

**Comment by cweedall** [comment]
After writing my previous comment, I realized that I (and OP, in the screenshot) had a typo.  For the response/request `content`, it is not `example` but rather `examples`.

Hope this helps anyone who stumbles across it in the future!
