### ISSUE TITLE
text overflow

### ISSUE THREAD

**Issue by yoyo837** [swagger-api/swagger-ui#5934]
ref: #3899

### Q&A (please complete the following information)
 - OS: [macOS]
 - Browser: [chrome]
 - Version: [3.25.0]
 - Method of installation: [dist assets]
 - Swagger-UI version: [3.25.0]
 - Swagger/OpenAPI version: []

### Content & configuration

Swagger-UI configuration options:
```js
SwaggerUIBundle({
  url: "/api.do",
  dom_id: '#swagger-ui',
  deepLinking: true,
  presets: [
    SwaggerUIBundle.presets.apis,
    SwaggerUIStandalonePreset
  ],
  plugins: [
    SwaggerUIBundle.plugins.DownloadUrl
  ],
  layout: "StandaloneLayout"
})
```

### Screenshots

![image](https://user-images.githubusercontent.com/6134547/77634949-c2a63b00-6f8c-11ea-898c-6ebed97f3345.png)

**Comment by sujithnath** [comment]
Can I pick up this bug fix?

**Comment by ffranchina** [comment]
Hello, I would like to work on this issue but I cannot reproduce the unexpected behavior. The UI works very fine on the most common resolutions both on Firefox and Chrome, it just breaks at very weird width (around 260).
Only in case of very long words (like JWT tokens or similar) the text for the default value overflows like in the screenshot.

Do you confirm it is the behavior we want to address?
Thanks for the info!

**Comment by yoyo837** [comment]
Yes, I think. If the default value of the parameter is too long (cookie、base64), there is this problem.

**Comment by ffranchina** [comment]
Hello everyone!

The proposed fix addresses the specified issue but, on unusually small screens, most of the content of the page still overflows. The behavior is due to the usage of `<table>` to structure the content and a major refactoring is required in order to solve such problems. It seems that the problem is [already known](https://github.com/swagger-api/swagger-ui/blob/7a63ba30c3db548e7159c00a168fcc0d32bc6aff/src/style/_table.scss#L111), though.

Please, let me know if you think this issue still needs more attention.

**Comment by yoyo837** [comment]
This is enough, that problem about very small screen is [already known](https://github.com/swagger-api/swagger-ui/blob/7a63ba30c3db548e7159c00a168fcc0d32bc6aff/src/style/_table.scss#L111), Let's handle it in another fix. Thanks great works.
