### ISSUE TITLE
Optionally disable parameter validation

### ISSUE THREAD

**Issue by fantapop** [swagger-api/swagger-ui#5963]
Currently, its difficult to test out certain types of error responses from my backend because the validation in swagger UI prevents me from making certain types of requests. 

### Is your feature request related to a problem?

I'd like to use swagger UI to test my error response formats

### Describe the solution you'd like

An option passed into the configuration to control this would be work.

### Describe alternatives you've considered
On alternative, is that I could use the provided curl output to test these but I normally hide, this option with css to clean up the UI a bit.  Another work around when testing locally is to build and server swagger UI with relaxed patterns and types, load the page, then rebuild the backend with the tighter types enabled.  You can then use the front end until its refreshed.

**Comment by webron** [comment]
Your request is very reasonable in order to perform negative tests and it's something we've considered doing in the past. However, even though it might sound as simple as just disabling the validation, it's also an opening to further feature requests around it.

While we do have some thoughts about more testing options in the future, Swagger UI is intended as a documentation tool and not a test tool, so for now we're not planning on implementing those.

As a workaround, you can always modify your definition to remove those validations, but that woul of course require more work from your end.
