### ISSUE TITLE
swagger-ui-react: japanese characters are not rendered 

### ISSUE THREAD

**Issue by hari5004** [swagger-api/swagger-ui#5988]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: chrome
 - Version:swagger-ui-react@3.25.0
 - Method of installation: npm

### Screenshots

![image](https://user-images.githubusercontent.com/8103160/81068426-f8c8ca00-8efd-11ea-8c91-0bdf006241ab.png)

**Comment by webron** [comment]
Please file the issue again, following the issue template and providing ways to reproduce it.
From the little tests I've ran, Swagger UI displays Japanese characters with no issue. The rendering issue *could* be because the response content type is plain text and not json, but without having the full details and a way to reproduce it, it'll be difficult to check.

**Comment by hari5004** [comment]
@webron  Thanks the issue was with response content type
