### ISSUE TITLE
There was a problem using enumeration parameters

### ISSUE THREAD

**Issue by 501956430** [swagger-api/swagger-ui#6232]
`public enum PayTypeEnum {

    ALIPAY(1, "alipay"),
    WEIXINPAY(2, "wxpay"),
    WALLETPAY(7, "qbpay"),
    ;

    private Integer type;
    private String name;`

> @ApiImplicitParam(name = "payTypeEnum", value = "payType", dataType = "PayTypeEnum", paramType = "query", required = true )
    @GetMapping("/pay")
    public String pay(PayTypeEnum payTypeEnum){
.......
}

**swagger-api ： Enumeration parameter cannot be verified to pass**
<img width="1130" alt="截屏2020-07-17 11 40 04" src="https://user-images.githubusercontent.com/20204491/87746153-7411fa80-c822-11ea-8f7b-690887170707.png">

**Comment by hkosova** [comment]
The generated OpenAPI definition does not seem to be valid. Specifically, the `payTypeEnum` parameter is generated with `type: ref` which is not a valid `type` value. You can [export the API definition](https://stackoverflow.com/q/48525546) from Swagger UI and paste it into https://editor.swagger.io to check for syntax errors.

Since you generate the API definition from code, the issue is with the library that you use to generate the API definition, most likely [Springfox](https://github.com/springfox/springfox) or [Swagger Core](https://github.com/swagger-api/swagger-core). You should open a ticket with that library to get the issue fixed.
