### ISSUE TITLE
[develop 2.0] Option to turn off validator

### ISSUE THREAD

**Issue by makenai** [swagger-api/swagger-ui#630]
Is is possible to explicitly disable the validator?  Our API is internal, so it makes no sense for it to go out through an external server. It would be nice to have an option to do so.

Also there is a bit of code that checks for localhost, but it's hardcoded as http://localhost and won't pick up on https://localhost.

**Comment by shankar-reddy** [comment]
Fix my issue. Thanks

**Comment by rzachariah** [comment]
I'm using swagger-express-mw to obtain swagger documentation for my node service. I'm getting a schemaValidationMessages error in production, though it works locally. My swagger spec is perfectly valid.

I'm trying to disable swagger validation. I don't want to make an edit in the index.html for swagger-ui, because I'm using it through the swagger-tools node module. I tried this, which doesn't work:

```
SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }
  
  app.use(routingPath, subpath);
  
  configureSwagger(swaggerExpress.runner.swagger)

  // enable SwaggerUI
  subpath.use(swaggerExpress.runner.swaggerTools.swaggerUi({
      url: getApiDocsUrl(),
      validatorUrl : null
  }));
```

**Comment by thirupathi-redpinesignals** [comment]
How to enable client side swagger pathVariable validations to allow numbers only

**Comment by ayushidalmia** [comment]
@webron, placing the variable,         validatorUrl=null, in line 33 https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L33 does not help. It still throws the error. Please help.

<img width="719" alt="screen shot 2016-09-01 at 1 48 01 pm" src="https://cloud.githubusercontent.com/assets/5400513/18160359/bcf98d8c-704a-11e6-8852-fb8ac9d0c770.png">

**Comment by ksac1** [comment]
What i sthe solution to this problem?
