### ISSUE TITLE
Support table column alignment

### ISSUE THREAD

**Issue by tmtron** [swagger-api/swagger-ui#6401]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
openapi: 3.0.0
info:
  title: Table Align Example
  description: |
    | Option | Description |
    | -----: | -----------:|
    | ext    | extension to be used for dest files. |  
  version: '1.0'
paths:
  /:
    get:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
 ```

This can be tested on https://editor.swagger.io/

### Is your feature request related to a problem?
Some columns should be right-aligned to make it more readable (e.g. numeric)

### Describe the solution you'd like
Support column-alignment as specified in [GFM](https://docs.github.com/en/github/writing-on-github/organizing-information-with-tables#formatting-content-within-your-table)

### Describe alternatives you've considered
Alternative is to use HTML `<table>`

### Additional context
Not sure, why this does not work. In [package.json](https://github.com/swagger-api/swagger-ui/blob/v3.33.0/package.json#L91) I can see that the project uses [remarkable](https://github.com/jonschlinkert/remarkable) and in the remarkable [online-demo](https://jonschlinkert.github.io/remarkable/demo/) table column alignment works

Screenshot from remarkable [online-demo](https://jonschlinkert.github.io/remarkable/demo/)  
Column alignment works:
![image](https://user-images.githubusercontent.com/20422904/93084128-e02ea480-f693-11ea-86c6-d2b82099d024.png)

This is a screenshot from https://editor.swagger.io/  
Column alignment does not work:
![image](https://user-images.githubusercontent.com/20422904/93084087-d4db7900-f693-11ea-9423-fd1b3ec6e68d.png)

**Comment by hkosova** [comment]
First of all, OpenAPI 3.0 uses [CommonMark](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#rich-text-formatting), not GFM. CommonMark doesn't have built-in syntax for tables, but Swagger UI [uses](https://github.com/swagger-api/swagger-ui/pull/5224) Remarkable's "GFM tables" extension on top of the standard CommonMark syntax.

Back to your question, table alignment doesn't have effect because Remarkable renders it by using inline `style` attributes (e.g. `<td style="text-align:right">ext</td>`) and Swagger UI's sanitizer removes the `style`, `class`, and `data-*` attributes for security reasons. If you configure Swagger UI with [`useUnsafeMarkdown`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-useunsafemarkdown)=`true`, then your table example will render as expected.

**Comment by tmtron** [comment]
Thanks for the great explanation.

`useUnsafeMarkdown=true` works for me - just note, that this is `deprecated `
