### ISSUE TITLE
Proxy support for CORS

### ISSUE THREAD

**Issue by sdemi** [swagger-api/swagger-ui#6478]
We are having an issue with the `Try it Now` functionality because CORS headers have not been set for APIs.

We understand there is a way to provide a proxy for an API URL. We have followed suggestions for this ticket to make this update, however, it is not working for us.

https://github.com/swagger-api/swagger-ui/issues/1888#issuecomment-173179594

We have updated \dist\index.html with the following:
```
    <script>
    window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: "https://petstore.swagger.io/v2/swagger.json",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout",
        requestInterceptor: function() {
          this.url = 'http://crossorigin.me' + '/' + this.url // will change the URL used.
          return this;
        },
      })
      // End Swagger UI call region
 
      window.ui = ui
    }
  </script>
```

However, this is not working and we are getting the follow error message:
![screenshot](https://i.imgur.com/Cb6KTPj.png)

Is there an updated way of doing this? or is there an issue with how we are embedding this update?

Note - we have explored alternative options on the CORS issue. This support ticket is for setting the proxy within Swagger UI.

**Comment by mathis-m** [comment]
The error clearly states that **** origin does not provided Access-Control-Allow-Origin header. This results in the CORS error. Since you censored the url I think it is not using your request interceptor, else it would fire against crossorigin.me.

In case you try to use crossorigin.me it will not work. The domain is for sale.

Never the less if you want to do this you should take into consideration that content not from webpack is served from `swagger-ui\dev-helpers`. Guess you need to change the `index.html` there to have effect when serving via run dev.

BUT such a cors-proxy is always some kind of bad practice that should never be used in production systems. Guess you will go best with configuring CORS server side.
