### ISSUE TITLE
Swagger - Inputs text fields are cleared immediately when the fields are unfocused

### ISSUE THREAD

**Issue by sanjaykumarns** [swagger-api/swagger-ui#6516]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04.1 LTS
 - Browser: chrome
 - Version: 72.0.3626.109
 - Method of installation: npm
 - Swagger-UI version: 4.1.4
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
I am using swagger-ui-express and is working properly except for the unwanted data clearing on focusing out the input text fields

Example Swagger/OpenAPI definition:
```

{
	"swagger": "2.0",
	"info": {
		"version": "1.0.0",
		"title": "Test",
		"description": "Test Middleware",
		"license": {
			"name": "MIT",
			"url": "https://www.mit.edu/~amini/LICENSE.md"
		}
	},
	"host": "localhost:3000",
	"basePath": "",
	"paths": {}
}
```

### NPM modules using:
"express": "4.17.1"
"swagger-ui-express": "4.1.4"

### Expected behavior
The input in the Parameters' text field should stay after the text field is unfocused.

### Current Behavior
However, the input in the Parameters' text field is cleared immediately after the text field is unfocused.

### Screenshots

![screencast-nimbus-capture-2020 10 14-20_27_34](https://user-images.githubusercontent.com/6234808/96007983-b1efe080-0e5c-11eb-8bbd-acbc6600cf8f.gif)

**Comment by hkosova** [comment]
Your OpenAPI definition appears to have syntax errors, specifically, the parameters are missing the [`in`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#user-content-parameterin) attribute. You can [export the OpenAPI file](https://stackoverflow.com/q/48525546/113116) from Swagger UI and paste it into https://editor.swagger.io to check for syntax errors.

The issue may be caused by missing annotations in your source code, or it may be a bug in the library that is used to generate the OpenAPI definition from code (`swagger-ui-express`, `swagger-jsdoc`, or something else). In any case, this is something you should troubleshoot with the `swagger-ui-express` project instead:
https://github.com/scottie1984/swagger-ui-express
