### ISSUE TITLE
swagger.json loaded from petstore.swagger.io

### ISSUE THREAD

**Issue by kkretsch** [swagger-api/swagger-ui#6766]
### Q&A (please complete the following information)
 - OS: Linux debian 10.7
 - Browser: Firefox 83.0
 - Method of installation: npm
 - Swagger-UI version: swagger-tools 0.10.4
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
Both locally and on the web server I see requests trying to load swagger.json (which my project doesn't have at all) from petstore.swagger.io - locally it can load it, on the web server it is denied by the browser because of mixed content (http isn't allowed to load from https page).

I exported the server stub for nodejs from the UI at app.swaggerhub.com and did no big changes on it.

Example Swagger/OpenAPI definition:
https://api.demodata.eu/api-docs

Swagger-UI configuration options (unchanged from exported stuff):
```js
var options = {
  swaggerUi: path.join(__dirname, '/swagger.json'),
  controllers: path.join(__dirname, './controllers'),
  useStubs: process.env.NODE_ENV === 'development' // Conditionally turn on stubs (mock mode)
};
```

Source can be seen here:
https://gitlab.kretschmann.software/kai/demodata/-/tree/master

**Comment by tim-lai** [comment]
@kkretsch swagger-ui defaults to loading `http` from petstore.swagger.io. You can however, also specify https via https://petstore.swagger.io since there is a http -> https redirect on petstore.swagger.io.

**Comment by hkosova** [comment]
@kkretsch is the problem here that your code tries to load the Petstore spec _in addition to_ your own OpenAPI file? This probably happens because of this fallback code in the HTML source of https://api.demodata.eu/docs/

```js
  xhr.onreadystatechange = function () {
    var url = 'http://petstore.swagger.io/v2/swagger.json';  // <-----------

    if (xhr.readyState === XMLHttpRequest.DONE) {
      url = xhr.getResponseHeader('Swagger-API-Docs-URL');
    } else {
      console.log('Unable to get the Swagger UI URL from the server (%s): %s', xhr.status, xhr.responseText);
    }

    initSwaggerUi(url);
  };
```

This custom code comes from the [swagger-tools](https://github.com/apigee-127/swagger-tools) middleware (a third-party project), not from Swagger UI itself:
https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-ui/index.html#L95
