### ISSUE TITLE
OAuth2 Implicit flow support

### ISSUE THREAD

**Issue by domaindrivendev** [swagger-api/swagger-ui#690]
Just want to double check before I start digging into the code to see why it's not working ...
Has the OAuth2 (implicit flow) support been built into the Swagger 2.0-driven UI yet? If not, do you have any idea when this is likely to happen?

**Comment by Tvaroh** [comment]
Is there an alternative page for http://developers-blog.helloreverb.com/enabling-oauth-with-swagger/ ? It's broken currently.

**Comment by webron** [comment]
@Tvaroh sorry about that. Not sure we have that readily available, but the oauth integration is very close to change and be simplified. In the meantime, you can look at the petstore for such an integration.

**Comment by Tvaroh** [comment]
@webron, could you paste a link, please?

**Comment by webron** [comment]
http://petstore.swagger.io

**Comment by fehguy** [comment]
@Tvaroh @webron actually the oauth is disabled on petstore right now so you won't find it there.  It will be re-added shortly.

**Comment by Tvaroh** [comment]
@fehguy that's why I asked. In any case I've already figured out what I needed, thanks.

**Comment by nmarasoiu** [comment]
@webron http://developers-blog.helloreverb.com/enabling-oauth-with-swagger gives 404 - can we find the docs on how to enable swagger with OAuth2 implicit flow ON JVM in another page? Thank you

**Comment by webron** [comment]
@nmarasoiu that page was about swagger-ui, not related to JVM. The information that was there is no longer relevant to the current version of swagger-ui. In the current version you don't need to do anything for it to work, but there are additional configuration options detailed in the project's README.

If you need information about a JVM implementation, you'd need to check with the project you use.

**Comment by nmarasoiu** [comment]
@webron thanks, one more question: I could not find an URL to the authorization server among the OAuth2 parameters, do you know how can I pass this? Thank you

**Comment by webron** [comment]
The `authorizationUrl` is part of the OAuth2 definition and needs to be provided in the API definition itself.

Not really sure what you mean by `Swagger2RC3`.

Swagger-UI supports both the Swagger specification (up to version 2.0) and the OpenAPI Specification (moving forward). Different versions of the specs are supported by different versions of swagger-ui (the main README has this information).

Swagger-ui supports OAuth2 for Swagger/OpenAPI 2.0 since May 2017 and earlier. Support for it in OAS3 came in in the last few iterations. Always prefer to use the latest version.
