### ISSUE TITLE
'Try it out' does not work correctly, the wrong value is sent in the header 'Accept'

### ISSUE THREAD

**Issue by VaCool** [swagger-api/swagger-ui#7374]
hen I hit the API via Postman (or any other external client, I can manage the headers) everything works correctly with the correct values. Used it in nestjs.

When using the Swagger UI generated by this package 'Accept' header always send wrong value. It should send 'application/json'' in the header, but it always sends 'application/ocr.v1+json'.

I use @ApiHeader:
@ApiHeader({
name: 'Accept',
description: 'API version',
example: Versions.v1,
required: true,
schema: { enum: [Versions.v1], default: Versions.v1 },
})

export enum Versions {
v1 = 'application/ocr.v1+json',
}

Also add screenshots from swagger.
<img width="1440" alt="Screenshot 2021-06-24 at 16 15 37" src="https://user-images.githubusercontent.com/25550723/123283016-a4264b00-d513-11eb-8d26-8bdc99a8c8d1.png">
<img width="1440" alt="Screenshot 2021-06-24 at 16 16 16" src="https://user-images.githubusercontent.com/25550723/123283024-a5f00e80-d513-11eb-8f62-376f4b2c68a6.png">

**Comment by hkosova** [comment]
In OpenAPI 3, the `Accept` header value in requests is inferred from the [response media types](https://swagger.io/docs/specification/describing-responses/#media-types). The definitions of `Accept` as a header _parameter_ are ignored, that's why your `@ApiHeader` code does not have effect.

You need to configure your code and annotations to generate the `responses` section that would look like this:

```yaml
paths:
  /analyze:
    post:
      requestBody:
        ...
      responses:
        '200':
          description: OK
          content:
            application/application/ocr.v1+json:
              ...
```

Check the documentation of your annotations library/framework to see how to produce this OpenAPI structure.
