### ISSUE TITLE
Request Body in Callbacks Produces Error

### ISSUE THREAD

**Issue by jonathon-boldcommerce** [swagger-api/swagger-ui#7465]
### Q&A (please complete the following information)
 - OS: macOs
 - Browser: chrome
 - Version: 92.0.4515.131 (Official Build) (x86_64)
 - Method of installation: online
 - Swagger-UI version: 3.52.0
 - Swagger/OpenAPI version: OpenAPI 3.0.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: test
  description: example with callback
paths:
  /subscribe:
    post:
      summary: Subscribe to a webhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                callbackUrl:
                  type: string
                  format: uri
                  example: https://myserver.com/send/callback/here
              required:
                - callbackUrl
      callbacks:
        myEvent:
          '{$request.body#/callbackUrl}':
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Some event happened
                      required:
                        - message
              responses:
                '200':
                  description: Your server returns this code if it accepts the callback
      responses:
        '201':
          description: Webhook created
```

### Describe the bug you're encountering

There are no visual problems with rendering this yaml in Swagger UI, but the error that appears in the console says "swagger-ui-es-bundle.js:2 TypeError: Cannot read property 'getIn' of undefined" and is likely causing problems in plugin themes such as [swagger-ui-kong-theme](https://github.com/Kong/swagger-ui-kong-theme). 

### To reproduce...

1. https://editor.swagger.io/ in chrome
2. Open the developer console
2. Paste the yaml file into the editor
3. Click the /subscribe request
4. Click the Callbacks tab
5. Click "{$request.body#/callbackUrl}"
6. Notice "TypeError: Cannot read property 'getIn' of undefined" in the console

### Expected behavior

There should not be an error in the console and this should render properly using other plugins.

### Screenshots

<img width="1780" alt="Screen Shot 2021-08-17 at 9 12 50 AM" src="https://user-images.githubusercontent.com/85517928/129741941-479033b9-411a-471b-a518-400791b62431.png">

### Additional context or thoughts

Possibly related to this open issue: https://github.com/swagger-api/swagger-ui/issues/5536

**Comment by mathis-m** [comment]
@char0n This happens because the `OperationContainer` component was reused for the `Callbacks` component.
For this issue the oas3 selector `hasUserEditedBody` throws the exception at

https://github.com/swagger-api/swagger-ui/blob/fc7cdb8badb83c7783e21eea7ba569c76c706ded/src/core/plugins/oas3/components/request-body.jsx#L8-L9

because the requestBody was not resolved for the callback level, insted it tries to resolve it for `paths.{path}.{method}`, which is valid for requestBody but not for callback request bodies.

https://github.com/swagger-api/swagger-ui/blob/fc7cdb8badb83c7783e21eea7ba569c76c706ded/src/core/plugins/oas3/selectors.js#L80

This behavior was introduced by me with PR #6837

To fix this the selector `hasUserEditedBody` needs to be adjusted to recieve the full path.
In addition oas3 `requestContentType` and `requestBodyValue` selectors need to be adjusted to also take in the full path, else if the callback url is named the same like a normal path it will corrupt the state.

In addition I think that there are many pitfalls we will run into, because many oas3 reducers are build up on path and method. So if it comes to the above stated case I think it will have some weird behavior.

Do you have any architectural recomendation on how to solve this issue in a clean way?

**Comment by char0n** [comment]
This is has been addressed for [v5](https://github.com/swagger-api/swagger-ui/tree/next) in https://github.com/swagger-api/swagger-ui/pull/8509

**Comment by char0n** [comment]
Addressed for v4 in https://github.com/swagger-api/swagger-ui/pull/8510
