### ISSUE TITLE
Unknown security definition type HTTP

### ISSUE THREAD

**Issue by rajeshkumarpradhan** [swagger-api/swagger-ui#7555]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: chrome
 - Version: [e.g. 22]
 - Method of installation: npm
 - Swagger-UI version: 3.27.0
 - Swagger/OpenAPI version: 3.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### How can we help?

![image](https://user-images.githubusercontent.com/49694077/137085760-8a2baab8-3964-492b-a0fd-9827c3b89d5a.png)

**Comment by hkosova** [comment]
@rajeshkumarpradhan please post your OpenAPI YAML/JSON file.

**Comment by hkosova** [comment]
Closing due to no details provided.

<br/>

Keep in mind that security schemes with `type: http` are only supported in OpenAPI 3.x (e.g. `openapi: 3.0.0`). OpenAPI 2.0 (`swagger: '2.0'`) only has `type: basic`, `type: apiKey` and `type: oauth2`.

More info:
* [OpenAPI 3.0 Security Schemes](https://swagger.io/docs/specification/authentication/)
* [OpenAPI 2.0 Security Schemes](https://swagger.io/docs/specification/2-0/authentication/)

You can use https://editor.swagger.io to check your OpenAPI definition for syntax errors.
