### ISSUE TITLE
swagger-ui-react in Vite

### ISSUE THREAD

**Issue by oxlade39** [swagger-api/swagger-ui#7762]
### Q&A (please complete the following information)
 - OS: WIndows 10 and Ubuntu 18.04
 - Browser: Chrome
 - Version: Version 94.0.4606.71 (Official Build) (64-bit)
 - Method of installation: npm
 - Swagger-UI version: "swagger-ui-react": "^4.1.3"

### Content & configuration

Swagger-UI configuration options:
```js
import SwaggerUI from 'swagger-ui-react'
import 'swagger-ui-react/swagger-ui.css'

function Swagger({ openAPIUrl }) {
    return <SwaggerUI url={openAPIUrl} />
}

export default Swagger;
```

```
[vite] connecting...
client.ts:52 [vite] connected.
prism.js:721 Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/safe-buffer/index.js (prism.js:721)
    at __require (chunk-ESTXZSVW.js?v=1766c466:12)
    at node_modules/randombytes/browser.js (prism.js:766)
    at __require (chunk-ESTXZSVW.js?v=1766c466:12)
    at Object.<anonymous> (swagger-ui.js:2)
    at n (email-matcher.ts:334)
    at Object.<anonymous> (url-matcher.ts:146)
    at Object.<anonymous> (parse-html.ts:296)
    at n (email-matcher.ts:334)
    at Module.<anonymous> (swagger-ui.js:2)
```

### How can we help?
I'm wondering if anyone has had success with swagger-ui-react in Vite. I just tried the most basic example after installing `swagger-ui-react`.

Firstly I received an error with `isarray` as a missing dependency. This was easily rectified by npm installing the library. After this I get the above error when importing `import SwaggerUI from 'swagger-ui-react'`. I can't really work out what the problem is why it might be happening but wondering if I need to do something special to get it working in Vite, although I don't think it should be necessary.

Thanks

**Comment by oxlade39** [comment]
I think I have resolved this by adding a dependency on "Buffer" and then using the following `vite.config.js`

```javascript
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react({ jsxRuntime: "classic" })],
  define: {
    global: {}
  }
})
```

the important addition being:
```javascript
  define: {
    global: {}
  }
```

**Comment by panzelva** [comment]
Just for reference - I solved this by adding `<script>window.global = window;</script>` on top of `index.html` like so:

```
<!DOCTYPE html>
<html lang="en">

<head>
  <script>window.global = window;</script>

  <meta charset="UTF-8" />
  <link rel="icon" type="image/svg+xml" href="/src/favicon.svg" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>app name</title>
</head>

<body>
  <div id="app"></div>
  <script type="module" src="/src/main.tsx"></script>
</body>

</html>
```

and by installing `buffer` package and setting it on window object like this:
```
import { Buffer } from "buffer"
window.Buffer = Buffer

ReactDOM.render(<App/>)
```

Setting
```
define: {
  global: {}
}
```
is not good idea, it can break many other things (because its just regex replacement - more info here: https://vitejs.dev/config/#define)

**Comment by xepozz** [comment]
Same for me when using react + vite + originjs/vite-plugin-federation

<img width="559" alt="image" src="https://github.com/swagger-api/swagger-ui/assets/6815714/896160ee-7a81-489a-b8ea-4156c94b9fa5">

`m` in the screenshot further looks like `React` because it has `useRef` / `useContext` and a few other react's hooks
<img width="783" alt="image" src="https://github.com/swagger-api/swagger-ui/assets/6815714/91ef4552-9799-420a-858e-7b2180835a66">

**Comment by char0n** [comment]
Hi everybody,

Since [SwaggerUI@4.10.0](https://github.com/swagger-api/swagger-ui/releases/tag/v4.10.0) this should no longer manifest as an issue. I've created a POC repo to prove this.

Hope it helps.
