### ISSUE TITLE
Swagger UI does not show ref type name when it is nullable

### ISSUE THREAD

**Issue by josephearl** [swagger-api/swagger-ui#7992]
Given the following OAS 3 schema:

```
---
openapi: 3.0.3
info:
  title: Family
  description: Family API
  version: 1.0.0
paths:
  /family/one:
    get:
      tags:
      - Family
      responses:
        "200":
          description: Parent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parent'
components:
  schemas:
    Child:
      type: object
      properties:
        name:
          type: string
    Parent:
      type: object
      properties:
        firstChild:
          $ref: '#/components/schemas/Child'
        secondChild:
          nullable: true
          allOf:
          - $ref: '#/components/schemas/Child'
```

The schema for parent does not show the referenced name for secondChild:

![Screenshot 2022-04-22 at 09 57 22](https://user-images.githubusercontent.com/2513147/164671599-e5e8fa5d-f82f-434b-8331-05fbc0a4be59.png)

**Comment by Isitar** [comment]
any update on this?

**Comment by holistic-developer** [comment]
It is questionable whether it makes sense to use allOf with just one schema

**Comment by simonachmueller** [comment]
We are also running in the same issue, any update on it or workaround?

**Comment by glowcloud** [comment]
Hi everyone,

1. When using `allOf`, it's actually the expected behaviour that the name of the referenced schema isn't carried over. If you want these schemas to display the same name, you can set a title within the referenced schema:
   ```yaml
   Child:
     title: Child
     type: object
     properties:
       name:
         type: string
   ```
2. When using `$ref`, any additional fields defined in the same object will be ignored, as specified for [JSON Reference Object](https://datatracker.ietf.org/doc/html/draft-pbryan-zyp-json-ref-03#section-3):

    > Any members other than "$ref" in a JSON Reference object SHALL be ignored.
    
    which is why `nullable` won’t show up if defined alongside a reference.
