### ISSUE TITLE
Missing btoa module dependency

### ISSUE THREAD

**Issue by emerikool** [swagger-api/swagger-ui#8018]
The btoa module dependency is missing.
Getting the error since swagger client has recently removed this dependency.

**Comment by tim-lai** [comment]
@char0n Would you be able to take a look at this?

**Comment by abdulazizali77** [comment]
got this problem today in our upstream project, had to manually add `btoa` to our npm deps, after some investigation it turns out the `swagger-js` dep removed the `btoa` dep and replaced it with its own internal helper
https://github.com/swagger-api/swagger-js/commit/4832f3249df3415b168fcd3ac45eb1a463c038b8

**Comment by BekzodbekTurgunov** [comment]
I added btoa to my package.json and resolved this issue
![image](https://user-images.githubusercontent.com/48333057/168629778-158895b6-56cd-4f7b-abaa-5511f7955a89.png)

**Comment by abdulazizali77** [comment]
Thanks @char0n , were using `4.1.0`, using `4.11.0` fixes it

**Comment by char0n** [comment]
Glad  to hear that. Closing this as resolved. For older versions `SwaggerUI < 4.9.0`, `btoa` has to be explicitly added as demonstrated in https://github.com/swagger-api/swagger-ui/issues/8018#issuecomment-1127823683. In `SwaggerUI >= 4.9.0` removing a dependency in swagger-client is not longer an issue for SwaggerUI.
