### ISSUE TITLE
How to add textarea in swagger ? 

### ISSUE THREAD

**Issue by jocartboy2** [swagger-api/swagger-ui#8552]
### Q&A (please complete the following information)
 - OS: windows 10
 - Browser: chrome
 - Version: 111.0.5563.147
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]
 
https://github.com/DarkaOnLine/L5-Swagger  version 8.0

### Parameter in swagger

     *     @OA\Parameter(
     *         name="bio",
     *         description="bio",
     *         in="query",
     *         @OA\Schema(
     *             type="string",     
     *             example=""
     *         ),
     *     ),
 
### Additional context or thoughts
Sorry just want to add I am using  darkaonline/l5-swagger on my laravel project I couldn't find a way to add a textarea instead of textbox is anyone have an idea ? thank you.

**Comment by char0n** [comment]
Hi @jocartboy2,

What do you mean by "How to add textarea in swagger?". I'm not sure I understand.

**Comment by char0n** [comment]
I'm still not sure I understand. Please provide more information that are actionable, otherwise I'll close this issue.

**Comment by michaeloliverx** [comment]
I think what he means is for example if you had a query param that accepted a SQL query then having a multiline textbox in the Swagger UI instead of a text input would be more suitable because you could include newline characters etc.

I was searching for the same functionality and came across this.

**Comment by char0n** [comment]
In order to achieve that, you'll have to create new SwaggerUI plugin that overrides [JsonSchemaForm](https://github.com/swagger-api/swagger-ui/blob/1ce9ce0cda2a55bf3896c0d89706400a83ba1d7e/src/core/json-schema-components.jsx) as this is the component that renders the input component.

The plugin would look like this:

```
const CustomJsonSchemaFormPlugin => ({
  components: {
    JsonSchemaForm: MyCustomSchemaForm,
  }
});
```

And then you need to register it when initializing the SwaggerUI:

```js
  const ui = SwaggerUIBundle({
    url: "https://petstore.swagger.io/v2/swagger.json",
    dom_id: "#swagger-ui",
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl,
      CustomJsonSchemaFormPlugin,
    ],
    // requestSnippetsEnabled: true,
    layout: "StandaloneLayout"
  })
```
