### ISSUE TITLE
Internet Explorers "Compatibilty View"-Mode is incompatible to swagger-ui

### ISSUE THREAD

**Issue by ssindelar** [swagger-api/swagger-ui#859]
I just gave a new version which includes swagger-ui to our QA and they complained it wouldn't work at all.

After some back and forth I found the issue. They tested it using Internet Explorer and the test system was on the intranet. This caused the Internet Explorer to automatically fall into a "Compatiblity View" mode which made it incompatible to swagger-ui (which irony ..). 
It shows the following errors (translated from german):

* shred.bundle.js: line 2211, col:1 - there seems to be a "," too much.
* swagger-client.js: line 13, col 35 - enum seems to be a reserved keyword.

I tested it on IE 11 with swagger-ui 2.1.0-alpha.4. Sadly I can't skip on the IE compatibilty completly. :(

**Comment by fehguy** [comment]
Hi, there is a solution...

Swagger-UI should detect that it's being used by internet explorer and fall back to use JQuery instead of Shred, which has perfectly good support for IE.  This is detected here:

https://github.com/swagger-api/swagger-ui/blob/master/lib/swagger-client.js#L1390-L1398

Now, you'll see that it's detecting "IE8" based on the user agent.  Can you please log what you're getting from IE right here:

https://github.com/swagger-api/swagger-ui/blob/master/lib/swagger-client.js#L1408

By adding a line like such:

```
log(navigator.userAgent);
```

and report back what you got?

**Comment by fehguy** [comment]
both the issues you mentioned have been addressed.  Please retry and reopen if you have troubles.
