### ISSUE TITLE
OpenAPI 3.1.0 support: GET request body support with OpenAPI 3.1, swagger-ui 5.X

### ISSUE THREAD

**Issue by Nikit123** [swagger-api/swagger-ui#8682]
### Q&A (please complete the following information)
 - OS: [macOS]
 - Browser: [chrome]
 - Version: [113.0]
 - Method of installation: [dist assets]
 - Swagger-UI version: [5.0.0-alpha.13]
 - Swagger/OpenAPI version: [OpenAPI 3.1]

### How can we help?
I am using a GET api, where I need to send a request body. I took 5.0.0-alpha.13 distribution of swagger, as I saw that it is compatible with OpenAPI 3.1. Although, when I am running it with OpenAPI 3.1, and trying to execute my GET api I still get this error - 'TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body'.

My server handles the GET request body as I have tested it with Postman and I know that OpenAPI 3.1 supports request body with GET requests. Why is swagger-ui not allowing me to do the same? Am I missing something, or this support is not in place and planned for a future release?

**Comment by char0n** [comment]
Hi @Nikit123,

> I am using a GET api, where I need to send a request body. I took 5.0.0-alpha.13 distribution of swagger, as I saw that it is compatible with OpenAPI 3.1

Yes, this is true

> Although, when I am running it with OpenAPI 3.1, and trying to execute my GET api I still get this error - 'TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body'.

Yes, this is expected behavior. I'll explain further below.

> My server handles the GET request body as I have tested it with Postman and I know that OpenAPI 3.1 supports request body with GET requests. Why is swagger-ui not allowing me to do the same? Am I missing something, or this support is not in place and planned for a future release?


`I know that OpenAPI 3.1 supports request body with GET requests` - I wouldn't agree with this claim. 

Here is what **OpenAPI 3.0.3** has to say about it:

![image](https://github.com/swagger-api/swagger-ui/assets/193286/b47e03f4-ac96-43cd-bfe3-a631eb472093)

Here is what **OpenAPI 3.1.0** has to say about it:

![image](https://github.com/swagger-api/swagger-ui/assets/193286/ae35084a-25a4-4b47-9a1b-00725ff0f710)

---

Now if we take GET method and read what [RFC7231](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.1) has to say about it:

![image](https://github.com/swagger-api/swagger-ui/assets/193286/1f013d11-e811-4e24-987d-4ee07e2d110b)

OpenAPI 3.1.0 considers RFC7231s `no defined semantics` to be vague, but HTTP clients in JavaScript ([Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), [XHR](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), Node.js) don't consider it vague and just forbids to send any payloads along with the `GET` requests. This is not specific to SwaggerUI, this is specific to JavaScript HTTP APIs. As far as I can tell it is not possible to send GET request with payload in JavaScript.

SwaggerUI will pass your GET request as it is to the underlying HTTP client. Inside browser, the HTTP clients happens to be [Fetch API]((https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). Fetch API doesn't allow to do GET requests with payloads and triggers the type error you're seeing:  `'TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body'`.

---

Best way to avoid this issue to comply with the OpenAPI 3.1.0 and RFC7231 and not use payloads for HTTP methods, which do not have semantics explicitly defined.
