### ISSUE TITLE
models fields of type array show as their member type, not as array

### ISSUE THREAD

**Issue by todd-richmond** [swagger-api/swagger-ui#915]
A Java field of Set<Long> and annotated with

@ApiModelProperty(value = "counts", dataType = "List[long]")

```js
groups : {
  type: "array",
  description: "counts",
  items: {
  type: "integer",
  format: "int64"
  }
}
```
shows as "counts (long, optional)" instead of "counts (array[long], optional]" in the "model" tab

However, the "model schema" tab shows an example properly as an array of longs so this might just be a ui issue

**Comment by ralphvanetten** [comment]
I stumbled upon the same bug. This seems to be already fixed by #876

**Comment by domaindrivendev** [comment]
Same issue reported through Swashbuckle ...

https://github.com/domaindrivendev/Swashbuckle/issues/200

In summary, there are two issue scenarios mentioned:

1. Complex array in response section - "Model" tab displays as the item type instead of an array of the item type.
2. Complex array request param. - just shows up as "array[#/defintitions/ListItemDto]" without actually showing the model descriptions.

Am I correct in saying these issues will be fixed in the M2 milestone?

**Comment by mohsen1** [comment]
If I understood this correctly, if `items` of an schema is a JSON Ref, the UI will not resolve the `$ref` before rendering it.

For example, this Swagger specs:

```yaml
---
swagger: '2.0'
info:
  version: 1.0.0
  title: Pets Store
paths:
  /pets:
    get:
      parameters:
        - name: blah
          in: body
          description: description
          schema:
            $ref: '#/definitions/blah'

        
      responses:
        200:
          description: Returns all the pet
definitions:
  blah:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/arritem'
  arritem:
    type: string
```

Will get rendered like this:

![screen shot 2015-03-03 at 3 25 32 pm](https://cloud.githubusercontent.com/assets/543633/6474871/92f0d4f0-c1b9-11e4-9428-dae70935a127.png)
![screen shot 2015-03-03 at 3 25 37 pm](https://cloud.githubusercontent.com/assets/543633/6474872/92f19a5c-c1b9-11e4-9b16-17cb7e292640.png)


This is a valid bug.

**Comment by mohsen1** [comment]
Please follow this issue here: https://github.com/swagger-api/swagger-js/issues/270
