### ISSUE TITLE
Convert all CoffeeScript files to JavaScript

### ISSUE THREAD

**Issue by mohsen1** [swagger-api/swagger-ui#961]
This needs to be done after:

* [ ] All PRs are merged 
* [ ] We have enough tests to ensure it's not breaking anything 

Also remove coffee-script dependency from package.json and gulpfile.js

**Comment by ngocdaothanh** [comment]
Just curious, why do you not want to use CoffeeScript any more?

**Comment by fehguy** [comment]
It made ugly javascript and was a barrier to community contributions.  It's a fine structure, but we felt it better to be pure js for this project.

**Comment by guicamest** [comment]
-1
Contributors must know of coffee script. It's way better than pure JS.

**Comment by fehguy** [comment]
I am sorry, there's no way to make everyone happy with this.  We did make the call to move to pure js intentionally.  We did the same thing in swagger-core, by removing scala and going to pure java.

**Comment by mohsen1** [comment]
This was done via following commits:

215a8fa
f21ade9
c858357
140dc77
e3a502c
7755235
a11fd8b
dc4e595
dc9ce7d
72dad96
3944828
734ad71
f211be4
15d1e22
846d589

**Comment by guicamest** [comment]
Thanks @mohsen1 !
@fehguy One thing is to move from scala to java which i think it's totally ok if someone wants to use swagger's model without having to use scala; and another totally different thing is moving from coffeescript to plain js. IMHO, CoffeeScript makes it far easier to read, understand and modify UI than JS, while still getting the same result: JS. If you did it for significantly performance improvements, I would understand it, but doing the change just to avoid a "barrier to community contributions", i think it's a bad decision. You had already coffee integrated with the build process, contributors have to build everything anyway. I really think you should think this over again. If you decide to stick to plain js, I guess I'll have to deal with it, it's your project and a good one btw.

**Comment by fehguy** [comment]
Hey @guicamest thanks.  I know it's a big change, and some people won't like it.  We felt it makes sense for the overall picture.  I'm glad you like the project and I'm sure you'll like the other stuff coming down the line.

**Comment by mcuba** [comment]
I agree with guicamest 
-1
Contributors must know of coffee script. It's way better than pure JS.

**Comment by lautaromei** [comment]
-1 

CoffeScript is better and clear than JS

**Comment by fehguy** [comment]
suggestion for everyone on this thread and who might discover it.  I know this is asking a lot, but when you see a ticket like this get filed (almost a month ago), please chime in before the work is done.  That's the best way to get your input heard on a community project like swagger.  This change wasn't done for commercial reasons--it was done based on community feedback.

**Comment by whitlockjc** [comment]
Since most of the pro-CoffeeScript comments I see are purely opinion, I doubt we will have much meaningful conversation if we focus on _CoffeeScript vs. JavaScript_.  That being said, CoffeeScript is a great language and it has served a purpose but in the end we have to think of the main contributors and the ease of development/maintenance for them.  Not only that but we have to think of the big picture when it comes to consistency across other Swagger projects and even the user experience.  _(For example, end users can use the non-minified code and see the same code that the developers see which should make bug reports simpler, and the runtime errors more meaningful.  That alone is good enough reason to do this if you ask me.)_

I realize not being able to use CoffeeScript might not be ideal for some but it should not impact your ability to contribute to the project.
