### ISSUE TITLE
` You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".`

### ISSUE THREAD

**Issue by MartinX3** [swagger-api/swagger-ui#9865]
### Q&A (please complete the following information)
 - OS: Arch Linux
 - Browser: Chromium
 - Version: 124.0.6367.60
 - Method of installation: pnpm
 - Swagger-UI version: 5.17.0

### Content & configuration
Quasar (VueJS + Vite)
TypeScript

### Describe the bug you're encountering
Using the development console I see:
```
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".
```

```html
<div id="swagger-ui" />
```

```ts
SwaggerUI({
  dom_id: '#swagger-ui',
  spec: document.value.content,
})
```

### To reproduce...

Use quasar/vueJS and open your browser.

### Expected behavior
Seeing that I don't use react.
I use the npm package `swagger-ui` and not `swagger-ui-react`.

### Additional context or thoughts
I saw this comment.
https://github.com/swagger-api/swagger-ui/issues/9598#issuecomment-1948044802
But I don't use react at all.

**Comment by char0n** [comment]
Hi @MartinX3,

`swagger-ui` is using React under the hood and that's where the warning comes from. React detects the following: 

```js
process.env.NODE_ENV === 'production'
```

If it's true, than React will use it's production bundles, which don't trigger above mentioned warning you're seeing. 

You're seeing the warning either because your build environment probably doesn't set `NODE_ENV` environment variable or it does set it, but you're only seeing the warning in development mode, not  when you've actually build the production bundles.
