### ISSUE TITLE
Send query parameter as collectionFormat: 'multi' or 'brackets'

### ISSUE THREAD

**Issue by exoszajzbuk** [swagger-api/swagger-ui#987]
I'm using the current `develop_2.0` branch and http://petstore.swagger.io/v2/swagger.json which has `collectionFormat: "multi"` set on pet/findByStatus.

If I understand it right, it should send the query parameters as tags=tag1&tags=tag2, if I enter a comma-separated string for the value field. Instead, it sends the parameters by simply encoding the comma.

What I'd be really interested in is `collectionFormat: "brackets"`, which is not yet present in the v2.0 spec https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md but seems to be already implemented in `swagger-ui` https://github.com/swagger-api/swagger-ui/blob/master/dist/lib/swagger-client.js#L1440

**Comment by fehguy** [comment]
Hi, the UI is not doing the right thing.  The issue is that when sending multiple values, the UI is treating them as a single one, which is then being encoded by the swagger-js logic.

There are two options I can think of for this:
1) give the user a text box, and newline means "new value".  The UI will then turn the multi-lines into an array
2) expose the delimiter and split on it

I'm partial to solution (1) because requiring a delimiter is really making it less usable.  I'd prefer that the user doesn't care about how it's split (that's the UI's job).

Thoughts?

**Comment by webron** [comment]
+(1)

**Comment by kswin** [comment]
I'm on Swagger UI version "2.1.8-M1" and I still see this issue. 

I debugged the code a bit and it looks like collectionFormat="multi" does not work as expected because of line 1120 in swagger-client.js. The condition "Array.isArray(qp)" does not evaluate to true because qp is a string. When I input, "a", "b", "c" from the swagger ui param input box, qp evaluates to "'a', 'b', 'c'" instead of ['a', 'b', 'c']. 

Since the condition fails, this.encodeQueryCollection is not called and encodeQueryCollection looks like the function that transforms the array into the "tags=tag1&tags=tag2" format.

qp comes from the "args" argument which is passed in early on in the call stack. 

When I replace lines 1119-1121, with the following code, then an input of "a", "b", "c" seems to work as expected.
```
var qp = args[param.name],
              qpArray = qp.replace(/"|'|\s/g, '').split(',');
          if(Array.isArray(qpArray))
            querystring += this.encodeQueryCollection(param.collectionFormat, param.name, qpArray);
``` 

The above code feels like a fragile workaround - I wanted to post it to illustrate that Array.isArray(qp) seems to be the source of the error.

**Comment by fehguy** [comment]
Please look at 2.1.0-M2, released today.

**Comment by kswin** [comment]
The issue exists as I described it, but now it's in swagger-ui.js lines 3422-3425.

**Comment by mjgp2** [comment]
A newline would be preferable, it at least gives a hint to the user you can have more than one value. If you use a comma you get into the awful issue of quoting commas in the value which I think we could all agree is asking the user to go too far.

**Comment by kswin** [comment]
+1 mjgp2

It wasn't immediately obvious that I should enter a comma-separated string until I found this post...

**Comment by fehguy** [comment]
This needs to be handled in swagger-ui.  It's entirely a UI issue.  We'll address in this upcoming release.

**Comment by fehguy** [comment]
we have added support to allow multi-line entries to send as arrays.
